# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Helpers for pyCirclize-backed circular plots.
"""
from _typeshed import Incomplete
import itertools
import sys
from pathlib import Path
from typing import Any, Callable, Mapping, Optional, Sequence, Union
from matplotlib.projections.polar import PolarAxes as MplPolarAxes
from ... import constructor
from ...config import rc
_PYCIRCLIZE_RC_LEAKS = ('savefig.bbox', 'savefig.pad_inches', 'svg.fonttype')

def _import_pycirclize() -> Incomplete:
    """Import pycirclize without letting it restyle the session.

``pycirclize.config`` runs ``mpl.rcParams.update(...)`` at import time,
setting ``savefig.bbox='tight'`` and ``savefig.pad_inches=0.5``. Since the
import is lazy, the first chord, radar, phylogeny or circos plot in a
session would otherwise silently change the size and padding of every
figure saved afterwards."""
    ...

def _import_pycirclize_unguarded() -> Incomplete:
    ...

def _unwrap_axes(ax: Incomplete, label: str) -> Incomplete:
    ...

def _ensure_polar(ax: Incomplete, label: str) -> Incomplete:
    ...

def _cycle_colors(n: int) -> list[str]:
    ...

def _resolve_chord_defaults(matrix: Any, cmap: Any) -> Incomplete:
    ...

def _resolve_radar_defaults(table: Any, cmap: Any) -> Incomplete:
    ...

def circos(ax: Incomplete, sectors: Mapping[str, Any], *, start: float=0, end: float=360, space: float | Sequence[float]=0, endspace: bool=True, sector2clockwise: Mapping[str, bool] | None=None, show_axis_for_debug: bool=False, plot: bool=False, tooltip: bool=False) -> Incomplete:
    """Create a pyCirclize Circos instance (optionally plot immediately)."""
    ...

def chord_diagram(ax: Incomplete, matrix: Any, *, start: Optional[float]=None, end: Optional[float]=None, space: Optional[Union[float, Sequence[float]]]=None, endspace: Optional[bool]=None, r_lim: Optional[tuple[float, float]]=None, cmap: Any=None, link_cmap: Optional[list[tuple[str, str, str]]]=None, ticks_interval: Optional[int]=None, order: Optional[Union[str, list[str]]]=None, label_kw: Optional[Mapping[str, Any]]=None, ticks_kw: Optional[Mapping[str, Any]]=None, link_kw: Optional[Mapping[str, Any]]=None, link_kw_handler: Incomplete=None, tooltip: bool=False) -> Incomplete:
    """Render a chord diagram using pyCirclize on the provided polar axes."""
    ...

def radar_chart(ax: Incomplete, table: Any, *, r_lim: Optional[tuple[float, float]]=None, vmin: Optional[float]=None, vmax: Optional[float]=None, fill: Optional[bool]=None, marker_size: Optional[int]=None, bg_color: Optional[str]=None, circular: Optional[bool]=None, cmap: Any=None, show_grid_label: Optional[bool]=None, grid_interval_ratio: Optional[float]=None, grid_line_kw: Optional[Mapping[str, Any]]=None, grid_label_kw: Optional[Mapping[str, Any]]=None, grid_label_formatter: Incomplete=None, label_kw_handler: Incomplete=None, line_kw_handler: Incomplete=None, marker_kw_handler: Incomplete=None) -> Incomplete:
    """Render a radar chart using pyCirclize on the provided polar axes."""
    ...

def phylogeny(ax: Incomplete, tree_data: Any, *, start: Optional[float]=None, end: Optional[float]=None, r_lim: Optional[tuple[float, float]]=None, format: Optional[str]=None, outer: Optional[bool]=None, align_leaf_label: Optional[bool]=None, ignore_branch_length: Optional[bool]=None, leaf_label_size: Optional[float]=None, leaf_label_rmargin: Optional[float]=None, reverse: Optional[bool]=None, ladderize: Optional[bool]=None, line_kw: Optional[Mapping[str, Any]]=None, label_formatter: Incomplete=None, align_line_kw: Optional[Mapping[str, Any]]=None, tooltip: bool=False) -> Incomplete:
    """Render a phylogenetic tree using pyCirclize on the provided polar axes."""
    ...

def circos_bed(ax: Incomplete, bed_file: Any, *, start: float=0, end: float=360, space: float | Sequence[float]=0, endspace: bool=True, sector2clockwise: Mapping[str, bool] | None=None, plot: bool=False, tooltip: bool=False) -> Incomplete:
    """Create a Circos instance from a BED file (optionally plot immediately)."""
    ...
