# @generated by tools/generate_stubs.py; do not edit
# fmt: off
from _typeshed import Incomplete
__all__ = ['CurvedQuiverSolver', 'CurvedQuiverSet']
from typing import Callable
from dataclasses import dataclass
from matplotlib.streamplot import StreamplotSet
import numpy as np

@dataclass
class CurvedQuiverSet(StreamplotSet):
    lines: object
    arrows: object

@dataclass
class _CurvedQuiverTrajectory:
    x: list[float]
    y: list[float]
    hit_edge: bool
    end_direction: tuple[float, float] | None

class _DomainMap(object):
    """Map representing different coordinate systems.

Coordinate definitions:
* axes-coordinates goes from 0 to 1 in the domain.
* data-coordinates are specified by the input x-y coordinates.
* grid-coordinates goes from 0 to N and 0 to M for an N x M grid,
    where N and M match the shape of the input data.
* mask-coordinates goes from 0 to N and 0 to M for an N x M mask,
    where N and M are user-specified to control the density of
    streamlines.

This class also has methods for adding trajectories to the
StreamMask. Before adding a trajectory, run `start_trajectory` to
keep track of regions crossed by a given trajectory. Later, if you
decide the trajectory is bad (e.g., if the trajectory is very
short) just call `undo_trajectory`."""

    def __init__(self, grid: Incomplete, mask: Incomplete) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    def grid2mask(self, xi: float, yi: float) -> tuple[int, int]:
        """Return nearest space in mask-coords from given grid-coords."""
        ...

    def mask2grid(self, xm: int, ym: int) -> tuple[float, float]:
        ...

    def data2grid(self, xd: float, yd: float) -> tuple[float, float]:
        ...

    def grid2data(self, xg: float, yg: float) -> tuple[float, float]:
        ...

    def start_trajectory(self, xg: float, yg: float) -> None:
        ...

    def reset_start_point(self, xg: float, yg: float) -> None:
        ...

    def update_trajectory(self, xg: float, yg: float) -> None:
        ...

    def undo_trajectory(self) -> None:
        ...

class _CurvedQuiverGrid(object):
    """Grid of data."""

    def __init__(self, x: np.ndarray, y: np.ndarray) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    @property
    def shape(self) -> tuple[int, int]:
        ...

    def within_grid(self, xi: float, yi: float) -> bool:
        """Return True if point is a valid index of grid."""
        ...

class _StreamMask(object):
    """Mask to keep track of discrete regions crossed by streamlines.

The resolution of this grid determines the approximate spacing
between trajectories. Streamlines are only allowed to pass through
zeroed cells: When a streamline enters a cell, that cell is set to
1, and no new streamlines are allowed to enter."""

    def __init__(self, density: float | int) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    def __getitem__(self, *args: Incomplete) -> Incomplete:
        ...

    def _start_trajectory(self, xm: int, ym: int) -> Incomplete:
        """Start recording streamline trajectory"""
        ...

    def _undo_trajectory(self) -> Incomplete:
        """Remove current trajectory from mask"""
        ...

    def _update_trajectory(self, xm: int, ym: int) -> None:
        """Update current trajectory position in mask.

If the new position has already been filled, raise
`InvalidIndexError`."""
        ...

class _CurvedQuiverTerminateTrajectory(Exception):
    pass

class CurvedQuiverSolver:

    def __init__(self, x: np.ndarray, y: np.ndarray, density: float | tuple[float, float]) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    def get_integrator(self, u: np.ndarray, v: np.ndarray, minlength: float, resolution: float, magnitude: np.ndarray) -> Callable[[float, float], _CurvedQuiverTrajectory | None]:
        ...

    def integrate_rk12(self, x0: float, y0: float, f: Callable[[float, float], tuple[float, float]], resolution: float, magnitude: np.ndarray) -> tuple[list[float], list[float], bool]:
        """2nd-order Runge-Kutta algorithm with adaptive step size.

This method is also referred to as the improved Euler's method, or
Heun's method. This method is favored over higher-order methods
because:

1. To get decent looking trajectories and to sample every mask cell
on the trajectory we need a small timestep, so a lower order
solver doesn't hurt us unless the data is *very* high
resolution. In fact, for cases where the user inputs data
smaller or of similar grid size to the mask grid, the higher
order corrections are negligible because of the very fast linear
interpolation used in `interpgrid`.

2. For high resolution input data (i.e. beyond the mask
resolution), we must reduce the timestep. Therefore, an
adaptive timestep is more suited to the problem as this would be
very hard to judge automatically otherwise.

This integrator is about 1.5 - 2x as fast as both the RK4 and RK45
solvers in most setups on my machine. I would recommend removing
the other two to keep things simple."""
        ...

    def euler_step(self, xf_traj: Incomplete, yf_traj: Incomplete, f: Incomplete) -> Incomplete:
        """Simple Euler integration step that extends streamline to boundary."""
        ...

    def interpgrid(self, a: Incomplete, xi: Incomplete, yi: Incomplete) -> Incomplete:
        """Fast 2D, linear interpolation on an integer grid"""
        ...

    def gen_starting_points(self, x: Incomplete, y: Incomplete, grains: Incomplete) -> Incomplete:
        ...
