ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.2
    hooks:
      - id: pydoclint
        args: [--style=numpy]
