# .readthedocs.yml
# Read the Docs configuration file
version: 2

# Python config
build:
  os: ubuntu-22.04
  tools:
    python: miniforge-latest
conda:
  environment: ./environment.yml

sphinx:
  configuration: ./docs/conf.py
  builder: html

python:
  install:
    - method: pip
      path: .

commands:
  pre_build:
    - locale -a
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - pip install .
