name: ultraplot-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - numpy
  - matplotlib>=3.9
  - cartopy
  - xarray
  - seaborn
  - pandas
  - pytest
  - pytest-mpl
  - jupyter
  - pip
  - pint
  - sphinx
  - nbsphinx
  - jupytext
  - sphinx-copybutton
  - sphinx-autoapi
  - sphinx-automodapi
  - sphinx-rtd-theme
  - base
  - pip:
      - git+https://github.com/ultraplot/UltraTheme.git
