name: ultraplot-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.14
  - numpy>=2.2
  - matplotlib>=3.9.3
  - cartopy
  - xarray
  - seaborn
  - pandas
  - pytest
  - pytest-mpl
  - jupyter
  - pip
  - basemap
  - pint
  - sphinx
  - nbsphinx
  - jupytext
  - sphinx-copybutton
  - sphinx-autoapi
  - sphinx-automodapi
  - pip:
      - git+https://github.com/ultraplot/UltraTheme.git
