# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Utilities for modifying ultraplot docstrings.
"""
from _typeshed import Incomplete
import inspect
import re
from typing import Any, Callable, TypeVar, cast, overload
from . import ic
_F = TypeVar('_F', bound=Callable[..., Any])
_T = TypeVar('_T')

def _obfuscate_kwargs(func: _F) -> _F:
    """Mark keyword arguments as compact in generated API documentation."""
    ...

def _obfuscate_params(func: _F) -> _F:
    """Mark all parameters as compact in generated API documentation."""
    ...

def _obfuscate_signature(func: _F, dummy: Callable[..., Any]) -> _F:
    """Mark a misleading or incomplete signature as compact in generated docs.

The callable's actual signature remains available to Python and language
servers; Sphinx reads the marker below when rendering API headings."""
    ...

def _concatenate_inherited(func: _F, prepend_summary: bool=False) -> _F:
    """Concatenate docstrings from a matplotlib axes method with a ultraplot
axes method and mark its generated-documentation signature as compact."""
    ...

class _SnippetManager(dict):
    """A simple database for handling documentation snippets."""
    _lazy_modules = {'axes': 'ultraplot.axes.base', 'cartesian': 'ultraplot.axes.cartesian', 'polar': 'ultraplot.axes.polar', 'geo': 'ultraplot.axes.geo', 'plot': 'ultraplot.axes.plot', 'figure': 'ultraplot.figure', 'gridspec': 'ultraplot.gridspec', 'legend': 'ultraplot.legend', 'ticker': 'ultraplot.ticker', 'proj': 'ultraplot.proj', 'colors': 'ultraplot.colors', 'utils': 'ultraplot.utils', 'config': 'ultraplot.config', 'demos': 'ultraplot.demos', 'rc': 'ultraplot.axes.base'}

    def __missing__(self, key: Incomplete) -> Incomplete:
        """Attempt to import modules that populate missing snippet keys."""
        ...

    @overload
    def __call__(self, obj: str) -> str:
        """Add snippets to the string or object using ``%(name)s`` substitution. Here
``%(name)s`` is used rather than ``.format`` to support invalid identifiers."""
        ...

    @overload
    def __call__(self, obj: _T) -> _T:
        """Add snippets to the string or object using ``%(name)s`` substitution. Here
``%(name)s`` is used rather than ``.format`` to support invalid identifiers."""
        ...

    def __setitem__(self, key: Incomplete, value: Incomplete) -> None:
        """Populate input strings with other snippets and strip newlines. Developers
should take care to import modules in the correct order."""
        ...
_snippet_manager = _SnippetManager()
_units_docstring = ...

def _aliases_note(*names: Incomplete) -> str:
    """Render a compact ``Aliases: ...`` note for a style parameter. The canonical
name leads the numpydoc field; the common documented synonyms go here so the
parameter reads cleanly instead of opening with a pile of alias names."""
    ...
_line_docstring = ...
_patch_docstring = ...
_pcolor_collection_docstring = ...
_contour_collection_docstring = ...
_text_docstring = ...
