# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Utilities for processing input data passed to plotting commands.
"""
from _typeshed import Incomplete
import functools
import sys
from typing import Any, Callable, TypeVar, cast
import numpy as np
import numpy.ma as ma
from . import ic
from . import _not_none, warnings
try:
    from cartopy.crs import PlateCarree
except ModuleNotFoundError:
    PlateCarree = object
try:
    from matplotlib.tri import Triangulation
except ModuleNotFoundError:
    Triangulation = object
_F = TypeVar('_F', bound=Callable[..., Any])
BASEMAP_FUNCS = ('barbs', 'contour', 'contourf', 'hexbin', 'imshow', 'pcolor', 'pcolormesh', 'plot', 'quiver', 'scatter', 'streamplot', 'step')
CARTOPY_FUNCS = ('barbs', 'contour', 'contourf', 'fill', 'fill_between', 'fill_betweenx', 'imshow', 'pcolor', 'pcolormesh', 'plot', 'quiver', 'scatter', 'streamplot', 'step', 'tricontour', 'tricontourf', 'tripcolor')

def _load_objects() -> None:
    """Load array-like objects."""
    ...

def _is_numeric(data: Incomplete) -> Incomplete:
    """Test whether input is numeric array rather than datetime or strings."""
    ...

def _is_categorical(data: Incomplete) -> Incomplete:
    """Test whether input is array of strings."""
    ...

def _is_descending(data: Incomplete) -> bool:
    """Test whether the input data is descending. This is used for auto axis reversal."""
    ...

def _to_duck_array(data: Incomplete, strip_units: Incomplete=False) -> Incomplete:
    """Convert arbitrary input to duck array. Preserve array containers with metadata."""
    ...

def _to_numpy_array(data: Incomplete, strip_units: Incomplete=False) -> Incomplete:
    """Convert arbitrary input to numpy array. Preserve masked arrays and unit arrays."""
    ...

def _to_masked_array(data: Incomplete, *, copy: Incomplete=False) -> Incomplete:
    """Convert numpy array to masked array with consideration for datetimes and quantities."""
    ...

def _to_edges(x: Incomplete, y: Incomplete, z: Incomplete) -> Incomplete:
    """Enforce that coordinates are edges. Convert from centers if possible."""
    ...

def _to_centers(x: Incomplete, y: Incomplete, z: Incomplete) -> Incomplete:
    """Enforce that coordinates are centers. Convert from edges if possible."""
    ...

def _from_data(data: Incomplete, *args: Incomplete) -> Incomplete:
    """Try to convert positional `key` arguments to `data[key]`. If argument is string
it could be a valid positional argument like `fmt` so do not raise error."""
    ...

def _parse_triangulation_inputs(*args: Incomplete, **kwargs: Incomplete) -> tuple[Triangulation, Any, tuple[Any, ...], dict[str, Any]]:
    """Parse inputs using Matplotlib's `get_from_args_and_kwargs` method.
Returns a Triangulation object, z values, and updated args/kwargs."""
    ...

def _parse_triangulation_with_preprocess(*keys: Incomplete, keywords: Incomplete=None, allow_extra: Incomplete=True) -> Callable[[_F], _F]:
    """Combines _parse_triangulation with _preprocess_or_redirect for backwards compatibility."""
    ...

def _preprocess_or_redirect(*keys: Incomplete, keywords: Incomplete=None, allow_extra: Incomplete=True, cartopy_default_transform: Incomplete=True) -> Callable[[_F], _F]:
    """Redirect internal plotting calls to native matplotlib methods. Also convert
keyword args to positional and pass arguments through 'data' dictionary."""
    ...

def _dist_finite(distribution: Incomplete, weights: Incomplete=None) -> Incomplete:
    """Return the finite subset of the distribution together with the matching
subset of the weights. Used to sanitize input for `_dist_kde`."""
    ...

def _dist_kde(distribution: Incomplete, *, coords: Incomplete=None, points: Incomplete=None, margin: Incomplete=0.0, bw_method: Incomplete=None, weights: Incomplete=None) -> Incomplete:
    """Return the coordinates and gaussian kernel density estimate of the input
distribution. This is the single entry point for the kernel density
estimates drawn by `~ultraplot.axes.PlotAxes.hist` and
`~ultraplot.axes.PlotAxes.ridgeline`.

Parameters
----------
distribution : array-like
    The sample. Flattened to 1D and stripped of non-finite values.
coords : array-like, optional
    The coordinates to evaluate the estimate on. If ``None`` an evenly
    spaced grid is built from the data range (see `points` and `margin`).
points : int, default: :rc:`kde.points`
    The number of evenly spaced evaluation coordinates. Larger values give
    smoother curves at the cost of speed. Ignored if `coords` was passed.
margin : float, default: 0
    The fraction of the data range used to pad either side of the
    evaluation grid. Ignored if `coords` was passed.
bw_method : str, float, or callable, optional
    The bandwidth selector passed to `scipy.stats.gaussian_kde`. Can be
    ``'scott'``, ``'silverman'``, a scalar, or a callable.
weights : array-like, optional
    The per-sample weights passed to `scipy.stats.gaussian_kde`.

Returns
-------
coords : ndarray
    The evaluation coordinates.
density : ndarray
    The probability density evaluated on `coords`. Integrates to ``1``."""
    ...

def _dist_clean(distribution: Incomplete) -> Incomplete:
    """Clean the distribution data for processing by `boxplot` or `violinplot`.
Handles np.ndarrays where the ndarray is a list of lists of variable sizes."""
    ...

def _dist_reduce(data: Incomplete, *, mean: Incomplete=None, means: Incomplete=None, median: Incomplete=None, medians: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
    """Reduce statistical distributions to means and medians. Tack on a
distribution keyword argument for processing down the line."""
    ...

def _dist_range(data: Incomplete, distribution: Incomplete, *, errdata: Incomplete=None, absolute: Incomplete=False, label: Incomplete=False, stds: Incomplete=None, pctiles: Incomplete=None, stds_default: Incomplete=None, pctiles_default: Incomplete=None) -> Incomplete:
    """Return a plottable characteristic range for the statistical distribution
relative to the input coordinate (generally a mean or median)."""
    ...

def _safe_mask(mask: Incomplete, *args: Incomplete) -> Incomplete:
    """Safely apply the mask to the input arrays, accounting for existing masked
or invalid values. Values matching ``False`` are set to `np.nan`."""
    ...

def _safe_range(data: Incomplete, lo: Incomplete=0, hi: Incomplete=100) -> Incomplete:
    """Safely return the minimum and maximum (default) or percentile range accounting
for masked values. Use min and max functions when possible for speed. Return
``None`` if we fail to get a valid range."""
    ...

def _meta_coords(*args: Incomplete, which: Incomplete='x', **kwargs: Incomplete) -> Incomplete:
    """Return the index arrays associated with string coordinates and
keyword arguments updated with index locators and formatters."""
    ...

def _meta_labels(data: Incomplete, axis: Incomplete=0, always: Incomplete=True) -> Incomplete:
    """Return the array-like "labels" along axis `axis`. If `always` is ``False``
we return ``None`` for simple ndarray input."""
    ...

def _meta_title(data: Incomplete, include_units: Incomplete=True) -> str | None:
    """Return the "title" of an array-like object with metadata.
Include units in the title if `include_units` is ``True``."""
    ...

def _meta_units(data: Incomplete) -> Incomplete:
    """Get the unit string from the `xarray.DataArray` attributes or the
`pint.Quantity`. Format the latter with :rcraw:`unitformat`."""
    ...

def _geo_basemap_1d(x: Incomplete, *ys: Incomplete, xmin: Incomplete=-180, xmax: Incomplete=180) -> Incomplete:
    """Fix basemap geographic 1D data arrays."""
    ...

def _geo_basemap_2d(x: Incomplete, y: Incomplete, *zs: Incomplete, xmin: Incomplete=-180, xmax: Incomplete=180, globe: Incomplete=False) -> Incomplete:
    """Fix basemap geographic 2D data arrays."""
    ...

def _geo_cartopy_1d(x: Incomplete, *ys: Incomplete) -> Incomplete:
    """Fix cartopy geographic 1D data arrays."""
    ...

def _geo_cartopy_2d(x: Incomplete, y: Incomplete, *zs: Incomplete, globe: Incomplete=False) -> Incomplete:
    """Fix cartopy geographic 2D data arrays."""
    ...

def _geo_clip(*ys: Incomplete) -> Incomplete:
    """Ensure latitudes fall within ``-90`` to ``90``. Important if we
add graticule edges with `edges`."""
    ...

def _geo_inbounds(x: Incomplete, y: Incomplete, xmin: Incomplete=-180, xmax: Incomplete=180) -> Incomplete:
    """Fix conflicts with map coordinates by rolling the data to fall between the
minimum and maximum longitudes and masking out-of-bounds data points."""
    ...

def _geo_globe(x: Incomplete, y: Incomplete, z: Incomplete, xmin: Incomplete=-180, modulo: Incomplete=False) -> Incomplete:
    """Ensure global coverage by fixing gaps over poles and across
longitude seams. Increases the size of the arrays."""
    ...
