"""Generate bundled type stubs with statically expanded docstrings."""

from __future__ import annotations

import argparse
import ast
import builtins
import copy
import os
import re
import shutil
import subprocess
import sys
import tempfile
import warnings
from collections import defaultdict, deque
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "ultraplot"
HEADER = "# @generated by tools/generate_stubs.py; do not edit\n# fmt: off\n"
VERSION_STUB = "__version__: str\n"
PYREFLY_VERSION = "1.2.0"
EXCLUDED_PARTS = {"tests", "results", "__pycache__"}
STATIC_DECORATORS = {
    "abstractmethod",
    "asynccontextmanager",
    "cached_property",
    "classmethod",
    "contextmanager",
    "dataclass",
    "deprecated",
    "final",
    "getter",
    "overload",
    "override",
    "property",
    "setter",
    "deleter",
    "singledispatch",
    "singledispatchmethod",
    "staticmethod",
}
SNIPPET_PATTERN = re.compile(r"%\(([^)]+)\)s")
BUILTIN_NAMES = set(dir(builtins)) | {"None"}
TRY_NODES = (ast.Try,) + ((ast.TryStar,) if hasattr(ast, "TryStar") else ())


def _dotted_name(node: ast.expr) -> str | None:
    """Return the dotted name represented by an expression."""
    if isinstance(node, ast.Call):
        node = node.func
    names = []
    while isinstance(node, ast.Attribute):
        names.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        names.append(node.id)
        return ".".join(reversed(names))
    return None


def _is_overload(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """Return whether a function is an overload declaration."""
    return any(
        (_dotted_name(item) or "").split(".")[-1] == "overload"
        for item in node.decorator_list
    )


def _has_decorator(
    node: ast.FunctionDef | ast.AsyncFunctionDef, name: str
) -> bool:
    """Return whether a function has a decorator with the given final name."""
    return any(
        (_dotted_name(item) or "").split(".")[-1] == name
        for item in node.decorator_list
    )


def _is_simple_target(node: ast.expr) -> bool:
    """Return whether an assignment target is declarative stub syntax."""
    if isinstance(node, ast.Name):
        return True
    if isinstance(node, (ast.List, ast.Tuple)):
        return all(_is_simple_target(item) for item in node.elts)
    return False


def _target_names(node: ast.expr) -> list[str]:
    """Return names contained in a simple assignment target."""
    if isinstance(node, ast.Name):
        return [node.id]
    if isinstance(node, (ast.List, ast.Tuple)):
        return [name for item in node.elts for name in _target_names(item)]
    return []


def _is_unstable_expression(node: ast.expr) -> bool:
    """Return whether ``ast.unparse`` changed for this expression by version."""
    unstable = (
        ast.DictComp,
        ast.GeneratorExp,
        ast.JoinedStr,
        ast.Lambda,
        ast.ListComp,
        ast.SetComp,
    )
    return any(isinstance(item, unstable) for item in ast.walk(node))


def _is_type_checking(node: ast.expr) -> bool:
    """Return whether *node* is a ``TYPE_CHECKING`` guard."""
    return (isinstance(node, ast.Name) and node.id == "TYPE_CHECKING") or (
        isinstance(node, ast.Attribute) and node.attr == "TYPE_CHECKING"
    )


def _is_docstring_statement(node: ast.stmt) -> bool:
    """Return whether *node* is a module/class/function docstring statement."""
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
    )


def _scope_statements(statements: list[ast.stmt]):
    """Yield declarations from module/class scopes, including guarded branches."""
    for statement in statements:
        yield statement
        if isinstance(statement, ast.If):
            yield from _scope_statements(statement.body)
            yield from _scope_statements(statement.orelse)
        elif isinstance(statement, TRY_NODES):
            yield from _scope_statements(statement.body)
            yield from _scope_statements(statement.orelse)
            yield from _scope_statements(statement.finalbody)
            for handler in statement.handlers:
                yield from _scope_statements(handler.body)


def _declarations(statements: list[ast.stmt], prefix: tuple[str, ...] = ()):
    """Yield qualified function declarations without descending into functions."""
    for statement in _scope_statements(statements):
        if isinstance(statement, (ast.FunctionDef, ast.AsyncFunctionDef)):
            yield ".".join((*prefix, statement.name)), statement
        elif isinstance(statement, ast.ClassDef):
            yield from _declarations(statement.body, (*prefix, statement.name))


def _parameter_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> tuple[str, ...]:
    """Return a signature key that distinguishes overloads and parameter kinds."""
    arguments = node.args
    return (
        *(f"pos:{arg.arg}" for arg in (*arguments.posonlyargs, *arguments.args)),
        *((f"var:{arguments.vararg.arg}",) if arguments.vararg else ()),
        *(f"kw:{arg.arg}" for arg in arguments.kwonlyargs),
        *((f"vkw:{arguments.kwarg.arg}",) if arguments.kwarg else ()),
    )


def _module_names(tree: ast.Module) -> set[str]:
    """Return names that inferred annotations may safely reference in a stub."""
    names = set(BUILTIN_NAMES)

    def collect(statements: list[ast.stmt]):
        for statement in _scope_statements(statements):
            if isinstance(statement, ast.Import):
                names.update(
                    alias.asname or alias.name.split(".")[0]
                    for alias in statement.names
                )
            elif isinstance(statement, ast.ImportFrom):
                names.update(alias.asname or alias.name for alias in statement.names)
            elif isinstance(
                statement, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
            ):
                names.add(statement.name)
                if isinstance(statement, ast.ClassDef):
                    collect(statement.body)
            elif isinstance(statement, ast.Assign):
                for target in statement.targets:
                    names.update(_target_names(target))
            elif isinstance(statement, ast.AnnAssign):
                names.update(_target_names(statement.target))

    collect(tree.body)
    names.add("Incomplete")
    return names


class _AnnotationNameCollector(ast.NodeVisitor):
    """Collect names, including names hidden inside forward-reference strings."""

    def __init__(self):
        self.names = set()
        self._literal_depth = 0

    def visit_Name(self, node: ast.Name) -> None:
        if isinstance(node.ctx, ast.Load):
            self.names.add(node.id)

    def visit_Constant(self, node: ast.Constant) -> None:
        if not isinstance(node.value, str) or self._literal_depth:
            return
        try:
            expression = ast.parse(node.value, mode="eval")
        except SyntaxError:
            return
        self.names.update(
            item.id
            for item in ast.walk(expression)
            if isinstance(item, ast.Name) and isinstance(item.ctx, ast.Load)
        )

    def visit_Subscript(self, node: ast.Subscript) -> None:
        self.visit(node.value)
        is_literal = (_dotted_name(node.value) or "").split(".")[-1] == "Literal"
        self._literal_depth += is_literal
        self.visit(node.slice)
        self._literal_depth -= is_literal


def _safe_annotation(annotation: ast.expr | None, available: set[str]) -> ast.expr | None:
    """Return a copied inferred annotation only when all root names resolve."""
    if annotation is None:
        return None
    if isinstance(annotation, (ast.Dict, ast.List, ast.Set, ast.Tuple)):
        return None
    collector = _AnnotationNameCollector()
    collector.visit(annotation)
    if collector.names <= available:
        return copy.deepcopy(annotation)
    return None


def _missing_annotation() -> ast.Name:
    """Return the typing-spec placeholder used for an unknown annotation."""
    return ast.Name(id="Incomplete", ctx=ast.Load())


def _merge_annotations(
    tree: ast.Module, inferred: ast.Module | None
) -> tuple[int, int, int, int]:
    """Fill missing source annotations using matching Pyrefly declarations.

    Explicit source annotations always win. If Pyrefly omitted a declaration or
    inferred a name that is not available in the module, ``Incomplete`` is used
    as the honest static placeholder recommended for generated stubs.
    """
    candidates = defaultdict(deque)
    if inferred is not None:
        for qualname, node in _declarations(inferred.body):
            candidates[(qualname, _parameter_names(node))].append(node)

    available = _module_names(tree)
    inferred_count = fallback_count = unmatched_count = discarded_count = 0
    for qualname, node in _declarations(tree.body):
        queue = candidates.get((qualname, _parameter_names(node)))
        inferred_node = queue.popleft() if queue else None
        if inferred_node is None:
            unmatched_count += 1

        source_args = (
            *node.args.posonlyargs,
            *node.args.args,
            *node.args.kwonlyargs,
        )
        # Inferences copied from an overridden third-party method change with
        # the installed dependency version. Keep only explicit source types for
        # overrides so generation remains reproducible across supported envs.
        use_inference = inferred_node is not None and not _has_decorator(
            node, "override"
        )
        inferred_args = ()
        if use_inference:
            inferred_args = (
                *inferred_node.args.posonlyargs,
                *inferred_node.args.args,
                *inferred_node.args.kwonlyargs,
            )
        inferred_by_name = {arg.arg: arg for arg in inferred_args}
        for argument in source_args:
            if argument.arg in {"self", "cls"}:
                continue
            if argument.annotation is not None:
                annotation = _safe_annotation(argument.annotation, available)
                if annotation is not None:
                    continue
                argument.annotation = None
                discarded_count += 1
            annotation = _safe_annotation(
                inferred_by_name.get(argument.arg).annotation
                if argument.arg in inferred_by_name
                else None,
                available,
            )
            argument.annotation = annotation or _missing_annotation()
            inferred_count += annotation is not None
            fallback_count += annotation is None

        for source_arg, inferred_arg in (
            (
                node.args.vararg,
                inferred_node.args.vararg if use_inference else None,
            ),
            (node.args.kwarg, inferred_node.args.kwarg if use_inference else None),
        ):
            if source_arg is None:
                continue
            if source_arg.annotation is not None:
                annotation = _safe_annotation(source_arg.annotation, available)
                if annotation is not None:
                    continue
                source_arg.annotation = None
                discarded_count += 1
            annotation = _safe_annotation(
                inferred_arg.annotation if inferred_arg else None, available
            )
            source_arg.annotation = annotation or _missing_annotation()
            inferred_count += annotation is not None
            fallback_count += annotation is None

        if node.returns is not None and _safe_annotation(node.returns, available) is None:
            node.returns = None
            discarded_count += 1
        if node.returns is None:
            if node.name == "__init__":
                node.returns = ast.Constant(None)
                inferred_count += 1
            else:
                annotation = _safe_annotation(
                    inferred_node.returns if use_inference else None, available
                )
                node.returns = annotation or _missing_annotation()
                inferred_count += annotation is not None
                fallback_count += annotation is None
    return inferred_count, fallback_count, unmatched_count, discarded_count


def _pyrefly_version(executable: str) -> str:
    """Return the installed Pyrefly version or raise an actionable error."""
    result = subprocess.run(
        [executable, "--version"], capture_output=True, text=True, check=True
    )
    match = re.search(r"\b(\d+\.\d+\.\d+)\b", result.stdout + result.stderr)
    if not match:
        raise RuntimeError(f"Could not determine Pyrefly version from: {result.stdout!r}")
    return match.group(1)


def _run_pyrefly(executable: str) -> tuple[dict[Path, ast.Module], list[Path]]:
    """Run Pyrefly on a source-only package and parse its inferred stubs."""
    version = _pyrefly_version(executable)
    if version != PYREFLY_VERSION:
        raise RuntimeError(
            f"Stub generation requires pyrefly=={PYREFLY_VERSION}; found {version}. "
            f"Install with `python -m pip install pyrefly=={PYREFLY_VERSION}`."
        )
    print(f"Running Pyrefly {version} type inference on a source-only package copy...")
    with tempfile.TemporaryDirectory(prefix="ultraplot-stubgen-") as directory:
        temporary = Path(directory)
        source_root = temporary / "source"
        source_package = source_root / PACKAGE.name
        output_root = temporary / "inferred"
        shutil.copytree(
            PACKAGE,
            source_package,
            ignore=shutil.ignore_patterns(
                "*.pyi", "tests", "results", "__pycache__", "*.pyc"
            ),
        )
        command = [
            executable,
            "stubgen",
            str(source_package),
            "--output-dir",
            str(output_root),
            "--include-docstrings",
            "--include-private",
            "--threads",
            "0",
            "--search-path",
            str(source_root),
            "--python-interpreter-path",
            sys.executable,
            "--check-unannotated-defs",
            "true",
            "--infer-return-types",
            "checked",
        ]
        result = subprocess.run(
            command, cwd=ROOT, capture_output=True, text=True, check=False
        )
        if result.returncode:
            details = (result.stdout + "\n" + result.stderr).strip()
            raise RuntimeError(f"Pyrefly stub generation failed:\n{details}")

        trees = {}
        invalid = []
        for source_path in _source_files():
            relative = source_path.relative_to(PACKAGE).with_suffix(".pyi")
            inferred_path = output_root / relative
            if not inferred_path.exists():
                continue
            try:
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore", SyntaxWarning)
                    trees[source_path] = ast.parse(
                        inferred_path.read_text(), filename=str(inferred_path)
                    )
            except SyntaxError:
                # Pyrefly 1.2.0 currently emits invalid ``((x: T) -> U)`` syntax
                # for one callable assignment in rcsetup.py. The structural base
                # and Incomplete fallbacks keep that module valid and complete.
                invalid.append(relative)
        return trees, invalid


class _StubTransformer(ast.NodeTransformer):
    """Reduce implementation syntax to declarations suitable for ``.pyi`` files."""

    def __init__(self, expand_docstring):
        self._expand_docstring = expand_docstring

    def _decorators(self, nodes: list[ast.expr]) -> list[ast.expr]:
        kept = []
        for node in nodes:
            name = (_dotted_name(node) or "").split(".")[-1]
            if name in STATIC_DECORATORS:
                kept.append(node)
        return kept

    def _doc_body(self, node: ast.AST) -> list[ast.stmt]:
        doc = ast.get_docstring(node, clean=True)
        body = []
        if doc:
            body.append(ast.Expr(value=ast.Constant(self._expand_docstring(doc))))
        body.append(ast.Expr(value=ast.Constant(Ellipsis)))
        return body

    def _scope_body(self, statements: list[ast.stmt]) -> list[ast.stmt]:
        overloaded = {
            item.name
            for item in statements
            if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
            and _is_overload(item)
        }
        body = []
        for statement in statements:
            if (
                isinstance(statement, (ast.FunctionDef, ast.AsyncFunctionDef))
                and statement.name in overloaded
                and not _is_overload(statement)
            ):
                continue
            transformed = self.visit(statement)
            if transformed is None:
                continue
            if isinstance(transformed, list):
                body.extend(transformed)
            else:
                body.append(transformed)
        return body

    def visit_Module(self, node: ast.Module) -> ast.Module:
        node.body = self._scope_body(node.body)
        insertion = int(bool(node.body) and _is_docstring_statement(node.body[0]))
        node.body.insert(
            insertion,
            ast.ImportFrom(
                module="_typeshed",
                names=[ast.alias(name="Incomplete")],
                level=0,
            ),
        )
        return node

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        node.decorator_list = self._decorators(node.decorator_list)
        node.body = self._scope_body(node.body)
        if not node.body:
            node.body = [ast.Expr(value=ast.Constant(Ellipsis))]
        return node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef:
        node.decorator_list = self._decorators(node.decorator_list)
        node.body = self._doc_body(node)
        return node

    def visit_AsyncFunctionDef(
        self, node: ast.AsyncFunctionDef
    ) -> ast.AsyncFunctionDef:
        node.decorator_list = self._decorators(node.decorator_list)
        node.body = self._doc_body(node)
        return node

    def visit_Expr(self, node: ast.Expr) -> ast.Expr | None:
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            value = self._expand_docstring(node.value.value)
            return ast.Expr(value=ast.Constant(value))
        return None

    def visit_Assign(self, node: ast.Assign) -> ast.Assign | None:
        if all(_is_simple_target(target) for target in node.targets):
            names = [name for target in node.targets for name in _target_names(target)]
            if (
                names and all(name.endswith("_docstring") for name in names)
            ) or _is_unstable_expression(node.value):
                # Comprehension parentheses, lambda spacing, and f-string quote
                # selection changed across supported Python versions. These
                # implementation values are irrelevant to static declarations.
                node.value = ast.Constant(Ellipsis)
            return node
        return None

    def visit_AnnAssign(self, node: ast.AnnAssign) -> ast.AnnAssign | None:
        if _is_simple_target(node.target):
            if node.value is not None and _is_unstable_expression(node.value):
                node.value = ast.Constant(Ellipsis)
            return node
        return None

    def visit_AugAssign(self, node: ast.AugAssign) -> None:
        return None

    def visit_If(self, node: ast.If) -> ast.If | list[ast.stmt] | None:
        if _is_type_checking(node.test):
            return self._scope_body(node.body)
        node.body = self._scope_body(node.body)
        node.orelse = self._scope_body(node.orelse)
        if not node.body:
            return node.orelse or None
        return node

    def visit_Try(self, node: ast.Try) -> ast.Try | list[ast.stmt] | None:
        node.body = self._scope_body(node.body)
        node.orelse = self._scope_body(node.orelse)
        node.finalbody = self._scope_body(node.finalbody)
        for handler in node.handlers:
            handler.body = self._scope_body(handler.body)
        if not node.body:
            return [item for handler in node.handlers for item in handler.body] or None
        return node

    def visit_For(self, node: ast.For) -> None:
        return None

    def visit_AsyncFor(self, node: ast.AsyncFor) -> None:
        return None

    def visit_While(self, node: ast.While) -> None:
        return None

    def visit_With(self, node: ast.With) -> None:
        return None

    def visit_AsyncWith(self, node: ast.AsyncWith) -> None:
        return None

    def visit_Match(self, node: ast.Match) -> None:
        return None

    def visit_ImportFrom(self, node: ast.ImportFrom) -> ast.ImportFrom | None:
        # Future annotations are unnecessary in stubs, and both Pylance and
        # Pyrefly require future imports to precede generated module docstrings.
        if node.module == "__future__":
            return None
        return node


def _source_files() -> Iterable[Path]:
    """Yield Python implementation files included in the distributed package."""
    for path in sorted(PACKAGE.rglob("*.py")):
        if not EXCLUDED_PARTS.intersection(path.parts):
            yield path


def _snippet_expander():
    """Return a function that expands all registered UltraPlot snippets."""
    os.environ.setdefault("MPLCONFIGDIR", "/tmp/ultraplot-matplotlib")
    sys.path.insert(0, str(ROOT))
    from ultraplot.internals.docstring import _snippet_manager

    def expand(doc: str) -> str:
        def replace(match: re.Match) -> str:
            key = match.group(1)
            try:
                return str(_snippet_manager[key])
            except KeyError:
                # Some internal helper docstrings explain the placeholder syntax.
                return match.group(0)

        previous = None
        while previous != doc:
            previous = doc
            doc = SNIPPET_PATTERN.sub(replace, doc)
        return doc

    return expand


def _render(
    source_path: Path, expand_docstring, inferred: ast.Module | None
) -> tuple[str, tuple[int, int, int, int]]:
    """Render one implementation module as a deterministic type stub."""
    if source_path == PACKAGE / "_version.py":
        # setuptools-scm rewrites this module while building each commit. Its
        # public interface is stable even though the assigned value is not.
        return HEADER + VERSION_STUB, (0, 0, 0, 0)
    source = source_path.read_text()
    tree = ast.parse(source, filename=str(source_path))
    annotation_counts = _merge_annotations(tree, inferred)
    tree = _StubTransformer(expand_docstring).visit(copy.deepcopy(tree))
    ast.fix_missing_locations(tree)
    rendered = ast.unparse(tree).rstrip() + "\n"
    return HEADER + rendered, annotation_counts


def _stub_path(source_path: Path) -> Path:
    return source_path.with_suffix(".pyi")


def _is_generated_stub(path: Path) -> bool:
    try:
        return path.read_text().startswith(HEADER.splitlines()[0])
    except OSError:
        return False


def main(argv: list[str] | None = None) -> int:
    """Generate bundled stubs, or report stale output with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--pyrefly",
        help="Pyrefly executable (default: resolve `pyrefly` from PATH)",
    )
    args = parser.parse_args(argv)

    executable = args.pyrefly or shutil.which("pyrefly")
    if not executable:
        parser.error(
            f"pyrefly=={PYREFLY_VERSION} is required; install the `typing` extra "
            "or pass --pyrefly PATH"
        )
    try:
        inferred_trees, invalid_inference = _run_pyrefly(executable)
    except (OSError, subprocess.SubprocessError, RuntimeError) as error:
        parser.error(str(error))

    expand_docstring = _snippet_expander()
    source_files = list(_source_files())
    expected = set()
    changed = []
    inferred_count = fallback_count = unmatched_count = discarded_count = 0
    if args.check:
        print(f"Checking {len(source_files)} source modules and their stubs...")
    for source_path in source_files:
        stub_path = _stub_path(source_path)
        expected.add(stub_path)
        rendered, counts = _render(
            source_path, expand_docstring, inferred_trees.get(source_path)
        )
        inferred_count += counts[0]
        fallback_count += counts[1]
        unmatched_count += counts[2]
        discarded_count += counts[3]
        current = stub_path.read_text() if stub_path.exists() else None
        if current == rendered:
            continue
        changed.append(stub_path)
        if not args.check:
            stub_path.write_text(rendered)

    obsolete = [
        path
        for path in PACKAGE.rglob("*.pyi")
        if path not in expected and _is_generated_stub(path)
    ]
    if not args.check:
        for path in obsolete:
            path.unlink()

    for path in changed:
        action = "Stale" if args.check else "Generated"
        print(f"{action}: {path.relative_to(ROOT)}")
    for path in obsolete:
        action = "Obsolete" if args.check else "Removed"
        print(f"{action}: {path.relative_to(ROOT)}")
    print(
        f"Annotation merge: {inferred_count} inferred, "
        f"{fallback_count} marked Incomplete; "
        f"{discarded_count} invalid source annotations replaced; "
        f"{unmatched_count} source declarations absent from Pyrefly output."
    )
    if invalid_inference:
        print(
            "Pyrefly output skipped after syntax validation: "
            + ", ".join(str(path) for path in invalid_inference)
        )
    if args.check:
        if changed or obsolete:
            count = len(changed) + len(obsolete)
            print(
                f"Check failed: {count} stale or obsolete stub(s). "
                "Run `python tools/generate_stubs.py` to update them."
            )
        else:
            print(f"Checked {len(expected)} stubs: all up to date.")
    else:
        unchanged = len(expected) - len(changed)
        print(
            f"Stub generation complete: {len(changed)} updated, "
            f"{unchanged} unchanged, {len(obsolete)} obsolete removed."
        )
    return int(args.check and bool(changed or obsolete))


if __name__ == "__main__":
    raise SystemExit(main())
