#!/usr/bin/env python3
"""
Generate the visual plot-type index for the documentation.

Reuses the icon registry the cheatsheet is built from, so the docs page, the
cheatsheet and the poster all show the same thumbnails and cannot drift apart.
Writes ``docs/plot_types.rst`` and copies the icons to ``docs/_static``.

    micromamba run -n ultraplot-dev python tools/cheatsheet/docs_index.py

Every command links to its API entry, and the link targets are checked against
the live class before the page is written: a typo fails here rather than
becoming a broken reference in the built docs.
"""

from __future__ import annotations

import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PARTS = os.path.join(HERE, "parts")
ROOT = os.path.dirname(os.path.dirname(HERE))
DOCS = os.path.join(ROOT, "docs")
STATIC = os.path.join(DOCS, "_static", "plot_types")

sys.path.insert(0, PARTS)

from icons import ICONS, slug  # noqa: E402

#: Gallery examples live here; an example that calls a command is a better
#: destination than the API page alone, so the card links to both.
EXAMPLES = os.path.join(DOCS, "examples", "plot_types")

#: Commands whose icon does not name a method of its own.
METHOD_OVERRIDES = {
    "errorbars": "plot",
    "taylor": None,  # a projection, not a command
    "proj='robin'": None,
    "proj='ortho'": None,
    "coast, land, ocean": None,  # format keywords
    "scatter on a map": "scatter",
    "quiver on a map": "quiver",
    "plot on a map": "plot",
}

#: Headings for the groups, in page order.
GROUPS = (
    ("relational", "Relational", "How one variable relates to another."),
    ("distribution", "Distributions", "The shape and spread of a sample."),
    ("field", "Fields", "A value over a two-dimensional grid."),
    ("vector", "Vector fields", "Direction and magnitude on a grid."),
    ("network", "Networks and diagrams", "Relationships that are not a grid."),
    (
        "maps",
        "Maps",
        "A projection by name, with any plotting command drawn on top in lon/lat.",
    ),
    (
        "keyword",
        "What one keyword does",
        "The same command, changed by a single argument.",
    ),
    (
        "swapped",
        "Swapped axes",
        "Every command has a sibling that puts the categories on the other axis.",
    ),
)

HEADER = """.. _plot_types:

==========
Plot types
==========

Every thumbnail below is the output of the command it names, drawn by that
command. Click one to read its documentation.

.. note::

   This page is generated by ``tools/cheatsheet/docs_index.py`` from the same
   registry the `cheatsheet <https://github.com/Ultraplot/UltraPlot>`__ is built
   from. Re-run it after adding a plotting command.

.. raw:: html

   <style>
   /* Card labels are code literals with no break opportunities; let them wrap
      inside the card instead of running past its edge on a narrow viewport. */
   .sd-card-body p code,
   .sd-card-body p a code {
     overflow-wrap: anywhere;
     word-break: break-word;
     font-size: 0.82em;
   }
   .sd-card-body p { margin-bottom: 0.25rem; }
   </style>

"""


def gallery_links():
    """
    Map a command to the gallery example that demonstrates it.

    Two signals, both deliberate on the example's part: a docstring that names
    ``PlotAxes.<command>``, or a file name that contains the command. Merely
    calling a command is not enough — nearly every example calls ``plot`` — so
    a missing link is preferred over a misleading one.
    """
    import re

    links = {}
    if not os.path.isdir(EXAMPLES):
        return links

    commands = {name: method_for(name) for name in ICONS}
    for entry in sorted(os.listdir(EXAMPLES)):
        if not entry.endswith(".py"):
            continue
        stem = entry[:-3]
        source = open(os.path.join(EXAMPLES, entry)).read()
        declared = set(re.findall(r"PlotAxes\.([a-z_]+)", source))
        for name, command in commands.items():
            if not command or name in links:
                continue
            named = command in declared
            in_filename = len(command) > 4 and command in stem
            if (named or in_filename) and f".{command}(" in source:
                links[name] = f"/gallery/plot_types/{stem}"
    return links


def method_for(name):
    """
    Return the PlotAxes method an icon should link to, or None.
    """
    if name in METHOD_OVERRIDES:
        return METHOD_OVERRIDES[name]
    return name.split("(")[0].strip()


def check_targets(names):
    """
    Verify every link target exists, so the page cannot ship broken references.
    """
    from ultraplot.axes.plot import PlotAxes

    missing = [name for name in names if name and not hasattr(PlotAxes, name)]
    if missing:
        raise SystemExit(
            "these link targets are not PlotAxes methods: " + ", ".join(missing)
        )


def ensure_icons():
    """
    Render the icons if they are missing, so a clean checkout can build.

    The docs build calls this; rendering is skipped when the assets are already
    present and complete, which is the usual case for a local rebuild.
    """
    source = os.path.join(HERE, "assets", "icons")
    have = len([f for f in os.listdir(source)]) if os.path.isdir(source) else 0
    if have >= len(ICONS):
        return
    print(f"  rendering {len(ICONS)} icons (found {have})")
    import icons as icons_module

    cwd = os.getcwd()
    os.chdir(PARTS)
    try:
        icons_module.main()
    finally:
        os.chdir(cwd)


def copy_icons():
    """
    Copy the rendered icons into the documentation's static folder.
    """
    source = os.path.join(HERE, "assets", "icons")
    if not os.path.isdir(source):
        raise SystemExit("no icons yet — run parts/icons.py first")
    os.makedirs(STATIC, exist_ok=True)
    wanted = {slug(name) + ".png" for name in ICONS}
    count = 0
    for entry in sorted(os.listdir(source)):
        if entry.endswith(".png"):
            shutil.copy2(os.path.join(source, entry), os.path.join(STATIC, entry))
            count += 1
    # Renaming or dropping a command would otherwise leave its icon behind, and
    # the docs would ship files nothing references.
    stale = [
        entry
        for entry in os.listdir(STATIC)
        if entry.endswith(".png") and entry not in wanted
    ]
    for entry in stale:
        os.remove(os.path.join(STATIC, entry))
    note = f", {len(stale)} stale removed" if stale else ""
    print(f"  docs/_static/plot_types/ ({count} icons{note})")


def write_page():
    """
    Write the reStructuredText page: one card grid per group.
    """
    examples = gallery_links()
    lines = [HEADER]
    for group, heading, blurb in GROUPS:
        entries = [(name, spec) for name, spec in ICONS.items() if spec[4] == group]
        if not entries:
            continue
        lines.append(heading)
        lines.append("=" * len(heading))
        lines.append("")
        lines.append(blurb)
        lines.append("")
        lines.append(".. grid:: 2 3 4 6")
        lines.append("   :gutter: 2")
        lines.append("")
        for name, spec in entries:
            method = method_for(name)
            label = (
                f":meth:`~ultraplot.axes.PlotAxes.{method}`"
                if method
                else "``proj='taylor'``"
            )
            plain = "(" in name or method is None or method != name.strip()
            # A keyword variant is captioned with its argument alone: the method
            # link underneath already says which command it belongs to, and the
            # whole call is too long to fit a card without overflowing it.
            shown = name.strip()
            if "(" in shown and shown.endswith(")"):
                shown = shown[shown.index("(") + 1 : -1]
            caption = f"``{shown}``" if plain else label
            lines.append("   .. grid-item-card::")
            lines.append(f"      :img-top: _static/plot_types/{slug(name)}.png")
            lines.append("      :text-align: center")
            lines.append("")
            lines.append(f"      {caption}")
            if plain and method:
                lines.append("")
                lines.append(f"      {label}")
            if name in examples:
                lines.append("")
                lines.append(f"      :doc:`example <{examples[name]}>`")
            lines.append("")
        lines.append("")

    path = os.path.join(DOCS, "plot_types.rst")
    with open(path, "w") as handle:
        handle.write("\n".join(lines).rstrip() + "\n")
    print(f"  docs/plot_types.rst ({sum(1 for _ in ICONS)} entries)")


def main():
    check_targets({method_for(name) for name in ICONS})
    ensure_icons()
    copy_icons()
    write_page()


if __name__ == "__main__":
    main()
