# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
The various axes classes used throughout ultraplot.
"""
from _typeshed import Incomplete
import matplotlib.projections as mproj
from ..internals import context
from .base import Axes
from .cartesian import CartesianAxes
from .container import ExternalAxesContainer
from .geo import GeoAxes, _BasemapAxes, _CartopyAxes
from .plot import PlotAxes
from .polar import PolarAxes
from .shared import _SharedAxes
from .taylor import TaylorAxes
from .three import ThreeAxes
__all__ = ['Axes', 'PlotAxes', 'CartesianAxes', 'PolarAxes', 'TaylorAxes', 'GeoAxes', 'ThreeAxes', 'ExternalAxesContainer']
_cls_dict = {}
_cls_table = ...
