# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Axes filled with cartographic projections.
"""
from _typeshed import Incomplete
import copy
import inspect
from dataclasses import dataclass
from functools import partial
from numbers import Real
from types import SimpleNamespace
try:
    from typing import override
except ImportError:
    from typing_extensions import override
from collections.abc import Iterator, Mapping, MutableMapping, Sequence
from typing import Any, Optional, Protocol
import matplotlib.axis as maxis
import matplotlib.axes as maxes
import matplotlib.collections as mcollections
import matplotlib.patches as mpatches
import matplotlib.path as mpath
import matplotlib.text as mtext
import matplotlib.ticker as mticker
import matplotlib.transforms as mtransforms
import numpy as np
from .. import constructor
from .. import proj as pproj
from .. import ticker as pticker
from ..config import rc
from ..internals import _not_none, _pop_params, _pop_props, _pop_rc, _version_cartopy, docstring, ic, labels, warnings
from ..utils import units
from . import plot, shared
try:
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature
    import cartopy.mpl.gridliner as cgridliner
    from cartopy.crs import Projection
    from cartopy.mpl.geoaxes import GeoAxes as _GeoAxes
except ModuleNotFoundError:
    ccrs = cfeature = cgridliner = None
    _GeoAxes = Projection = object
try:
    from mpl_toolkits.basemap import Basemap
except ModuleNotFoundError:
    Basemap = object
__all__ = ['GeoAxes']
GridlineDict = MutableMapping[float, tuple[list[Any], list[mtext.Text]]]
_GRIDLINER_PAD_SCALE = 2.0
_MINOR_TICK_SCALE = 0.6
_BASEMAP_LABEL_SIZE_SCALE = 0.5
_BASEMAP_LABEL_Y_SCALE = 0.65
_BASEMAP_LABEL_X_SCALE = 0.25
_CARTOPY_LABEL_SIDES = ('labelleft', 'labelright', 'labelbottom', 'labeltop', 'geo')
_BASEMAP_LABEL_SIDES = ('labelleft', 'labelright', 'labelbottom', 'labeltop', 'geo')
_HAWKEYE_ANCHORS = {'ul': (0, 1), 'upper left': (0, 1), 'ur': (1, 1), 'upper right': (1, 1), 'll': (0, 0), 'lower left': (0, 0), 'lr': (1, 0), 'lower right': (1, 0), 'c': (0.5, 0.5), 'center': (0.5, 0.5), 'uc': (0.5, 1), 'upper center': (0.5, 1), 'lc': (0.5, 0), 'lower center': (0.5, 0), 'cl': (0, 0.5), 'center left': (0, 0.5), 'cr': (1, 0.5), 'center right': (1, 0.5)}

class _AnchoredInsetLocator:
    """Locate an inset by anchoring one of its points to a parent coordinate."""

    def __init__(self, parent: Incomplete, xy: Incomplete, size: Incomplete, transform: Incomplete, anchor: Incomplete, square: Incomplete=False) -> None:
        ...

    def __call__(self, ax: Incomplete, renderer: Incomplete) -> Incomplete:
        ...
_HAWKEYE_TRANSFORM_NAMES = frozenset({'axes', 'data', 'figure', 'subfigure', 'map'})

def _parse_hawkeye_anchor(anchor: Incomplete, axes_relative: Incomplete=True) -> Incomplete:
    """Translate a named hawkeye anchor to normalized axes coordinates.

String anchors are always axes-relative. When ``axes_relative`` is False the
caller supplied a non-default ``anchor_transform``, so a coordinate 2-tuple
is required and string aliases are rejected."""
    ...

def _parse_hawkeye_size(size: Incomplete) -> Incomplete:
    """Normalize scalar hawkeye sizes to square inset dimensions."""
    ...

def _hawkeye_crs_from_name(name: Incomplete) -> Incomplete:
    """Resolve a projection name to a cartopy CRS for hawkeye coordinates."""
    ...

def _hawkeye_crs(transform: Incomplete, param: Incomplete) -> Incomplete:
    """Resolve a hawkeye geographic transform to a cartopy CRS.

Accepts ``'map'`` (an alias for `~cartopy.crs.PlateCarree`), a cartopy CRS
instance, or a registered projection name (e.g. ``'cyl'``, ``'moll'``)."""
    ...

def _parse_hawkeye_extent_transform(transform: Incomplete) -> Incomplete:
    """Translate hawkeye extent transforms to cartopy coordinate systems."""
    ...

def _parse_hawkeye_anchor_transform(transform: Incomplete) -> Incomplete:
    """Resolve the coordinate system for a hawkeye anchor point.

``'axes'`` (the default) leaves the anchor as an inset axes fraction and is
signalled by returning ``None``. Any other value is resolved to a cartopy CRS
so the anchor can be interpreted as a geographic or projected point."""
    ...

def _hawkeye_anchor_fraction(inset: Incomplete, anchor: Incomplete, anchor_transform: Incomplete) -> Incomplete:
    """Convert a hawkeye anchor point to an inset axes fraction.

With ``anchor_transform`` None the anchor is already an axes fraction and is
returned unchanged. Otherwise the anchor is a point in ``anchor_transform``
coordinates; it is projected into the inset projection and normalized against
the inset view limits, which are fixed by the time this runs."""
    ...

def _parse_hawkeye_connector(connector: Incomplete) -> Incomplete:
    """Normalize connector shorthand to a named presentation mode."""
    ...

def _parse_hawkeye_shape(value: Incomplete, name: Incomplete) -> Incomplete:
    """Validate a hawkeye inset or target shape."""
    ...

def _square_hawkeye_view(inset: Incomplete) -> Incomplete:
    """Expand the shorter projected dimension to make a square map viewport."""
    ...

def _infer_hawkeye_relation(parent_extent: Incomplete, inset_extent: Incomplete) -> Incomplete:
    """Infer whether an inset is a geographic detail or overview."""
    ...

def _segments_intersect(start1: Incomplete, end1: Incomplete, start2: Incomplete, end2: Incomplete) -> Incomplete:
    """Return whether two display-coordinate line segments intersect."""
    ...

def _select_hawkeye_connector_pairs(extent_display: Incomplete, frame_display: Incomplete) -> Incomplete:
    """Select the shortest pair of non-crossing overview connectors."""
    ...

def _add_hawkeye_overview_connectors(parent: Incomplete, inset: Incomplete, extent: Incomplete, transform: Incomplete, **kwargs: Incomplete) -> Incomplete:
    """Connect the parent frame to its geographic extent on an overview inset."""
    ...

def _add_hawkeye_leader(inset: Incomplete, target_axes: Incomplete, target_xy: Incomplete, transform: Incomplete, target_patch: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
    """Draw a leader from an inset edge to a geographic target point."""
    ...

def _add_hawkeye_zoom_indicator(parent: 'GeoAxes', inset: 'GeoAxes', **kwargs: Any) -> Incomplete:
    """Draw an ``indicate_inset_zoom`` marker with a version-stable return.

matplotlib >= 3.10 returns an ``InsetIndicator`` artist exposing
``.rectangle`` and ``.connectors``. Earlier versions return a plain
``(rectangle, connectors)`` tuple, so wrap it to expose the same accessors."""
    ...

def _select_enveloping_connectors(indicator: Incomplete, inset: 'GeoAxes', renderer: Incomplete=None) -> None:
    """Show the two zoom connectors that wrap around the inset (outer tangents).

The visible pair is chosen from the sign of the inset-to-indicator centre
offset: a diagonally opposite pair envelops the inset, whereas a same-side
pair would run parallel and cross the frustum."""
    ...

def _envelop_hawkeye_zoom_connectors(indicator: Incomplete, inset: 'GeoAxes') -> None:
    """Reassert the enveloping connector pair on every draw.

matplotlib fixes connector visibility once, from a bounding-box rule that can
pick a parallel pair for a diagonally placed inset. The inset position is only
final at draw time, so recompute the enveloping pair from a draw hook: on
matplotlib >= 3.10 the ``InsetIndicator`` resolves its connectors in its own
``draw``, while the legacy wrapper draws its rectangle before the connectors."""
    ...

@dataclass
class _HawkeyeSpec:
    """Validated inputs for `GeoAxes.hawkeye`.

``extent_transform`` and ``relation`` are only fully resolved when ``extent``
is not ``None`` (they require a geographic extent to normalize and infer);
otherwise they retain their raw defaults and are never consumed. ``aspect`` is
intentionally not stored here because ``'projection'`` can only be resolved
from the live inset axes (see `GeoAxes._build_hawkeye_inset`). When
``anchor_transform`` is not ``None`` the ``anchor`` is a geographic/projected
point rather than an axes fraction; it is converted to a fraction against the
live inset view limits in `GeoAxes._build_hawkeye_inset`."""
    xy: tuple[float, float]
    size: tuple[float, float]
    anchor: tuple[float, float]
    anchor_transform: Any
    transform: Any
    extent: Optional[tuple[float, float, float, float]]
    extent_transform: Any
    relation: str
    connector: Optional[str]
    shape: str
    target: str

def _apply_hawkeye_circle_boundary(inset: 'GeoAxes', aspect: str | float) -> None:
    """Clip a hawkeye inset to a circular map boundary matching its view."""
    ...

def _make_hawkeye_indicator_patch(extent: Sequence[float], transform: Any, target: str, **kwargs: Any) -> mpatches.Patch:
    """Build the outline patch (box or circle) marking a hawkeye extent."""
    ...
_format_docstring = ...
_hawkeye_docstring = ...
_choropleth_docstring = ...

class _GeoLabel(object):
    """Optionally omit overlapping check if an rc setting is disabled."""

    def check_overlapping(self, *args: Any, **kwargs: Any) -> bool:
        ...
if cgridliner is not None and hasattr(cgridliner, 'Label'):

    class _CartopyLabel(_GeoLabel, cgridliner.Label):
        """Label class with configurable overlap checks."""

    class _CartopyGridliner(cgridliner.Gridliner):
        """Gridliner subclass to localize cartopy quirks in one place."""
        LabelClass = _CartopyLabel

        def _generate_labels(self) -> Iterator[_CartopyLabel]:
            """Yield label objects, reusing cached instances when possible."""
            ...

        def _axes_domain(self, *args: Any, **kwargs: Any) -> tuple[Any, Any]:
            ...

        def _draw_gridliner(self, *args: Any, **kwargs: Any) -> Any:
            ...
else:
    _CartopyGridliner = None

class _GeoAxis(object):
    """Dummy axis used by longitude and latitude locators and for storing view limits on
longitude and latitude coordinates. Modeled after how [matplotlib.ticker._DummyAxis](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker._DummyAxis.html)
and [matplotlib.ticker.TickHelper](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.TickHelper.html) are used to control tick locations and labels."""

    def __init__(self, axes: 'GeoAxes') -> None:
        ...

    def _get_extent(self) -> tuple[float, float, float, float]:
        ...

    @staticmethod
    def _pad_ticks(ticks: np.ndarray, vmin: float, vmax: float) -> np.ndarray:
        ...

    def get_scale(self) -> str:
        ...

    def get_tick_space(self) -> int:
        ...

    def get_major_formatter(self) -> mticker.Formatter | None:
        ...

    def get_major_locator(self) -> mticker.Locator | None:
        ...

    def get_minor_locator(self) -> mticker.Locator | None:
        ...

    def get_majorticklocs(self) -> np.ndarray:
        ...

    def get_minorticklocs(self) -> np.ndarray:
        ...

    def set_major_formatter(self, formatter: mticker.Formatter, default: bool=False) -> None:
        ...

    def set_major_locator(self, locator: mticker.Locator, default: bool=False) -> None:
        ...

    def set_minor_locator(self, locator: mticker.Locator, default: bool=False) -> None:
        ...

    def set_view_interval(self, vmin: float, vmax: float) -> None:
        ...

    def _copy_locator_properties(self, other: '_GeoAxis') -> None:
        """This function copies the locator properties. It is
used when the @self is sharing with @other."""
        ...

class _GridlinerAdapter(Protocol):
    """Lightweight facade used to normalize cartopy and basemap gridliner behavior.
These adapters let GeoAxes apply gridline label toggles and styles without
backend-specific branching."""

    def labels_for_sides(self, *, bottom: bool | str | None=None, top: bool | str | None=None, left: bool | str | None=None, right: bool | str | None=None) -> dict[str, list[mtext.Text]]:
        ...

    def toggle_labels(self, *, labelleft: bool | str | None=None, labelright: bool | str | None=None, labelbottom: bool | str | None=None, labeltop: bool | str | None=None, geo: bool | str | None=None) -> None:
        ...

    def apply_style(self, *, axis: str='both', pad: float | None=None, labelsize: float | str | None=None, labelcolor: Any=None, labelrotation: float | None=None, linecolor: Any=None, linewidth: float | None=None) -> None:
        ...

    def tick_positions(self, axis: str, *, lonaxis: '_GeoAxis', lataxis: '_GeoAxis') -> np.ndarray:
        ...

    def is_label_on(self, side: str) -> bool:
        ...

class _CartopyGridlinerProtocol(Protocol):
    """Structural protocol for the subset of cartopy Gridliner attributes we use.
This keeps type hints tight without importing cartopy at runtime."""
    collection_kwargs: dict[str, Any]
    xlabel_style: dict[str, Any]
    ylabel_style: dict[str, Any]
    xlocator: mticker.Locator
    ylocator: mticker.Locator
    xpadding: float | None
    ypadding: float | None
    xlines: bool
    ylines: bool
    x_inline: bool | None
    y_inline: bool | None
    rotate_labels: bool | None
    inline_labels: bool | str | None
    geo_labels: bool | str | None
    left_label_artists: list[mtext.Text]
    right_label_artists: list[mtext.Text]
    bottom_label_artists: list[mtext.Text]
    top_label_artists: list[mtext.Text]
    xline_artists: list[Any]

    def _axes_domain(self, *args: Any, **kwargs: Any) -> tuple[Any, Any]:
        ...

    def _draw_gridliner(self, *args: Any, **kwargs: Any) -> Any:
        ...

class _CartopyGridlinerAdapter(_GridlinerAdapter):
    """Adapter for cartopy's Gridliner, translating common label/style operations
into the Gridliner API while hiding cartopy version differences."""

    def __init__(self, gridliner: Optional[_CartopyGridlinerProtocol]) -> None:
        ...

    @staticmethod
    def _side_labels() -> tuple[str, str, str, str]:
        ...

    def labels_for_sides(self, *, bottom: bool | str | None=None, top: bool | str | None=None, left: bool | str | None=None, right: bool | str | None=None) -> dict[str, list[mtext.Text]]:
        ...

    def toggle_labels(self, *, labelleft: bool | str | None=None, labelright: bool | str | None=None, labelbottom: bool | str | None=None, labeltop: bool | str | None=None, geo: bool | str | None=None) -> None:
        ...

    def apply_style(self, *, axis: str='both', pad: float | None=None, labelsize: float | str | None=None, labelcolor: Any=None, labelrotation: float | None=None, linecolor: Any=None, linewidth: float | None=None) -> None:
        ...

    def tick_positions(self, axis: str, *, lonaxis: _GeoAxis, lataxis: _GeoAxis) -> np.ndarray:
        ...

    def is_label_on(self, side: str) -> bool:
        ...

class _BasemapGridlinerAdapter(_GridlinerAdapter):
    """Adapter for basemap meridian/parallel dictionaries, emulating the subset
of cartopy Gridliner behavior needed by GeoAxes (labels, toggles, styling)."""

    def __init__(self, lonlines: GridlineDict | None, latlines: GridlineDict | None) -> None:
        ...

    def labels_for_sides(self, *, bottom: bool | str | None=None, top: bool | str | None=None, left: bool | str | None=None, right: bool | str | None=None) -> dict[str, list[mtext.Text]]:
        ...

    def toggle_labels(self, *, labelleft: bool | str | None=None, labelright: bool | str | None=None, labelbottom: bool | str | None=None, labeltop: bool | str | None=None, geo: bool | str | None=None) -> None:
        ...

    def apply_style(self, *, axis: str='both', pad: float | None=None, labelsize: float | str | None=None, labelcolor: Any=None, labelrotation: float | None=None, linecolor: Any=None, linewidth: float | None=None) -> None:
        ...

    def tick_positions(self, axis: str, *, lonaxis: _GeoAxis, lataxis: _GeoAxis) -> np.ndarray:
        ...

    def is_label_on(self, side: str) -> bool:
        ...

class _LonAxis(_GeoAxis):
    """Axis with default longitude locator."""
    axis_name = 'lon'

    def __init__(self, axes: 'GeoAxes') -> None:
        ...

    def _get_ticklocs(self, locator: mticker.Locator) -> np.ndarray:
        ...

    def get_view_interval(self) -> tuple[float, float]:
        ...

class _LatAxis(_GeoAxis):
    """Axis with default latitude locator."""
    axis_name = 'lat'

    def __init__(self, axes: 'GeoAxes', latmax: float=90) -> None:
        ...

    def _get_ticklocs(self, locator: mticker.Locator) -> np.ndarray:
        ...

    def get_latmax(self) -> float:
        ...

    def get_view_interval(self) -> tuple[float, float]:
        ...

    def set_latmax(self, latmax: float) -> None:
        ...

def _gridliner_sides_from_arrays(lonarray: Sequence[bool | None] | None, latarray: Sequence[bool | None] | None, *, order: Sequence[str], allow_xy: bool, include_false: bool) -> dict[str, bool | str]:
    """Map lon/lat label arrays to gridliner toggle flags.

Parameters
----------
allow_xy
    Use "x"/"y" to preserve axis-specific toggles when only one of lon/lat
    is enabled for a given side (cartopy behavior).
include_false
    Include explicit False entries to actively hide existing labels instead
    of leaving previous state untouched (backend-dependent behavior)."""
    ...

class GeoAxes(shared._SharedAxes, plot.PlotAxes):
    """Axes subclass for plotting in geographic projections. Uses either cartopy
or basemap as a "backend".

Note
----
This subclass uses longitude and latitude as the default coordinate system for all
plotting commands by internally passing ``transform=cartopy.crs.PlateCarree()`` to
cartopy commands and ``latlon=True`` to basemap commands. Also, when using basemap
as the "backend", plotting is still done "cartopy-style" by calling methods from
the axes instance rather than the `~mpl_toolkits.basemap.Basemap` instance.

Important
---------
This axes subclass can be used by passing ``proj='proj_name'``
to axes-creation commands like [add_axes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.add_axes),
[add_subplot](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.add_subplot), and [subplots](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.subplots),
where ``proj_name`` is a registered [PROJ projection name](https://ultraplot.readthedocs.io/en/stable/search.html?q=proj_table).
You can also pass a `~cartopy.crs.Projection` or `~mpl_toolkits.basemap.Basemap`
instance instead of a projection name. Alternatively, you can pass any of the
matplotlib-recognized axes subclass names ``proj='cartopy'``, ``proj='geo'``, or
``proj='geographic'`` with a `~cartopy.crs.Projection` `map_projection` keyword
argument, or pass ``proj='basemap'`` with a `~mpl_toolkits.basemap.Basemap`
`map_projection` keyword argument."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Parameters
----------
- `*args`: Passed to [matplotlib.axes.Axes](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.html).
- `map_projection`: The cartopy or basemap projection instance.
- `aspect`: The map aspect ratio.
- `abcanchor`: The coordinate box used for the a-b-c label.
- `round`: *For polar cartopy axes only*.
- `extent`: *For cartopy axes only*.
- `lonlim, latlim`: *For cartopy axes only.* The approximate longitude and latitude boundaries of the map, applied with `~cartopy.mpl.geoaxes.GeoAxes.set_extent`.
- `boundinglat`: *For cartopy axes only.* The edge latitude for the circle bounding North Pole and South Pole-centered projections.
- `longrid, latgrid, grid`: Whether to draw longitude and latitude gridlines.
- `longridminor, latgridminor, gridminor`: Whether to draw "minor" longitude and latitude lines.
- `lonticklen, latticklen, ticklen`: Major tick lengths for the longitudinal (x) and latitude (y) axis.
- `latmax`: The maximum absolute latitude for gridlines.
- `nsteps`: *For cartopy axes only.* The number of interpolation steps used to draw gridlines.
- `lonlocator, latlocator`: Used to determine the longitude and latitude gridline locations.
- `lonlocator_kw, latlocator_kw`: Keyword arguments passed to the [matplotlib.ticker.Locator](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Locator.html) class.
- `lonminorlocator, latminorlocator`: As with `lonlocator` and `latlocator` but for the "minor" gridlines.
- `lonminorlocator_kw, latminorlocator_kw`: As with `lonlocator_kw`, and `latlocator_kw` but for the "minor" gridlines.
- `lonlabels, latlabels, labels`: Whether to add non-inline longitude and latitude gridline labels, and on which sides of the map.
- `loninline, latinline, inlinelabels`: *For cartopy axes only.* Whether to add inline longitude and latitude gridline labels.
- `rotatelabels`: *For cartopy axes only.* Whether to rotate non-inline gridline labels so that they automatically follow the map boundary curvature.
- `labelrotation`: The rotation angle in degrees for both longitude and latitude tick labels.
- `lonlabelrotation`: The rotation angle in degrees for longitude tick labels.
- `latlabelrotation`: The rotation angle in degrees for latitude tick labels.
- `labelpad`: *For cartopy axes only.* The padding between non-inline gridline labels and the map boundary.
- `dms`: *For cartopy axes only.* Whether the default locators and formatters should use "minutes" and "seconds" for gridline labels on small scales rather than decimal degrees.
- `lonformatter, latformatter`: Formatter used to style longitude and latitude gridline labels.
- `lonformatter_kw, latformatter_kw`: Keyword arguments passed to the [matplotlib.ticker.Formatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Formatter.html) class.
- `land, ocean, coast, rivers, lakes, borders, innerborders`: Toggles various geographic features.
- `reso`: *For cartopy axes only.* The resolution of geographic features.
- `color`: The color for the axes edge.
- `gridcolor`: The color for the gridline labels.
- `labelcolor`: The color for the gridline labels (`gridlabelcolor` is also allowed).
- `labelsize`: The font size for the gridline labels (`gridlabelsize` is also allowed).
- `labelweight`: The font weight for the gridline labels (`gridlabelweight` is also allowed).
- `title`: The axes title.
- `abc`: The "a-b-c" subplot label style.
- _14 additional parameter groups are documented online._

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html)"""
        ...

    def _sync_shared_tick_state(self, which: str, *, copy_major_locator: bool=False, copy_minor_locator: bool=False, copy_major_formatter: bool=False) -> None:
        """Copy explicit tick-state changes from this axis to shared GeoAxes siblings."""
        ...

    def hawkeye(self, xy: Sequence[float], size: float | Sequence[float], *, transform: Any='axes', anchor: str | Sequence[float]='upper right', anchor_transform: Any='axes', aspect: str | float='projection', extent: Optional[Sequence[float]]=None, extent_transform: Any='map', relation: str='auto', indicator: bool=True, connector: bool | str=False, shape: str='box', target: str='box', indicator_kw: Optional[Mapping[str, Any]]=None, **kwargs: Any) -> 'GeoAxes':
        """Add a transform-anchored geographic callout inset.

Parameters
----------
- `xy`: The parent-axes coordinate at which to anchor the inset.
- `size`: The requested inset width and height as fractions of the parent axes box.
- `transform`: Coordinate system for *xy*.
- `anchor`: The inset point placed at *xy*.
- `anchor_transform`: Coordinate system for a float-tuple `anchor`.
- `aspect`: The inset aspect.
- `grid`: Whether to draw gridlines in the inset.
- `extent`: The geographic scope ``(west, east, south, north)`` displayed by the inset.
- `extent_transform`: Coordinate system for *extent*.
- `relation`: Whether the inset is a zoomed detail of the parent or an overview containing the parent extent.
- `indicator`: Whether to outline *extent* on the parent map when an extent is supplied.
- `connector`: The connector presentation.
- `shape, target`: The inset clipping shape and target marker shape.
- `indicator_kw`: Patch properties for the extent outline and connector lines.
- `**kwargs`: Passed to `~Axes.inset_axes`.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html#ultraplot.axes.GeoAxes.hawkeye)"""
        ...

    def _resolve_hawkeye_spec(self, xy: Sequence[float], size: float | Sequence[float], transform: Any, anchor: str | Sequence[float], anchor_transform: Any, extent: Optional[Sequence[float]], extent_transform: Any, relation: str, connector: bool | str, shape: str, target: str) -> '_HawkeyeSpec':
        """Validate and normalize raw hawkeye arguments into a `_HawkeyeSpec`."""
        ...

    def _resolve_hawkeye_xy_transform(self, transform: Any) -> Any:
        """Resolve the *xy* transform, accepting projection names.

Reserved names (``'axes'``, ``'data'``, ``'figure'``, ``'subfigure'``,
``'map'``), matplotlib transforms, and cartopy CRS instances are handled
by `_get_transform`. Any other string is treated as a projection
name and resolved to a cartopy CRS so *xy* can be given in arbitrary
projected coordinates."""
        ...

    def _build_hawkeye_inset(self, spec: '_HawkeyeSpec', aspect: str | float, **kwargs: Any) -> 'GeoAxes':
        """Create the inset axes and configure its extent, aspect, and boundary."""
        ...

    def _add_hawkeye_indicator(self, inset: 'GeoAxes', spec: '_HawkeyeSpec', indicator_kw: Optional[Mapping[str, Any]], color: Any) -> None:
        """Draw the extent indicator patch and any connectors onto the hawkeye."""
        ...

    @override
    def _sharey_limits(self, sharey: 'GeoAxes') -> None:
        ...

    @override
    def _sharex_limits(self, sharex: 'GeoAxes') -> None:
        ...

    def _share_limits_with(self, other: 'GeoAxes', which: str) -> None:
        """Safely share limits and tickers without resetting things."""
        ...

    def _is_rectilinear(self) -> bool:
        ...

    def __share_axis_setup(self, other: 'GeoAxes', *, which: str, labels: bool, limits: bool) -> None:
        ...

    @override
    def _sharey_setup(self, sharey: 'GeoAxes', *, labels: bool=True, limits: bool=True) -> None:
        """Configure shared axes accounting for panels. The input is the
'parent' axes, from which this one will draw its properties."""
        ...

    @override
    def _sharex_setup(self, sharex: 'GeoAxes', *, labels: bool=True, limits: bool=True) -> None:
        ...

    def _toggle_ticks(self, label: Any, which: str) -> None:
        """Toggle x/y tick positions from geo label specifications.

Accepts the same `labels` forms as format(), including booleans, strings,
and boolean/string sequences. Only sides relevant to the requested axis
are considered: bottom/top for ``which='x'`` and left/right for
``which='y'``."""
        ...

    def _set_gridliner_adapter(self, which: str, adapter: Optional[_GridlinerAdapter]) -> None:
        ...

    def _get_gridliner_adapter(self, which: str) -> Optional[_GridlinerAdapter]:
        ...

    def _gridliner_adapter(self, which: str, *, create: bool=True) -> Optional[_GridlinerAdapter]:
        """Return a cached gridliner adapter, optionally creating it via the backend
builder when missing."""
        ...

    def _iter_gridliner_adapters(self, which: str) -> Iterator[_GridlinerAdapter]:
        """Yield available gridliner adapters for the requested tick selection."""
        ...

    def _gridliner_tick_positions(self, axis: str, *, which: str='major') -> np.ndarray:
        """Return tick positions from the backend gridliner for a given axis."""
        ...

    @override
    def tick_params(self, *args: Any, **kwargs: Any) -> Any:
        """Apply tick parameters and mirror a subset of settings onto the backend
gridliner artists so gridline labels respond to common tick tweaks."""
        ...

    def _apply_axis_sharing(self) -> None:
        """Enforce the "shared" axis labels and axis tick labels. If this is not
called at drawtime, "shared" labels can be inadvertantly turned off.

Notes:
    - Critical to apply labels to *shared* axes attributes rather than testing
        extents or we end up sharing labels with twin axes.
    - Similar to how align_super_labels() calls apply_title_above(), this is called
        inside align_axis_labels() so we align the correct text.
    - The "panel sharing group" refers to axes and panels *above* the bottommost
        or to the *right* of the leftmost panel. But the sharing level used for
        the leftmost and bottommost is the *figure* sharing level."""
        ...

    def _apply_aspect_and_adjust_panels(self, *, tol: float=1e-09) -> None:
        """Apply aspect and then align panels to the adjusted axes box.

Notes
-----
Cartopy and basemap use different tolerances when detecting whether
apply_aspect() actually changed the axes position."""
        ...

    def _compute_span_extent(self, side: Incomplete, panel: Incomplete, gs: Incomplete, p_r1: Incomplete, p_r2: Incomplete, p_c1: Incomplete, p_c2: Incomplete) -> tuple[float, float] | None:
        """If the panel spans beyond the parent's SubplotSpec, compute the visual
extent (min, max) along the span axis from all non-panel axes in range.
Returns None if not a span override or no valid extent found."""
        ...

    @staticmethod
    def _compute_adjusted_panel_pos(side: Incomplete, panel_pos: Incomplete, span_extent: Incomplete, original_pos: Incomplete, main_pos: Incomplete, sx: Incomplete, sy: Incomplete, tol: Incomplete) -> Incomplete:
        """Compute the new [x0, y0, width, height] for a panel on the given side,
accounting for aspect-adjusted main axes and optional span extent.
Returns the new position list, or None for unknown sides."""
        ...

    def _adjust_panel_positions(self, *, tol: float=1e-09) -> None:
        """Adjust panel positions to align with the aspect-constrained main axes.
After apply_aspect() shrinks the main axes, panels should flank the actual
map boundaries rather than the full gridspec allocation."""
        ...

    def _get_gridliner_labels(self, bottom: bool | str | None=None, top: bool | str | None=None, left: bool | str | None=None, right: bool | str | None=None) -> dict[str, list[mtext.Text]]:
        ...

    def _update_title_position(self, renderer: Any) -> None:
        """Optionally anchor the a-b-c label to the unadjusted subplot slot."""
        ...

    def _toggle_gridliner_labels(self, labeltop: bool | str | None=None, labelbottom: bool | str | None=None, labelleft: bool | str | None=None, labelright: bool | str | None=None, geo: bool | str | None=None) -> None:
        """Toggle visibility of gridliner labels for each direction via the backend
adapter.

Parameters
----------
labeltop, labelbottom, labelleft, labelright : bool or None
    Whether to show labels on each side. If None, do not change.
geo : optional
    Not used in this method."""
        ...

    @override
    def _is_ticklabel_on(self, side: str) -> bool:
        """Check if tick labels are visible on the requested side via the backend adapter."""
        ...

    def _clear_edge_lon_labels(self) -> None:
        ...

    def _sync_edge_lon_labels(self) -> None:
        """Ensure cartopy top longitude labels include the endpoints when requested."""
        ...

    def _clear_edge_lat_labels(self) -> None:
        ...

    def _sync_edge_lat_labels(self) -> None:
        """Ensure cartopy left/right latitude labels include the endpoints when requested."""
        ...

    def _prune_corner_labels(self) -> bool:
        """Drop endpoint labels at the map corners to reduce crowding."""
        ...

    @override
    def draw(self, renderer: Any=None, *args: Any, **kwargs: Any) -> None:
        """Draw the Artist (and its children) using the given renderer.

This has no effect if the artist is not visible (`.Artist.get_visible`
returns False).

Parameters
----------
renderer : [RendererBase](https://matplotlib.org/stable/api/_as_gen/matplotlib.backend_bases.RendererBase.html) subclass.

Notes
-----
This method is overridden in the Artist subclasses."""
        ...

    def _get_lonticklocs(self, which: str='major') -> np.ndarray:
        """Retrieve longitude tick locations."""
        ...

    def _get_latticklocs(self, which: str='major') -> np.ndarray:
        """Retrieve latitude tick locations."""
        ...

    def _set_view_intervals(self, extent: Sequence[float]) -> None:
        """Update view intervals for lon and lat axis."""
        ...

    @staticmethod
    def _to_label_array(arg: Any, lon: bool=True) -> list[bool | None]:
        """Convert labels argument to length-5 boolean array."""
        ...

    def _format_init_basemap_boundary(self) -> None:
        """Initialize basemap boundaries before format triggers gridline work.

Basemap can create a hidden boundary when gridlines are drawn before the
map boundary is initialized, so we force initialization here."""
        ...

    def _format_rc_context(self, kwargs: MutableMapping[str, Any], *, ticklen: Any, labelcolor: Any, labelsize: Any, labelweight: Any) -> tuple[dict[str, Any], int, Any]:
        """Pop rc overrides and prepare context settings for format()."""
        ...

    def _format_normalize_label_inputs(self, *, labels: Any, lonlabels: Any, latlabels: Any, loninline: bool | None, latinline: bool | None, inlinelabels: bool | None) -> tuple[Any, Any]:
        """Normalize label inputs before rc context is applied."""
        ...

    def _format_resolve_label_arrays(self, *, labels: Any, lonlabels: Any, latlabels: Any) -> tuple[Any, Any, list[bool | None], list[bool | None]]:
        """Resolve label toggles and return label arrays for gridliners."""
        ...

    def _format_update_latmax(self, latmax: float | None) -> None:
        """Update the latitude gridline cutoff."""
        ...

    def _format_update_major_locators(self, *, lonlocator: Any, lonlines: Any, latlocator: Any, latlines: Any, lonlocator_kw: MutableMapping | None, lonlines_kw: MutableMapping | None, latlocator_kw: MutableMapping | None, latlines_kw: MutableMapping | None) -> None:
        """Update major longitude/latitude locators."""
        ...

    def _format_update_minor_locators(self, *, lonminorlocator: Any, lonminorlines: Any, latminorlocator: Any, latminorlines: Any, lonminorlocator_kw: MutableMapping | None, lonminorlines_kw: MutableMapping | None, latminorlocator_kw: MutableMapping | None, latminorlines_kw: MutableMapping | None) -> None:
        """Update minor longitude/latitude locators."""
        ...

    def _format_resolve_gridline_params(self, *, loninline: bool | None, latinline: bool | None, inlinelabels: bool | None, rotatelabels: bool | None, labelrotation: float | None, lonlabelrotation: float | None, latlabelrotation: float | None, labelpad: Any, dms: bool | None, nsteps: int | None) -> tuple[bool | None, bool | None, bool | None, float | None, float | None, Any, bool | None, int | None]:
        """Resolve gridline-related parameters with rc defaults."""
        ...

    def _format_update_formatters(self, *, lonformatter: Any, latformatter: Any, lonformatter_kw: MutableMapping | None, latformatter_kw: MutableMapping | None, dms: bool | None) -> None:
        """Update longitude/latitude formatters and DMS flags."""
        ...

    def _format_apply_grid_updates(self, *, lonlim: tuple[float | None, float | None] | None, latlim: tuple[float | None, float | None] | None, boundinglat: float | None, longrid: bool | None, latgrid: bool | None, longridminor: bool | None, latgridminor: bool | None, lonarray: Sequence[bool | None], latarray: Sequence[bool | None], loninline: bool | None, latinline: bool | None, rotatelabels: bool | None, lonlabelrotation: float | None, latlabelrotation: float | None, labelpad: Any, nsteps: int | None) -> tuple[tuple[float | None, float | None], tuple[float | None, float | None]]:
        """Apply extent, features, and gridline updates for format()."""
        ...

    def _format_apply_ticklen(self, *, lonlim: tuple[float | None, float | None], latlim: tuple[float | None, float | None], boundinglat: float | None, ticklen: Any, lonticklen: Any, latticklen: Any) -> None:
        """Apply tick length updates, including any extent refresh for geoticks."""
        ...

    def format(self, *, aspect: str | float | None=None, abcanchor: str | None=None, extent: str | None=None, round: bool | None=None, lonlim: tuple[float | None, float | None] | None=None, latlim: tuple[float | None, float | None] | None=None, boundinglat: float | None=None, longrid: bool | None=None, latgrid: bool | None=None, longridminor: bool | None=None, latgridminor: bool | None=None, ticklen: Any=None, lonticklen: Any=None, latticklen: Any=None, latmax: float | None=None, nsteps: int | None=None, lonlocator: Any=None, lonlines: Any=None, latlocator: Any=None, latlines: Any=None, lonminorlocator: Any=None, lonminorlines: Any=None, latminorlocator: Any=None, latminorlines: Any=None, lonlocator_kw: MutableMapping | None=None, lonlines_kw: MutableMapping | None=None, latlocator_kw: MutableMapping | None=None, latlines_kw: MutableMapping | None=None, lonminorlocator_kw: MutableMapping | None=None, lonminorlines_kw: MutableMapping | None=None, latminorlocator_kw: MutableMapping | None=None, latminorlines_kw: MutableMapping | None=None, lonformatter: Any=None, latformatter: Any=None, lonformatter_kw: MutableMapping | None=None, latformatter_kw: MutableMapping | None=None, labels: Any=None, latlabels: Any=None, lonlabels: Any=None, rotatelabels: bool | None=None, labelrotation: float | None=None, lonlabelrotation: float | None=None, latlabelrotation: float | None=None, loninline: bool | None=None, latinline: bool | None=None, inlinelabels: bool | None=None, dms: bool | None=None, labelpad: Any=None, labelcolor: Any=None, labelsize: Any=None, labelweight: Any=None, **kwargs: Any) -> None:
        """Modify map limits, longitude and latitude gridlines, geographic features, and more.

Parameters
----------
- `aspect`: The map aspect ratio.
- `abcanchor`: The coordinate box used for the a-b-c label.
- `round`: *For polar cartopy axes only*.
- `extent`: *For cartopy axes only*.
- `lonlim, latlim`: *For cartopy axes only.* The approximate longitude and latitude boundaries of the map, applied with `~cartopy.mpl.geoaxes.GeoAxes.set_extent`.
- `boundinglat`: *For cartopy axes only.* The edge latitude for the circle bounding North Pole and South Pole-centered projections.
- `longrid, latgrid, grid`: Whether to draw longitude and latitude gridlines.
- `longridminor, latgridminor, gridminor`: Whether to draw "minor" longitude and latitude lines.
- `lonticklen, latticklen, ticklen`: Major tick lengths for the longitudinal (x) and latitude (y) axis.
- `latmax`: The maximum absolute latitude for gridlines.
- `nsteps`: *For cartopy axes only.* The number of interpolation steps used to draw gridlines.
- `lonlocator, latlocator`: Used to determine the longitude and latitude gridline locations.
- `lonlocator_kw, latlocator_kw`: Keyword arguments passed to the [matplotlib.ticker.Locator](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Locator.html) class.
- `lonminorlocator, latminorlocator`: As with `lonlocator` and `latlocator` but for the "minor" gridlines.
- `lonminorlocator_kw, latminorlocator_kw`: As with `lonlocator_kw`, and `latlocator_kw` but for the "minor" gridlines.
- `lonlabels, latlabels, labels`: Whether to add non-inline longitude and latitude gridline labels, and on which sides of the map.
- `loninline, latinline, inlinelabels`: *For cartopy axes only.* Whether to add inline longitude and latitude gridline labels.
- `rotatelabels`: *For cartopy axes only.* Whether to rotate non-inline gridline labels so that they automatically follow the map boundary curvature.
- `labelrotation`: The rotation angle in degrees for both longitude and latitude tick labels.
- `lonlabelrotation`: The rotation angle in degrees for longitude tick labels.
- `latlabelrotation`: The rotation angle in degrees for latitude tick labels.
- `labelpad`: *For cartopy axes only.* The padding between non-inline gridline labels and the map boundary.
- `dms`: *For cartopy axes only.* Whether the default locators and formatters should use "minutes" and "seconds" for gridline labels on small scales rather than decimal degrees.
- `lonformatter, latformatter`: Formatter used to style longitude and latitude gridline labels.
- `lonformatter_kw, latformatter_kw`: Keyword arguments passed to the [matplotlib.ticker.Formatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Formatter.html) class.
- `land, ocean, coast, rivers, lakes, borders, innerborders`: Toggles various geographic features.
- `reso`: *For cartopy axes only.* The resolution of geographic features.
- `color`: The color for the axes edge.
- `gridcolor`: The color for the gridline labels.
- `labelcolor`: The color for the gridline labels (`gridlabelcolor` is also allowed).
- `labelsize`: The font size for the gridline labels (`gridlabelsize` is also allowed).
- `labelweight`: The font weight for the gridline labels (`gridlabelweight` is also allowed).
- `title`: The axes title.
- `abc`: The "a-b-c" subplot label style.
- `abcloc, titleloc`: Strings indicating the location for the a-b-c label and main title.
- `abcborder, titleborder`: Whether to draw a white border around titles and a-b-c labels positioned inside the axes.
- _21 additional parameter groups are documented online._

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html#ultraplot.axes.GeoAxes.format)"""
        ...

    def choropleth(self, geometries: Sequence[Any], values: Sequence[Any] | None=None, *, transform: Any=None, country: bool=False, country_reso: str | None=None, country_territories: bool | None=None, colorbar: Any=None, colorbar_kw: MutableMapping[str, Any] | None=None, missing_kw: MutableMapping[str, Any] | None=None, **kwargs: Any) -> mcollections.PatchCollection:
        """Draw polygon geometries colored by numeric values.

Parameters
----------
- `geometries`: Sequence of polygon-like shapely geometries.
- `values`: Numeric values mapped to colors.
- `transform`: The input coordinate system for `geometries`.
- `country`: Interpret `geometries` as country identifiers and resolve them to Natural Earth polygons before plotting.
- `country_reso`: The Natural Earth country resolution used when `country=True`.
- `country_territories`: Whether to keep distant territories for multi-part country geometries when `country=True`.
- `missing_kw`: Style applied to geometries whose values are missing or non-finite.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html#ultraplot.axes.GeoAxes.choropleth)"""
        ...

    def _add_geoticks(self, x_or_y: str, itick: Any, ticklen: Any) -> None:
        """Add tick marks to the geographic axes.

Parameters
----------
x_or_y : {'x', 'y'}
    The axis to add ticks to ('x' for longitude, 'y' for latitude).
itick, ticklen : unit-spec, default: [tick.len](https://ultraplot.readthedocs.io/en/stable/search.html?q=tick.len)
    Major tick lengths for the x and y axis.
    If float, units are points. If string, interpreted by [units](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.utils.units.html).
    Use the argument `ticklen` to set both at once.

Notes
-----
This method handles proper tick mark drawing for geographic projections
while respecting the current gridline settings."""
        ...

    def _add_gridline_labels(self, ax: maxis.Axis, gl: tuple[GridlineDict, GridlineDict], padding: float | int=8) -> None:
        """This function is intended for the Basemap backend
and mirrors the label placement behavior of Cartopy.
See: https://cartopy.readthedocs.io/stable/reference/generated/cartopy.mpl.gridliner.Gridliner.html"""
        ...

    @property
    def gridlines_major(self) -> Any:
        """The cartopy `~cartopy.mpl.gridliner.Gridliner`
used for major gridlines or a 2-tuple containing the
(longitude, latitude) major gridlines returned by
basemap's `drawmeridians`
and `drawparallels`.
This can be used for customization and debugging."""
        ...

    @property
    def gridlines_minor(self) -> Any:
        """The cartopy `~cartopy.mpl.gridliner.Gridliner`
used for minor gridlines or a 2-tuple containing the
(longitude, latitude) minor gridlines returned by
basemap's `drawmeridians`
and `drawparallels`.
This can be used for customization and debugging."""
        ...

    @property
    def projection(self) -> Any:
        """The cartopy `~cartopy.crs.Projection` or basemap `~mpl_toolkits.basemap.Basemap`
instance associated with this axes."""
        ...

    @projection.setter
    def projection(self, map_projection: Any) -> None:
        """The cartopy `~cartopy.crs.Projection` or basemap `~mpl_toolkits.basemap.Basemap`
instance associated with this axes."""
        ...

class _CartopyAxes(GeoAxes, _GeoAxes):
    """Axes subclass for plotting cartopy projections."""
    _name = 'cartopy'
    _name_aliases = ('geo', 'geographic')
    _proj_class = Projection
    _PANEL_TOL = 1e-09
    _proj_north = (pproj.NorthPolarStereo, pproj.NorthPolarGnomonic, pproj.NorthPolarAzimuthalEquidistant, pproj.NorthPolarLambertAzimuthalEqualArea)
    _proj_south = (pproj.SouthPolarStereo, pproj.SouthPolarGnomonic, pproj.SouthPolarAzimuthalEquidistant, pproj.SouthPolarLambertAzimuthalEqualArea)
    _proj_polar = _proj_north + _proj_south

    def __init__(self, *args: Any, map_projection: Any=None, **kwargs: Any) -> None:
        """Parameters
----------
map_projection : ~cartopy.crs.Projection
    The map projection.
*args, **kwargs
    Passed to `GeoAxes`."""
        ...

    @staticmethod
    def _get_circle_path(N: int=100) -> mpath.Path:
        """Return a circle [Path](https://matplotlib.org/stable/api/_as_gen/matplotlib.path.Path.html) used as the outline for polar
stereographic, azimuthal equidistant, Lambert conformal, and gnomonic
projections. This was developed from [this cartopy example](https://cartopy.readthedocs.io/v0.25.0.post2/gallery/lines_and_polygons/always_circular_stereo.html)."""
        ...

    def _get_global_extent(self) -> list[float]:
        """Return the global extent with meridian properly shifted."""
        ...

    def _get_lon0(self) -> float:
        """Get the central longitude. Default is ``0``."""
        ...

    def gridlines(self, crs: Any=None, draw_labels: bool | str | None=False, xlocs: mticker.Locator | Sequence[float] | None=None, ylocs: mticker.Locator | Sequence[float] | None=None, dms: bool=False, x_inline: bool | None=None, y_inline: bool | None=None, auto_inline: bool=True, xformatter: Any=None, yformatter: Any=None, xlim: Sequence[float] | None=None, ylim: Sequence[float] | None=None, rotate_labels: bool | float | None=None, xlabel_style: MutableMapping[str, Any] | None=None, ylabel_style: MutableMapping[str, Any] | None=None, labels_bbox_style: MutableMapping[str, Any] | None=None, xpadding: float | None=5, ypadding: float | None=5, offset_angle: float=25, auto_update: bool | None=None, formatter_kwargs: MutableMapping[str, Any] | None=None, **kwargs: Any) -> _CartopyGridlinerProtocol:
        """Override cartopy gridlines to use a local Gridliner subclass."""
        ...

    def _init_gridlines(self) -> _CartopyGridlinerProtocol:
        """Create "major" and "minor" gridliners managed by ultraplot."""
        ...

    def _build_gridliner_adapter(self, which: str='major') -> Optional[_GridlinerAdapter]:
        ...

    def _update_background(self, **kwargs: Any) -> None:
        """Update the map background patches. This is called in `Axes.format`."""
        ...

    def _update_boundary(self, round: bool | None=None) -> None:
        """Update the map boundary path."""
        ...

    def _update_extent_mode(self, extent: str | None=None, boundinglat: float | None=None) -> None:
        """Update the extent mode."""
        ...

    def _update_extent(self, lonlim: tuple[float | None, float | None] | None=None, latlim: tuple[float | None, float | None] | None=None, boundinglat: float | None=None) -> None:
        """Set the projection extent."""
        ...

    def _update_features(self) -> None:
        """Update geographic features."""
        ...

    def _update_gridlines(self, gl: _CartopyGridlinerProtocol, which: str='major', longrid: bool | None=None, latgrid: bool | None=None, nsteps: int | None=None) -> None:
        """Update gridliner object with axis locators, and toggle gridlines on and off."""
        ...

    def _update_major_gridlines(self, longrid: bool | None=None, latgrid: bool | None=None, lonarray: Sequence[bool | None] | None=None, latarray: Sequence[bool | None] | None=None, loninline: bool | None=None, latinline: bool | None=None, labelpad: Any=None, rotatelabels: bool | None=None, lonlabelrotation: float | None=None, latlabelrotation: float | None=None, nsteps: int | None=None) -> None:
        """Update major gridlines."""
        ...

    def _update_minor_gridlines(self, longrid: bool | None=None, latgrid: bool | None=None, nsteps: int | None=None) -> None:
        """Update minor gridlines."""
        ...

    def get_extent(self, crs: Any=None) -> Sequence[float]:
        ...

    @override
    def draw(self, renderer: Any=None, *args: Any, **kwargs: Any) -> None:
        """Override draw to adjust panel positions for cartopy axes.

Cartopy's apply_aspect() can shrink the main axes to enforce the projection
aspect ratio. Panels occupy separate gridspec slots, so we reposition them
after the main axes has applied its aspect but before the panel axes are drawn."""
        ...

    def get_tightbbox(self, renderer: Any, *args: Any, **kwargs: Any) -> Any:
        """Return the tight bounding box of the Axes, including axis and their
decorators (xlabel, title, etc).

Artists that have ``artist.set_in_layout(False)`` are not included
in the bbox.

Parameters
----------
renderer : `.RendererBase` subclass
    renderer that will be used to draw the figures (i.e.
    ``fig.canvas.get_renderer()``)

bbox_extra_artists : list of `.Artist` or ``None``
    List of artists to include in the tight bounding box.  If
    ``None`` (default), then all artist children of the Axes are
    included in the tight bounding box.

call_axes_locator : bool, default: True
    If *call_axes_locator* is ``False``, it does not call the
    ``_axes_locator`` attribute, which is necessary to get the correct
    bounding box. ``call_axes_locator=False`` can be used if the
    caller is only interested in the relative size of the tightbbox
    compared to the Axes bbox.

for_layout_only : default: False
    The bounding box will *not* include the x-extent of the title and
    the xlabel, or the y-extent of the ylabel.

Returns
-------
`.BboxBase`
    Bounding box in figure pixel coordinates.

See Also
--------
matplotlib.axes.Axes.get_window_extent
matplotlib.axis.Axis.get_tightbbox
matplotlib.spines.Spine.get_window_extent"""
        ...

    def set_extent(self, extent: Sequence[float], crs: Any=None) -> Any:
        ...

    def set_global(self) -> Any:
        ...

class _BasemapAxes(GeoAxes):
    """Axes subclass for plotting basemap projections."""
    _name = 'basemap'
    _proj_class = Basemap
    _proj_north = ('npaeqd', 'nplaea', 'npstere')
    _proj_south = ('spaeqd', 'splaea', 'spstere')
    _proj_polar = _proj_north + _proj_south
    _proj_non_rectangular = _proj_polar + ('ortho', 'geos', 'nsper', 'moll', 'hammer', 'robin', 'eck4', 'kav7', 'mbtfpq', 'sinu', 'vandg')
    _PANEL_TOL = 1e-06

    def __init__(self, *args: Any, map_projection: Any=None, **kwargs: Any) -> None:
        """Parameters
----------
map_projection : ~mpl_toolkits.basemap.Basemap
    The map projection.
*args, **kwargs
    Passed to `GeoAxes`."""
        ...

    def get_tightbbox(self, renderer: Any, *args: Any, **kwargs: Any) -> Any:
        """Get tight bounding box, adjusting panel positions after aspect is applied.

This ensures panels are properly aligned when saving figures, as apply_aspect()
may be called during the rendering process."""
        ...

    @override
    def draw(self, renderer: Any=None, *args: Any, **kwargs: Any) -> None:
        """Override draw to adjust panel positions for basemap axes.

Basemap projections also rely on apply_aspect() and can shrink the main axes;
panels must be repositioned to flank the visible map boundaries."""
        ...

    def _turnoff_tick_labels(self, locator: GridlineDict) -> None:
        """For GeoAxes with are dealing with a duality. Basemap axes behave differently than Cartopy axes and vice versa. UltraPlot abstracts away from these by providing GeoAxes. For basemap axes we need to turn off the tick labels as they will be handles by GeoAxis"""
        ...

    def _get_lon0(self) -> float:
        """Get the central longitude."""
        ...

    @staticmethod
    def _iter_gridlines(dict_: GridlineDict | None) -> Iterator[Any]:
        """Iterate over longitude latitude lines."""
        ...

    def _build_gridliner_adapter(self, which: str='major') -> Optional[_GridlinerAdapter]:
        ...

    def _update_background(self, **kwargs: Any) -> None:
        """Update the map boundary patches. This is called in `Axes.format`."""
        ...

    def _update_boundary(self, round: bool | None=None) -> None:
        """No-op. Boundary mode cannot be changed in basemap."""
        ...

    def _update_extent_mode(self, extent: str | None=None, boundinglat: float | None=None) -> None:
        """No-op. Extent mode cannot be changed in basemap."""
        ...

    def _update_extent(self, lonlim: tuple[float | None, float | None] | None=None, latlim: tuple[float | None, float | None] | None=None, boundinglat: float | None=None) -> None:
        """No-op. Map bounds cannot be changed in basemap."""
        ...

    def _update_features(self) -> None:
        """Update geographic features."""
        ...

    def _update_gridlines(self, which: str='major', longrid: bool | None=None, latgrid: bool | None=None, lonarray: Sequence[bool | None] | None=None, latarray: Sequence[bool | None] | None=None, lonlabelrotation: float | None=None, latlabelrotation: float | None=None) -> None:
        """Apply changes to the basemap axes."""
        ...

    def _update_major_gridlines(self, longrid: bool | None=None, latgrid: bool | None=None, lonarray: Sequence[bool | None] | None=None, latarray: Sequence[bool | None] | None=None, loninline: bool | None=None, latinline: bool | None=None, rotatelabels: bool | None=None, lonlabelrotation: float | None=None, latlabelrotation: float | None=None, labelpad: Any=None, nsteps: int | None=None) -> None:
        """Update major gridlines."""
        ...

    def _update_minor_gridlines(self, longrid: bool | None=None, latgrid: bool | None=None, nsteps: int | None=None) -> None:
        """Update minor gridlines."""
        ...

def _is_platecarree_crs(transform: Any) -> bool:
    """Return whether `transform` represents plain longitude-latitude coordinates."""
    ...

def _choropleth_close_path(vertices: Any) -> mpath.Path | None:
    """Convert a single polygon ring into a closed path."""
    ...

def _choropleth_iter_rings(geometry: Any) -> Iterator[Any]:
    """Yield polygon rings from shapely-like polygon geometries."""
    ...

def _choropleth_project_vertices(ax: GeoAxes, vertices: Any, *, transform: Any=None) -> np.ndarray:
    """Project polygon-ring vertices into the target map coordinate system."""
    ...

def _choropleth_geometry_path(ax: GeoAxes, geometry: Any, *, transform: Any=None) -> mpath.Path | None:
    """Convert a polygon geometry to a projected matplotlib path."""
    ...

def _choropleth_country_inputs(geometries: Any, values: Any, *, transform: Any=None, resolution: str='110m', include_far: bool=False) -> tuple[list[Any], Any, Any]:
    """Resolve country identifiers into polygon geometries."""
    ...

def _choropleth_edge_collection_kw(kw: Mapping[str, Any], *, zorder: float, explicit_zorder: bool=False) -> dict[str, Any] | None:
    """Return edge-only collection settings when polygon outlines should overlay features."""
    ...

def _is_rectilinear_projection(ax: Any) -> bool:
    """Check if the axis has a flat projection (works with Cartopy)."""
    ...
