# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
An axes used to jointly format Cartesian and polar axes.
"""
from _typeshed import Incomplete
import contextvars
import functools
import numpy as np
from ..config import rc
from .._sharing import AXIS_LABEL_FORMAT_KEYS, axis_supports_format_key, axis_sharing_updates_enabled, get_axis_sharing_format_keys, restore_axis_sharing, snapshot_axis_sharing, update_sharing_for_format_keys, validate_axis_format_values
from ..internals import ic
from ..internals import _pop_kwargs
from ..utils import _fontsize_to_pt, _not_none, units
from ..axes import Axes
try:
    from typing import override
except ImportError:
    from typing_extensions import override
_active_format_axes = contextvars.ContextVar('active_format_axes', default=())

def _format_wrapper(method: Incomplete=None, *, exclude: Incomplete=(), capture_explicit: Incomplete=False) -> Incomplete:
    """Decorate a public format method with transactional sharing updates."""
    ...

class _SharedAxes(object):
    """Mix-in class with methods shared between [CartesianAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.CartesianAxes.html)
and [PolarAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.PolarAxes.html)."""

    def _update_format_sharing(self, format_keys: Incomplete) -> None:
        """Apply sharing effects for one explicit axes-level format call."""
        ...

    @staticmethod
    def _min_max_lim(key: Incomplete, min_: Incomplete=None, max_: Incomplete=None, lim: Incomplete=None) -> Incomplete:
        """Translate and standardize minimum, maximum, and limit keyword arguments."""
        ...

    def _update_background(self, **kwargs: Incomplete) -> Incomplete:
        """Update the background patch."""
        ...

    def _update_frame(self, x: Incomplete, *, edgecolor: Incomplete=None, linewidth: Incomplete=None, tickcolor: Incomplete=None, tickwidth: Incomplete=None, tickwidthratio: Incomplete=None) -> None:
        """Update the axis frame, including spines and tick line appearance."""
        ...

    def _update_ticks(self, x: Incomplete, *, grid: Incomplete=None, gridminor: Incomplete=None, gridpad: Incomplete=None, gridcolor: Incomplete=None, ticklen: Incomplete=None, ticklenratio: Incomplete=None, tickdir: Incomplete=None, tickcolor: Incomplete=None, labeldir: Incomplete=None, labelpad: Incomplete=None, labelcolor: Incomplete=None, labelsize: Incomplete=None, labelweight: Incomplete=None) -> None:
        """Update the gridlines and labels. Set `gridpad` to ``True`` to use grid padding."""
        ...

    @override
    def sharex(self, other: Incomplete) -> Incomplete:
        ...

    @override
    def sharey(self, other: Incomplete) -> Incomplete:
        ...

    def _share_axis_with(self, other: 'Axes', *, which: str) -> TypeError | None:
        ...
