# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""Private helpers for responsive interactive figure navigation."""
from _typeshed import Incomplete
from contextlib import contextmanager
from dataclasses import dataclass, field
import time
import matplotlib.collections as mcollections
import numpy as np
from matplotlib.backend_bases import TimerBase
from matplotlib.ticker import MaxNLocator, NullLocator
_MISSING = object()
_MIN_PREVIEW_SURFACE_CELLS = 625
_PREVIEW_SURFACE_SAMPLES = 10
_PREVIEW_TICK_COUNT = 3
_TARGET_FRAME_RATE = 60
_MS_PER_SECOND = 1000

def _preview_enabled() -> Incomplete:
    """Return the current runtime setting for approximate navigation frames."""
    ...

def _state_equal(left: Incomplete, right: Incomplete) -> bool:
    """Return whether an artist property still matches our preview value."""
    ...

@dataclass
class _LocatorPreviewState:
    """Exact and temporary locators for one axis."""
    axis: object
    original_major: object
    original_minor: object
    preview_major: object
    preview_minor: object

    def restore(self) -> None:
        ...

@dataclass
class _LinePreviewState:
    """Exact and sampled data for one line artist."""
    artist: object
    original: tuple
    preview: tuple
    dimensions: str

    def restore(self) -> None:
        ...

@dataclass
class _ScatterPreviewState:
    """Exact and sampled private collection fields for one scatter artist."""
    artist: object
    original: dict
    preview: dict

    def restore(self) -> None:
        ...

@dataclass
class _SurfacePreviewState:
    """Temporary surface proxy attachment and draw-suppression state."""
    artist: object
    proxy: object
    ax: object
    proxy_attached: bool
    proxy_visible: bool
    hidden_marker: object

    def restore(self) -> None:
        ...

@dataclass
class _AxesPreviewState:
    """All temporary navigation state owned for one axes."""
    ax: object
    grid_marker: object = _MISSING
    locators: list = field(default_factory=list)
    lines: list = field(default_factory=list)
    scatters: list = field(default_factory=list)
    surfaces: list = field(default_factory=list)
    restored: bool = False

    def restore(self) -> None:
        ...

@dataclass
class _SurfaceProxyRecipe:
    """Lazy recipe for a coarse surface used only during navigation."""
    arrays: tuple
    args: tuple
    kwargs: dict
    geometry_signature: tuple
    facecolor_signature: tuple
    proxy: object = None

def _surface_geometry_signature(surface: Incomplete) -> Incomplete:
    ...

def _surface_facecolor_signature(surface: Incomplete) -> Incomplete:
    ...

def _register_surface_preview(surface: Incomplete, X: Incomplete, Y: Incomplete, Z: Incomplete, args: Incomplete, kwargs: Incomplete) -> None:
    """Attach a lazy coarse-surface recipe without constructing another artist."""
    ...

def _sync_surface_proxy(surface: Incomplete, proxy: Incomplete) -> None:
    """Copy safe presentation properties from an exact surface to its proxy."""
    ...

def _prepare_surface_preview(surface: Incomplete) -> Incomplete:
    """Synchronize an attached proxy and return whether to suppress the exact one."""
    ...

def _resolve_surface_proxy(surface: Incomplete) -> Incomplete:
    """Create or return a valid lazy surface proxy for an exact collection."""
    ...

class _FramePacer:
    """Coalesce GUI draws and submit the newest view near a 60 Hz cadence."""
    _interval = 1 / _TARGET_FRAME_RATE

    def __init__(self, canvas: Incomplete, is_active: Incomplete) -> None:
        ...

    def cancel(self) -> None:
        ...

    def _submit(self) -> Incomplete:
        ...

    def _schedule(self) -> bool:
        ...

    def request(self, draw: Incomplete) -> bool:
        ...

    def acknowledge(self) -> None:
        ...

class _NavigationInteractionManager:
    """Temporarily simplify dense scenes during interactive navigation."""
    _line_limit = 2000
    _scatter_limit = 2000

    def __init__(self, canvas: Incomplete, figure: Incomplete, selective: Incomplete) -> None:
        ...

    def _is_active(self) -> Incomplete:
        ...

    @staticmethod
    def _is_three_axes(ax: Incomplete) -> Incomplete:
        ...

    @staticmethod
    def _subset_indices(arrays: Incomplete, limit: Incomplete) -> Incomplete:
        ...

    @staticmethod
    def _shared_view_axes(ax: Incomplete) -> Incomplete:
        ...

    @staticmethod
    def _shared_two_axes(ax: Incomplete) -> Incomplete:
        ...

    @staticmethod
    def _simplify_locator(axis: Incomplete, state: Incomplete) -> None:
        ...

    def _simplify_line(self, line: Incomplete, dimensions: Incomplete, state: Incomplete) -> None:
        ...

    def _simplify_scatter(self, artist: Incomplete, arrays: Incomplete, indices: Incomplete, names: Incomplete, state: Incomplete) -> None:
        ...

    def _simplify_three_axes(self, ax: Incomplete) -> _AxesPreviewState:
        ...

    def _simplify_two_axes(self, ax: Incomplete) -> _AxesPreviewState:
        ...

    def activate(self, ax: Incomplete) -> bool:
        """Activate preview quality for the navigated axes and shared siblings."""
        ...

    def deactivate(self, *, redraw: Incomplete=True) -> bool:
        """Restore exact artists and formatting after interactive navigation."""
        ...

    def request_draw(self, draw: Incomplete) -> bool:
        ...

    @contextmanager
    def full_quality_context(self) -> Incomplete:
        ...

    def _on_press(self, event: Incomplete) -> None:
        ...

    def _on_release(self, event: Incomplete) -> None:
        ...

    def _on_draw(self, event: Incomplete) -> None:
        ...

    def _on_close(self, event: Incomplete) -> None:
        ...

    def close(self) -> None:
        ...
