# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Helpers for lazy attribute loading in :mod:`ultraplot`.
"""
from _typeshed import Incomplete
import ast
import importlib.util
import types
from importlib import import_module
from pathlib import Path
from typing import Any, Callable, Dict, Mapping, MutableMapping, Optional

class LazyLoader:
    """
    Encapsulates lazy-loading mechanics for the ultraplot top-level module.
    """

    def __init__(self, *, package: str, package_path: Path, exceptions: Mapping[str, tuple[str, Optional[str]]], setup_callback: Callable[[], None], registry_attr_callback: Callable[[str], Optional[type]], registry_build_callback: Callable[[], None], registry_names_callback: Callable[[], Optional[Mapping[str, type]]], attr_map_key: str='_ATTR_MAP', eager_key: str='_EAGER_DONE') -> None:
        ...

    def _import_module(self, module_name: str) -> types.ModuleType:
        ...

    def _get_attr_map(self, module_globals: Mapping[str, Any]) -> Optional[Dict[str, tuple[str, Optional[str]]]]:
        ...

    def _set_attr_map(self, module_globals: MutableMapping[str, Any], value: Dict[str, tuple[str, Optional[str]]]) -> None:
        ...

    def _get_eager_done(self, module_globals: Mapping[str, Any]) -> bool:
        ...

    def _set_eager_done(self, module_globals: MutableMapping[str, Any], value: bool) -> None:
        ...

    @staticmethod
    def _parse_all(path: Path) -> Optional[list[str]]:
        ...

    def _discover_modules(self, module_globals: MutableMapping[str, Any]) -> None:
        ...

    def resolve_extra(self, name: str, module_globals: MutableMapping[str, Any]) -> Any:
        ...

    def load_all(self, module_globals: MutableMapping[str, Any]) -> list[str]:
        ...

    def get_attr(self, name: str, module_globals: MutableMapping[str, Any]) -> Any:
        ...

    def iter_dir_names(self, module_globals: MutableMapping[str, Any]) -> list[str]:
        ...

class _UltraPlotModule(types.ModuleType):

    def __setattr__(self, name: str, value: Any) -> None:
        ...

def install_module_proxy(module: Optional[types.ModuleType]) -> None:
    """Prevent lazy-loading names from being clobbered by submodule imports."""
    ...
