# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Fast drop-in replacements for the [matplotlib.animation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.html) classes.

The classes here subclass their Matplotlib counterparts, so the constructor
signatures, the attributes, and the notebook representations are unchanged.
What differs is how frames are rendered:

* [save](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.animation.FuncAnimation.html#ultraplot.animation.FuncAnimation.save) bypasses the per-frame
  [savefig](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.savefig.html) call used by Matplotlib's writers and
  instead renders straight into the Agg buffer, piping raw ``RGBA`` bytes to
  the encoder. No PNG round-trip, no ``print_figure`` machinery.
* The expensive UltraPlot tight-layout pass runs once, for the first frame,
  rather than on every frame.
* Blitting is used while saving, not just interactively, so only the artists
  the update function returns are redrawn per frame.

Everything falls back to Matplotlib's own implementation when the fast path
cannot be used (custom writer instances, ``bbox_inches``, vector output, and
so on), so the output is never silently wrong.
"""
from _typeshed import Incomplete
import itertools
import os
import subprocess
from contextlib import ExitStack, contextmanager, suppress
from tempfile import TemporaryFile
from pathlib import Path
import matplotlib as mpl
import matplotlib.animation as manimation
import numpy as np
from matplotlib import cbook
__all__ = ['FuncAnimation', 'ArtistAnimation']
_FFMPEG_SUFFIXES = frozenset(('.mp4', '.m4v', '.mov', '.mkv', '.webm', '.avi', '.ogv', '.ogg') + ('.gif', '.webp', '.apng', '.avif'))
_PILLOW_SUFFIXES = frozenset(('.gif', '.webp', '.apng'))
_SUFFIX_CODECS = frozenset(('.gif', '.webp', '.apng', '.avif'))
_FAST_WRITERS = frozenset(('ffmpeg', 'pillow'))

def _suffix(filename: Incomplete) -> Incomplete:
    """Return the lowercase suffix of a path-like filename."""
    ...

class _RawWriter:
    """Base class for writers that consume raw ``RGBA`` frames.

Subclasses implement `write`, `_close`, and `_discard`. The output file is
deleted unless `finish` completed, so an animation that fails halfway
through never leaves a truncated movie that looks like a whole one."""

    def __init__(self, filename: Incomplete, fps: Incomplete) -> None:
        ...

    def setup(self, width: Incomplete, height: Incomplete) -> Incomplete:
        ...

    def write(self, buffer: Incomplete) -> Incomplete:
        ...

    def _close(self) -> Incomplete:
        ...

    def _discard(self) -> Incomplete:
        ...

    def finish(self) -> Incomplete:
        """Complete the file. Anything short of this counts as a failed save."""
        ...

    def cleanup(self) -> Incomplete:
        """Release resources, and remove the output of an unfinished save."""
        ...

class _RawFFMpegWriter(_RawWriter):
    """Pipe raw ``RGBA`` frames into ``ffmpeg`` with no intermediate encoding."""

    def __init__(self, filename: Incomplete, fps: Incomplete, *, codec: Incomplete=None, bitrate: Incomplete=None, extra_args: Incomplete=None, metadata: Incomplete=None) -> None:
        ...

    @staticmethod
    def available() -> Incomplete:
        """Return whether the configured ``ffmpeg`` binary can be executed."""
        ...

    def _command(self) -> Incomplete:
        ...

    def setup(self, width: Incomplete, height: Incomplete) -> Incomplete:
        ...

    def _stderr_text(self) -> Incomplete:
        ...

    def write(self, buffer: Incomplete) -> Incomplete:
        ...

    def _close(self) -> Incomplete:
        ...

    def _discard(self) -> Incomplete:
        ...

class _RawPillowWriter(_RawWriter):
    """Collect raw ``RGBA`` frames and write an animated image with Pillow."""

    def __init__(self, filename: Incomplete, fps: Incomplete) -> None:
        ...

    def write(self, buffer: Incomplete) -> Incomplete:
        ...

    def _close(self) -> Incomplete:
        ...

    def _discard(self) -> Incomplete:
        ...

class _FastSaveMixin:
    """The fast `save` path, shared by the animation classes.

Subclasses supply the three frame hooks below; everything else here is the
machinery that renders those frames into a movie file."""

    def _fast_frame_seq(self) -> Incomplete:
        ...

    def _fast_frame_artists(self, frame: Incomplete) -> Incomplete:
        ...

    def _fast_init_artists(self, frame: Incomplete) -> Incomplete:
        ...

    @contextmanager
    def _frozen_layout(self) -> Incomplete:
        """Run the UltraPlot layout solver once instead of once per frame.

UltraPlot recomputes tight layout whenever the figure is marked dirty.
During an animation the geometry must stay fixed anyway, or frames
would jitter, so the solver is switched off after the first draw. Yields
a function that marks the current layout as final."""
        ...

    @contextmanager
    def _animated_artists(self, artists: Incomplete=()) -> Incomplete:
        """Temporarily mark artists as animated so full draws skip them.

Yields a function that marks further artists, for update functions that
return a different set of artists as the animation goes on."""
        ...

    @contextmanager
    def _suspended_event_source(self) -> Incomplete:
        """Keep the interactive timer from starting on the frames drawn here.

[matplotlib.animation.Animation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.Animation.html) starts itself from the figure's first
``draw_event``. The draws below are for the movie file, not the screen."""
        ...

    @contextmanager
    def _suspended_figure_blitting(self) -> Incomplete:
        """Stand down the figure's own retained-draw machinery while saving.

[savefig](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.savefig) does the same before printing. A live
[_BlitManager](https://ultraplot.readthedocs.io/en/stable/api/ultraplot._animation._BlitManager.html) keeps its artists flagged animated
and repaints them from a ``draw_event`` handler, which would fight the
frames drawn here."""
        ...

    @contextmanager
    def _agg_canvas(self) -> Incomplete:
        """Ensure the figure has a canvas that can blit and expose an RGBA buffer."""
        ...

    def _resolve_writer(self, filename: Incomplete, writer: Incomplete, savefig_kwargs: Incomplete, extra_anim: Incomplete) -> Incomplete:
        """Return the name of the fast writer to use, or ``None`` for none.

The fast path must pick the same writer Matplotlib would, or the same
call would produce a differently encoded file than before."""
        ...

    def _make_raw_writer(self, filename: Incomplete, writer: Incomplete, fps: Incomplete, codec: Incomplete, bitrate: Incomplete, extra_args: Incomplete, metadata: Incomplete) -> Incomplete:
        """Return the raw-frame writer for the resolved writer name."""
        ...

    def _fast_save(self, filename: Incomplete, writer: Incomplete, fps: Incomplete, dpi: Incomplete, codec: Incomplete, bitrate: Incomplete, extra_args: Incomplete, metadata: Incomplete, progress_callback: Incomplete, blit: Incomplete) -> Incomplete:
        """Render every frame straight into the Agg buffer and pipe it out."""
        ...

    def save(self, filename: Incomplete, writer: Incomplete=None, fps: Incomplete=None, dpi: Incomplete=None, codec: Incomplete=None, bitrate: Incomplete=None, extra_args: Incomplete=None, metadata: Incomplete=None, extra_anim: Incomplete=None, savefig_kwargs: Incomplete=None, *, progress_callback: Incomplete=None, fast: Incomplete=None, blit: Incomplete=None) -> Incomplete:
        """Save the animation to a movie file.

Parameters
----------
- `filename`: The output file, e.g.
- `writer`: Same meaning as in [matplotlib.animation.Animation.save](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.Animation.save.html).
- `fps`: Frames per second.
- `dpi`: Resolution of the saved frames.
- `codec, bitrate, extra_args, metadata`: Passed to the encoder, as in Matplotlib.
- `extra_anim`: Additional animations to composite.
- `savefig_kwargs`: Extra [savefig](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.savefig.html) arguments.
- `progress_callback`: Called as ``progress_callback(current_frame, total_frames)``.
- `fast`: Whether to use the fast renderer.
- `blit`: Whether to blit while saving."""
        ...

class FuncAnimation(_FastSaveMixin, manimation.FuncAnimation):
    """A faster drop-in replacement for [matplotlib.animation.FuncAnimation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.FuncAnimation.html).

Parameters
----------
- `fig`: The figure to animate.
- `func`: The update function, called as ``func(frame, *fargs)``.
- `frames`: Source of frame data, as in Matplotlib.
- `init_func`: Function drawing the clear frame.
- `fargs`: Extra positional arguments for `func` and `init_func`.
- `save_count`: Number of frames to cache from a generator.
- `blit`: Whether to redraw only the artists returned by `func`.
- `cache_frame_data`: Whether to cache frame data, as in Matplotlib.
- `**kwargs`: Passed to [matplotlib.animation.TimedAnimation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.TimedAnimation.html), e.g.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.animation.FuncAnimation.html)"""

    def __init__(self, fig: Incomplete, func: Incomplete, frames: Incomplete=None, init_func: Incomplete=None, fargs: Incomplete=None, save_count: Incomplete=None, *, blit: Incomplete=True, **kwargs: Incomplete) -> None:
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    def _fast_frame_seq(self) -> Incomplete:
        ...

    def _fast_init_artists(self, frame: Incomplete) -> Incomplete:
        ...

    def _fast_frame_artists(self, frame: Incomplete) -> Incomplete:
        ...

class ArtistAnimation(_FastSaveMixin, manimation.ArtistAnimation):
    """A faster drop-in replacement for [matplotlib.animation.ArtistAnimation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.ArtistAnimation.html).

Frames are lists of artists that are made visible in turn. Saving uses the
same direct-to-buffer renderer as `FuncAnimation`.

Parameters
----------
fig : [Figure](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html)
    The figure to animate.
artists : list of list of [Artist](https://matplotlib.org/stable/api/_as_gen/matplotlib.artist.Artist.html)
    Each entry is the collection of artists making up one frame.
**kwargs
    Passed to [matplotlib.animation.TimedAnimation](https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.TimedAnimation.html).

See also
--------
matplotlib.animation.ArtistAnimation
ultraplot.animation.FuncAnimation"""

    def _fast_frame_seq(self) -> Incomplete:
        ...

    def _fast_init_artists(self, frame: Incomplete) -> Incomplete:
        ...

    def _fast_frame_artists(self, frame: Incomplete) -> Incomplete:
        ...
