# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
Fast drop-in replacements for the `matplotlib.animation` classes.

The classes here subclass their Matplotlib counterparts, so the constructor
signatures, the attributes, and the notebook representations are unchanged.
What differs is how frames are rendered:

* `~ultraplot.animation.FuncAnimation.save` bypasses the per-frame
  `~matplotlib.figure.Figure.savefig` call used by Matplotlib's writers and
  instead renders straight into the Agg buffer, piping raw ``RGBA`` bytes to
  the encoder. No PNG round-trip, no ``print_figure`` machinery.
* The expensive UltraPlot tight-layout pass runs once, for the first frame,
  rather than on every frame.
* Blitting is used while saving, not just interactively, so only the artists
  the update function returns are redrawn per frame.

Everything falls back to Matplotlib's own implementation when the fast path
cannot be used (custom writer instances, ``bbox_inches``, vector output, and
so on), so the output is never silently wrong.
"""
from _typeshed import Incomplete
import itertools
import os
import subprocess
from contextlib import ExitStack, contextmanager, suppress
from tempfile import TemporaryFile
from pathlib import Path
import matplotlib as mpl
import matplotlib.animation as manimation
import numpy as np
from matplotlib import cbook
__all__ = ['FuncAnimation', 'ArtistAnimation']
_FFMPEG_SUFFIXES = frozenset(('.mp4', '.m4v', '.mov', '.mkv', '.webm', '.avi', '.ogv', '.ogg') + ('.gif', '.webp', '.apng', '.avif'))
_PILLOW_SUFFIXES = frozenset(('.gif', '.webp', '.apng'))
_SUFFIX_CODECS = frozenset(('.gif', '.webp', '.apng', '.avif'))
_FAST_WRITERS = frozenset(('ffmpeg', 'pillow'))

def _suffix(filename: Incomplete) -> Incomplete:
    """Return the lowercase suffix of a path-like filename."""
    ...

class _RawWriter:
    """
    Base class for writers that consume raw ``RGBA`` frames.

    Subclasses implement `write`, `_close`, and `_discard`. The output file is
    deleted unless `finish` completed, so an animation that fails halfway
    through never leaves a truncated movie that looks like a whole one.
    """

    def __init__(self, filename: Incomplete, fps: Incomplete) -> None:
        ...

    def setup(self, width: Incomplete, height: Incomplete) -> Incomplete:
        ...

    def write(self, buffer: Incomplete) -> Incomplete:
        ...

    def _close(self) -> Incomplete:
        ...

    def _discard(self) -> Incomplete:
        ...

    def finish(self) -> Incomplete:
        """Complete the file. Anything short of this counts as a failed save."""
        ...

    def cleanup(self) -> Incomplete:
        """Release resources, and remove the output of an unfinished save."""
        ...

class _RawFFMpegWriter(_RawWriter):
    """
    Pipe raw ``RGBA`` frames into ``ffmpeg`` with no intermediate encoding.
    """

    def __init__(self, filename: Incomplete, fps: Incomplete, *, codec: Incomplete=None, bitrate: Incomplete=None, extra_args: Incomplete=None, metadata: Incomplete=None) -> None:
        ...

    @staticmethod
    def available() -> Incomplete:
        """Return whether the configured ``ffmpeg`` binary can be executed."""
        ...

    def _command(self) -> Incomplete:
        ...

    def setup(self, width: Incomplete, height: Incomplete) -> Incomplete:
        ...

    def _stderr_text(self) -> Incomplete:
        ...

    def write(self, buffer: Incomplete) -> Incomplete:
        ...

    def _close(self) -> Incomplete:
        ...

    def _discard(self) -> Incomplete:
        ...

class _RawPillowWriter(_RawWriter):
    """
    Collect raw ``RGBA`` frames and write an animated image with Pillow.
    """

    def __init__(self, filename: Incomplete, fps: Incomplete) -> None:
        ...

    def write(self, buffer: Incomplete) -> Incomplete:
        ...

    def _close(self) -> Incomplete:
        ...

    def _discard(self) -> Incomplete:
        ...

class _FastSaveMixin:
    """
    The fast `save` path, shared by the animation classes.

    Subclasses supply the three frame hooks below; everything else here is the
    machinery that renders those frames into a movie file.
    """

    def _fast_frame_seq(self) -> Incomplete:
        ...

    def _fast_frame_artists(self, frame: Incomplete) -> Incomplete:
        ...

    def _fast_init_artists(self, frame: Incomplete) -> Incomplete:
        ...

    @contextmanager
    def _frozen_layout(self) -> Incomplete:
        """Run the UltraPlot layout solver once instead of once per frame.

UltraPlot recomputes tight layout whenever the figure is marked dirty.
During an animation the geometry must stay fixed anyway, or frames
would jitter, so the solver is switched off after the first draw. Yields
a function that marks the current layout as final."""
        ...

    @contextmanager
    def _animated_artists(self, artists: Incomplete=()) -> Incomplete:
        """Temporarily mark artists as animated so full draws skip them.

Yields a function that marks further artists, for update functions that
return a different set of artists as the animation goes on."""
        ...

    @contextmanager
    def _suspended_event_source(self) -> Incomplete:
        """Keep the interactive timer from starting on the frames drawn here.

`matplotlib.animation.Animation` starts itself from the figure's first
``draw_event``. The draws below are for the movie file, not the screen."""
        ...

    @contextmanager
    def _suspended_figure_blitting(self) -> Incomplete:
        """Stand down the figure's own retained-draw machinery while saving.

`~ultraplot.figure.Figure.savefig` does the same before printing. A live
`~ultraplot._animation._BlitManager` keeps its artists flagged animated
and repaints them from a ``draw_event`` handler, which would fight the
frames drawn here."""
        ...

    @contextmanager
    def _agg_canvas(self) -> Incomplete:
        """Ensure the figure has a canvas that can blit and expose an RGBA buffer."""
        ...

    def _resolve_writer(self, filename: Incomplete, writer: Incomplete, savefig_kwargs: Incomplete, extra_anim: Incomplete) -> Incomplete:
        """Return the name of the fast writer to use, or ``None`` for none.

The fast path must pick the same writer Matplotlib would, or the same
call would produce a differently encoded file than before."""
        ...

    def _make_raw_writer(self, filename: Incomplete, writer: Incomplete, fps: Incomplete, codec: Incomplete, bitrate: Incomplete, extra_args: Incomplete, metadata: Incomplete) -> Incomplete:
        """Return the raw-frame writer for the resolved writer name."""
        ...

    def _fast_save(self, filename: Incomplete, writer: Incomplete, fps: Incomplete, dpi: Incomplete, codec: Incomplete, bitrate: Incomplete, extra_args: Incomplete, metadata: Incomplete, progress_callback: Incomplete, blit: Incomplete) -> Incomplete:
        """Render every frame straight into the Agg buffer and pipe it out."""
        ...

    def save(self, filename: Incomplete, writer: Incomplete=None, fps: Incomplete=None, dpi: Incomplete=None, codec: Incomplete=None, bitrate: Incomplete=None, extra_args: Incomplete=None, metadata: Incomplete=None, extra_anim: Incomplete=None, savefig_kwargs: Incomplete=None, *, progress_callback: Incomplete=None, fast: Incomplete=None, blit: Incomplete=None) -> Incomplete:
        """Save the animation to a movie file.

Parameters
----------
filename : path-like
    The output file, e.g. ``'movie.mp4'`` or ``'movie.gif'``.
writer : str or `~matplotlib.animation.AbstractMovieWriter`, optional
    Same meaning as in `matplotlib.animation.Animation.save`. Passing a
    writer *instance*, or a writer the fast path does not implement,
    transparently falls back to Matplotlib's implementation.
fps : int, optional
    Frames per second. Defaults to the animation interval.
dpi : float, optional
    Resolution of the saved frames. Unlike Matplotlib, which uses
    :rc:`savefig.dpi`, this defaults to the figure's own dpi. UltraPlot
    sets ``savefig.dpi`` to 1000 for publication-quality stills, which
    for a movie means hundredfold larger frames and a hundredfold
    slower encode.
codec, bitrate, extra_args, metadata : optional
    Passed to the encoder, as in Matplotlib.
extra_anim : list, optional
    Additional animations to composite. Forces the Matplotlib path.
savefig_kwargs : dict, optional
    Extra `~matplotlib.figure.Figure.savefig` arguments. Any value here
    forces the Matplotlib path, since the fast path skips ``savefig``.
progress_callback : callable, optional
    Called as ``progress_callback(current_frame, total_frames)``.
fast : bool, optional
    Whether to use the fast renderer. The default, ``None``, uses it
    whenever it can reproduce the requested output exactly. Passing
    ``True`` raises if the fast path is unavailable.
blit : bool, optional
    Whether to blit while saving. Defaults to the animation's own
    ``blit`` setting. Blitting only redraws the artists returned by the
    update function, so anything else changed per frame (titles, ticks,
    axes limits) will not appear. Pass ``False`` to redraw everything.

Other Parameters
----------------
See `matplotlib.animation.Animation.save`.

See also
--------
matplotlib.animation.Animation.save"""
        ...

class FuncAnimation(_FastSaveMixin, manimation.FuncAnimation):
    """
    A faster drop-in replacement for `matplotlib.animation.FuncAnimation`.

    The signature matches Matplotlib's, with two differences: `blit` defaults
    to ``True`` instead of ``False``, and `freeze_layout` is added. Saving
    renders frames directly into the Agg buffer instead of calling
    `~matplotlib.figure.Figure.savefig` once per frame, which removes the
    per-frame PNG round-trip and the repeated UltraPlot tight-layout pass.

    Parameters
    ----------
    fig : `~ultraplot.figure.Figure`
        The figure to animate.
    func : callable
        The update function, called as ``func(frame, *fargs)``. It should
        return an iterable of the artists it modified. This is required when
        `blit` is ``True``, and lets the fast path skip untouched artists.
    frames : int, iterable, generator, or None, optional
        Source of frame data, as in Matplotlib.
    init_func : callable, optional
        Function drawing the clear frame. Should return the animated artists.
    fargs : tuple, optional
        Extra positional arguments for `func` and `init_func`.
    save_count : int, optional
        Number of frames to cache from a generator.
    blit : bool, default: True
        Whether to redraw only the artists returned by `func`. This is the main
        source of the speedup, but it means changes to artists that are *not*
        returned, such as titles or tick labels, will not show up. Pass
        ``False`` to redraw the whole figure each frame, which is still faster
        than Matplotlib because the layout solver is frozen.
    cache_frame_data : bool, default: True
        Whether to cache frame data, as in Matplotlib.
    **kwargs
        Passed to `matplotlib.animation.TimedAnimation`, e.g. `interval`,
        `repeat`, and `repeat_delay`.

    Examples
    --------
    >>> import ultraplot as uplt
    >>> import numpy as np
    >>> fig, ax = uplt.subplots()
    >>> x = np.linspace(0, 2 * np.pi, 200)
    >>> (line,) = ax.plot(x, np.sin(x))
    >>> def update(frame):
    ...     line.set_ydata(np.sin(x + frame / 10))
    ...     return (line,)
    ...
    >>> ani = uplt.FuncAnimation(fig, update, frames=100)
    >>> ani.save('waves.mp4')

    See also
    --------
    matplotlib.animation.FuncAnimation
    ultraplot.animation.ArtistAnimation
    """

    def __init__(self, fig: Incomplete, func: Incomplete, frames: Incomplete=None, init_func: Incomplete=None, fargs: Incomplete=None, save_count: Incomplete=None, *, blit: Incomplete=True, **kwargs: Incomplete) -> None:
        ...

    def _fast_frame_seq(self) -> Incomplete:
        ...

    def _fast_init_artists(self, frame: Incomplete) -> Incomplete:
        ...

    def _fast_frame_artists(self, frame: Incomplete) -> Incomplete:
        ...

class ArtistAnimation(_FastSaveMixin, manimation.ArtistAnimation):
    """
    A faster drop-in replacement for `matplotlib.animation.ArtistAnimation`.

    Frames are lists of artists that are made visible in turn. Saving uses the
    same direct-to-buffer renderer as `FuncAnimation`.

    Parameters
    ----------
    fig : `~ultraplot.figure.Figure`
        The figure to animate.
    artists : list of list of `~matplotlib.artist.Artist`
        Each entry is the collection of artists making up one frame.
    **kwargs
        Passed to `matplotlib.animation.TimedAnimation`.

    See also
    --------
    matplotlib.animation.ArtistAnimation
    ultraplot.animation.FuncAnimation
    """

    def _fast_frame_seq(self) -> Incomplete:
        ...

    def _fast_init_artists(self, frame: Incomplete) -> Incomplete:
        ...

    def _fast_frame_artists(self, frame: Incomplete) -> Incomplete:
        ...
