# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
The constructor functions used to build class instances from simple shorthand arguments.
"""
from _typeshed import Incomplete
import copy
import os
import re
from functools import partial
from numbers import Number
from typing import Callable, Iterator, TypeVar
import cycler
import matplotlib.colors as mcolors
import matplotlib.dates as mdates
import matplotlib.font_manager as mfonts
import matplotlib.projections.polar as mpolar
import matplotlib.scale as mscale
import matplotlib.ticker as mticker
from matplotlib.ft2font import FT2Font
import numpy as np
from . import colors as pcolors
from . import proj as pproj
from . import scale as pscale
from . import ticker as pticker
from .config import rc
from .internals import _not_none, _pop_props, _version_cartopy, _version_mpl, ic, warnings
from .utils import to_hex, to_rgba
try:
    from mpl_toolkits.basemap import Basemap
except ImportError:
    Basemap = object
try:
    import cartopy.crs as ccrs
    from cartopy.crs import Projection
except ModuleNotFoundError:
    ccrs = None
    Projection = object
__all__ = ['Proj', 'Locator', 'Formatter', 'Scale', 'Colormap', 'Norm', 'Cycle']
DEFAULT_CYCLE_SAMPLES = 10
DEFAULT_CYCLE_LUMINANCE = 90
_RegistryValue = TypeVar('_RegistryValue')

class _RefreshingRegistry(dict[str, _RegistryValue]):
    """Dictionary-like registry that rebuilds itself before reads.

This keeps constructor registries aligned with modules that may be reloaded
in-place during tests or interactive use."""

    def __init__(self, factory: Callable[[], dict[str, _RegistryValue]]) -> None:
        ...

    def _refresh(self) -> None:
        ...

    def __contains__(self, key: object) -> bool:
        ...

    def __getitem__(self, key: str) -> _RegistryValue:
        ...

    def __iter__(self) -> Iterator[str]:
        ...

    def __len__(self) -> int:
        ...

    def get(self, key: str, default: _RegistryValue | None=None) -> _RegistryValue | None:
        ...

    def items(self) -> Incomplete:
        ...

    def keys(self) -> Incomplete:
        ...

    def values(self) -> Incomplete:
        ...

    def copy(self) -> dict[str, _RegistryValue]:
        ...

def _build_norm_registry() -> dict[str, type[mcolors.Normalize]]:
    ...

def _build_locator_registry() -> dict[str, object]:
    ...

def _get_dms_symbol_kwargs() -> dict[str, str]:
    """Return ASCII DMS symbols when the active font lacks prime glyphs."""
    ...

def _build_formatter_registry() -> dict[str, object]:
    ...
NORMS = _RefreshingRegistry(_build_norm_registry)
LOCATORS = _RefreshingRegistry(_build_locator_registry)
FORMATTERS = _RefreshingRegistry(_build_formatter_registry)
SCALES = mscale._scale_mapping
SCALES_PRESETS = {'quadratic': ('power', 2), 'cubic': ('power', 3), 'quartic': ('power', 4), 'height': ('exp', np.e, -1 / 7, 1013.25, True), 'pressure': ('exp', np.e, -1 / 7, 1013.25, False), 'db': ('exp', 10, 1, 0.1, True), 'idb': ('exp', 10, 1, 0.1, False), 'np': ('exp', np.e, 1, 1, True), 'inp': ('exp', np.e, 1, 1, False)}
PROJ_DEFAULTS = {'geos': {'lon_0': 0}, 'eck4': {'lon_0': 0}, 'moll': {'lon_0': 0}, 'hammer': {'lon_0': 0}, 'kav7': {'lon_0': 0}, 'sinu': {'lon_0': 0}, 'vandg': {'lon_0': 0}, 'mbtfpq': {'lon_0': 0}, 'robin': {'lon_0': 0}, 'ortho': {'lon_0': 0, 'lat_0': 0}, 'nsper': {'lon_0': 0, 'lat_0': 0}, 'aea': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'eqdc': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'cass': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'gnom': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'poly': {'lon_0': 0, 'lat_0': 0, 'width': 10000000.0, 'height': 10000000.0}, 'npaeqd': {'lon_0': 0, 'boundinglat': 10}, 'nplaea': {'lon_0': 0, 'boundinglat': 10}, 'npstere': {'lon_0': 0, 'boundinglat': 10}, 'spaeqd': {'lon_0': 0, 'boundinglat': -10}, 'splaea': {'lon_0': 0, 'boundinglat': -10}, 'spstere': {'lon_0': 0, 'boundinglat': -10}, 'lcc': {'lon_0': 0, 'lat_0': 40, 'lat_1': 35, 'lat_2': 45, 'width': 20000000.0, 'height': 15000000.0}, 'tmerc': {'lon_0': 0, 'lat_0': 0, 'width': 10000000.0, 'height': 10000000.0}, 'merc': {'llcrnrlat': -80, 'urcrnrlat': 84, 'llcrnrlon': -180, 'urcrnrlon': 180}, 'omerc': {'lat_0': 0, 'lon_0': 0, 'lat_1': -10, 'lat_2': 10, 'lon_1': 0, 'lon_2': 0, 'width': 10000000.0, 'height': 10000000.0}}
if ccrs is None:
    PROJS = {}
else:
    PROJS = {'aitoff': pproj.Aitoff, 'hammer': pproj.Hammer, 'kav7': pproj.KavrayskiyVII, 'wintri': pproj.WinkelTripel, 'npgnom': pproj.NorthPolarGnomonic, 'spgnom': pproj.SouthPolarGnomonic, 'npaeqd': pproj.NorthPolarAzimuthalEquidistant, 'spaeqd': pproj.SouthPolarAzimuthalEquidistant, 'nplaea': pproj.NorthPolarLambertAzimuthalEqualArea, 'splaea': pproj.SouthPolarLambertAzimuthalEqualArea}
    PROJS_MISSING = {'aea': 'AlbersEqualArea', 'aeqd': 'AzimuthalEquidistant', 'cyl': 'PlateCarree', 'eck1': 'EckertI', 'eck2': 'EckertII', 'eck3': 'EckertIII', 'eck4': 'EckertIV', 'eck5': 'EckertV', 'eck6': 'EckertVI', 'eqc': 'PlateCarree', 'eqdc': 'EquidistantConic', 'eqearth': 'EqualEarth', 'euro': 'EuroPP', 'geos': 'Geostationary', 'gnom': 'Gnomonic', 'igh': 'InterruptedGoodeHomolosine', 'laea': 'LambertAzimuthalEqualArea', 'lcc': 'LambertConformal', 'lcyl': 'LambertCylindrical', 'merc': 'Mercator', 'mill': 'Miller', 'moll': 'Mollweide', 'npstere': 'NorthPolarStereo', 'nsper': 'NearsidePerspective', 'ortho': 'Orthographic', 'osgb': 'OSGB', 'osni': 'OSNI', 'pcarree': 'PlateCarree', 'robin': 'Robinson', 'rotpole': 'RotatedPole', 'sinu': 'Sinusoidal', 'spstere': 'SouthPolarStereo', 'stere': 'Stereographic', 'tmerc': 'TransverseMercator', 'utm': 'UTM'}
    PROJS_TABLE = ...
FEATURES_CARTOPY = {'land': ('physical', 'land'), 'ocean': ('physical', 'ocean'), 'lakes': ('physical', 'lakes'), 'coast': ('physical', 'coastline'), 'rivers': ('physical', 'rivers_lake_centerlines'), 'borders': ('cultural', 'admin_0_boundary_lines_land'), 'innerborders': ('cultural', 'admin_1_states_provinces_lakes')}
FEATURES_BASEMAP = {'land': 'fillcontinents', 'coast': 'drawcoastlines', 'rivers': 'drawrivers', 'borders': 'drawcountries', 'innerborders': 'drawstates'}
RESOS_CARTOPY = {'lo': '110m', 'med': '50m', 'hi': '10m', 'x-hi': '10m', 'xx-hi': '10m'}
RESOS_BASEMAP = {'lo': 'c', 'med': 'l', 'hi': 'i', 'x-hi': 'h', 'xx-hi': 'f'}

def _modify_colormap(cmap: Incomplete, *, cut: Incomplete, left: Incomplete, right: Incomplete, reverse: Incomplete, shift: Incomplete, alpha: Incomplete, samples: Incomplete) -> Incomplete:
    """Modify colormap using a variety of methods."""
    ...

def Colormap(*args: Incomplete, name: Incomplete=None, listmode: Incomplete='perceptual', filemode: Incomplete='continuous', discrete: Incomplete=False, cycle: Incomplete=None, save: Incomplete=False, save_kw: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
    """Generate, retrieve, modify, and/or merge instances of [PerceptualColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.PerceptualColormap.html), [ContinuousColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.ContinuousColormap.html), and [DiscreteColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.DiscreteColormap.html).

Parameters
----------
- `*args`: Positional arguments that individually generate colormaps.
- `name`: Name under which the final colormap is registered.
- `filemode`: Controls how colormaps are generated when you input list(s) of colors.
- `listmode`: Controls how colormaps are generated when you input sequence(s) of colors.
- `samples`: For [ContinuousColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.ContinuousColormap.html)\\ s, this is used to generate [DiscreteColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.DiscreteColormap.html)\\ s with…
- `discrete`: If ``True``, when the final colormap is a [DiscreteColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.DiscreteColormap.html), we leave it alone, but when it is a [ContinuousColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.ContinuousColormap.html), we always…
- `left, right`: Truncate the left or right edges of the colormap.
- `cut`: Cut out the center of the colormap.
- `reverse`: Reverse the colormap.
- `shift`: Cyclically shift the colormap.
- `a`: Shorthand for `alpha`.
- `alpha`: The opacity of the colormap or the opacity gradation.
- `hue, saturation, luminance`: The channel value(s) used to generate colormaps with [from_hsl](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.PerceptualColormap.html#ultraplot.colors.PerceptualColormap.from_hsl) and [from_color](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.PerceptualColormap.html#ultraplot.colors.PerceptualColormap.from_color).
- `chroma`: Alias for `saturation`.
- `cycle`: The registered cycle name used to interpret color strings like ``'C0'`` and ``'C2'``.
- `save`: Whether to call the colormap/color cycle save method, i.e.
- `save_kw`: Ignored if `save` is ``False``.
- `**kwargs`: Passed to [ultraplot.colors.ContinuousColormap.copy](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.ContinuousColormap.html#ultraplot.colors.ContinuousColormap.copy), [ultraplot.colors.PerceptualColormap.copy](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.PerceptualColormap.html#ultraplot.colors.PerceptualColormap.copy), or [ultraplot.colors.DiscreteColormap.copy](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.DiscreteColormap.html#ultraplot.colors.DiscreteColormap.copy).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Colormap.html)"""
    ...

class Cycle(cycler.Cycler):
    """Generate and merge `~cycler.Cycler` instances in a variety of ways.

Parameters
----------
- `*args`: Positional arguments control the *colors* in the `~cycler.Cycler` object.
- `N`: Shorthand for `samples`.
- `samples`: For [DiscreteColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.DiscreteColormap.html)\\ s, this is the number of colors to select.
- `c, color, colors`: A sequence of colors passed as keyword arguments.
- `linewidth, linestyle, dashes, alpha, marker, markersize, markeredgewidth, markeredgecolor, markerfacecolor`: Lists of [Line2D](https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html) properties that can be added to the `~cycler.Cycler` instance.
- `**kwargs`: If the input is not already a `~cycler.Cycler` instance, these are passed to `Colormap` and used to build the [DiscreteColormap](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.colors.DiscreteColormap.html) from which the cycler will…

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Cycle.html)"""

    def __init__(self, *args: Incomplete, N: Incomplete=None, samples: Incomplete=None, name: Incomplete=None, **kwargs: Incomplete) -> None:
        ...

    def _parse_basic_properties(self, kwargs: Incomplete) -> Incomplete:
        """Parse and validate basic properties from kwargs."""
        ...

    def _handle_empty_args(self, props: Incomplete, kwargs: Incomplete) -> None:
        """Handle case when no positional arguments are provided."""
        ...

    def _handle_cycler_args(self, args: Incomplete, props: Incomplete, kwargs: Incomplete) -> None:
        """Handle case when arguments are cycler objects."""
        ...

    def _handle_colormap_args(self, args: Incomplete, props: Incomplete, kwargs: Incomplete, samples: Incomplete, name: Incomplete) -> None:
        """Handle case when arguments are for creating a colormap."""
        ...

    def _create_colormap(self, args: Incomplete, name: Incomplete, samples: Incomplete, kwargs: Incomplete) -> Incomplete:
        """Create a colormap from the given arguments."""
        ...

    def _is_all_cyclers(self, args: Incomplete) -> bool:
        """Check if all arguments are Cycler objects."""
        ...

    def _build_cycler(self, dicts: Incomplete) -> None:
        """Build the final cycler from the given dictionaries."""
        ...

    def __eq__(self, other: Incomplete) -> bool:
        ...

    def get_next(self) -> Incomplete:
        ...

def Norm(norm: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
    """Return an arbitrary [Normalize](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Normalize.html) instance.

Parameters
----------
- `norm`: The normalizer specification.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Norm.html)"""
    ...

def Locator(locator: Incomplete, *args: Incomplete, discrete: Incomplete=False, **kwargs: Incomplete) -> Incomplete:
    """Return a [Locator](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Locator.html) instance.

Parameters
----------
- `locator`: The locator specification, interpreted as follows: * If a [Locator](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Locator.html) instance already, a `copy.copy` of the instance is returned.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Locator.html)"""
    ...

def Formatter(formatter: Incomplete, *args: Incomplete, date: Incomplete=False, index: Incomplete=False, **kwargs: Incomplete) -> Incomplete:
    """Return a [Formatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Formatter.html) instance.

Parameters
----------
- `formatter`: The formatter specification, interpreted as follows: * If a [Formatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Formatter.html) instance already, a `copy.copy` of the instance is returned.
- `date`: Toggles the behavior when `formatter` contains a ``'%%'`` sign (see above).
- `index`: Controls the behavior when `formatter` is a sequence of strings (see above).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Formatter.html)"""
    ...

def Scale(scale: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
    """Return a [ScaleBase](https://matplotlib.org/stable/api/_as_gen/matplotlib.scale.ScaleBase.html) instance.

Parameters
----------
- `scale`: The axis scale specification.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Scale.html)"""
    ...

def _warn_basemap_deprecated() -> Incomplete:
    """Warn that the basemap backend is deprecated."""
    ...

def Proj(name: Incomplete, backend: Incomplete=None, lon0: Incomplete=None, lon_0: Incomplete=None, lat0: Incomplete=None, lat_0: Incomplete=None, lonlim: Incomplete=None, latlim: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
    """Return a `cartopy.crs.Projection` or `~mpl_toolkits.basemap.Basemap` instance.

Parameters
----------
- `name`: The projection name or projection class instance.
- `backend`: Whether to return a cartopy `~cartopy.crs.Projection` instance or a basemap `~mpl_toolkits.basemap.Basemap` instance.
- `lon0, lat0`: The central projection longitude and latitude.
- `lon_0, lat_0`: Aliases for `lon0`, `lat0`.
- `lonlim`: The longitude limits.
- `latlim`: The latitude limits.
- `**kwargs`: Passed to the cartopy `~cartopy.crs.Projection` or basemap `~mpl_toolkits.basemap.Basemap` class.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.constructor.Proj.html)"""
    ...
