# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
The constructor functions used to build class instances from simple shorthand arguments.
"""
from _typeshed import Incomplete
import copy
import os
import re
from functools import partial
from numbers import Number
from typing import Callable, Iterator, TypeVar
import cycler
import matplotlib.colors as mcolors
import matplotlib.dates as mdates
import matplotlib.font_manager as mfonts
import matplotlib.projections.polar as mpolar
import matplotlib.scale as mscale
import matplotlib.ticker as mticker
from matplotlib.ft2font import FT2Font
import numpy as np
from . import colors as pcolors
from . import proj as pproj
from . import scale as pscale
from . import ticker as pticker
from .config import rc
from .internals import _not_none, _pop_props, _version_cartopy, _version_mpl, ic, warnings
from .utils import to_hex, to_rgba
try:
    from mpl_toolkits.basemap import Basemap
except ImportError:
    Basemap = object
try:
    import cartopy.crs as ccrs
    from cartopy.crs import Projection
except ModuleNotFoundError:
    ccrs = None
    Projection = object
__all__ = ['Proj', 'Locator', 'Formatter', 'Scale', 'Colormap', 'Norm', 'Cycle']
DEFAULT_CYCLE_SAMPLES = 10
DEFAULT_CYCLE_LUMINANCE = 90
_RegistryValue = TypeVar('_RegistryValue')

class _RefreshingRegistry(dict[str, _RegistryValue]):
    """
    Dictionary-like registry that rebuilds itself before reads.

    This keeps constructor registries aligned with modules that may be reloaded
    in-place during tests or interactive use.
    """

    def __init__(self, factory: Callable[[], dict[str, _RegistryValue]]) -> None:
        ...

    def _refresh(self) -> None:
        ...

    def __contains__(self, key: object) -> bool:
        ...

    def __getitem__(self, key: str) -> _RegistryValue:
        ...

    def __iter__(self) -> Iterator[str]:
        ...

    def __len__(self) -> int:
        ...

    def get(self, key: str, default: _RegistryValue | None=None) -> _RegistryValue | None:
        ...

    def items(self) -> Incomplete:
        ...

    def keys(self) -> Incomplete:
        ...

    def values(self) -> Incomplete:
        ...

    def copy(self) -> dict[str, _RegistryValue]:
        ...

def _build_norm_registry() -> dict[str, type[mcolors.Normalize]]:
    ...

def _build_locator_registry() -> dict[str, object]:
    ...

def _get_dms_symbol_kwargs() -> dict[str, str]:
    """Return ASCII DMS symbols when the active font lacks prime glyphs."""
    ...

def _build_formatter_registry() -> dict[str, object]:
    ...
NORMS = _RefreshingRegistry(_build_norm_registry)
LOCATORS = _RefreshingRegistry(_build_locator_registry)
FORMATTERS = _RefreshingRegistry(_build_formatter_registry)
SCALES = mscale._scale_mapping
SCALES_PRESETS = {'quadratic': ('power', 2), 'cubic': ('power', 3), 'quartic': ('power', 4), 'height': ('exp', np.e, -1 / 7, 1013.25, True), 'pressure': ('exp', np.e, -1 / 7, 1013.25, False), 'db': ('exp', 10, 1, 0.1, True), 'idb': ('exp', 10, 1, 0.1, False), 'np': ('exp', np.e, 1, 1, True), 'inp': ('exp', np.e, 1, 1, False)}
PROJ_DEFAULTS = {'geos': {'lon_0': 0}, 'eck4': {'lon_0': 0}, 'moll': {'lon_0': 0}, 'hammer': {'lon_0': 0}, 'kav7': {'lon_0': 0}, 'sinu': {'lon_0': 0}, 'vandg': {'lon_0': 0}, 'mbtfpq': {'lon_0': 0}, 'robin': {'lon_0': 0}, 'ortho': {'lon_0': 0, 'lat_0': 0}, 'nsper': {'lon_0': 0, 'lat_0': 0}, 'aea': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'eqdc': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'cass': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'gnom': {'lon_0': 0, 'lat_0': 90, 'width': 15000000.0, 'height': 15000000.0}, 'poly': {'lon_0': 0, 'lat_0': 0, 'width': 10000000.0, 'height': 10000000.0}, 'npaeqd': {'lon_0': 0, 'boundinglat': 10}, 'nplaea': {'lon_0': 0, 'boundinglat': 10}, 'npstere': {'lon_0': 0, 'boundinglat': 10}, 'spaeqd': {'lon_0': 0, 'boundinglat': -10}, 'splaea': {'lon_0': 0, 'boundinglat': -10}, 'spstere': {'lon_0': 0, 'boundinglat': -10}, 'lcc': {'lon_0': 0, 'lat_0': 40, 'lat_1': 35, 'lat_2': 45, 'width': 20000000.0, 'height': 15000000.0}, 'tmerc': {'lon_0': 0, 'lat_0': 0, 'width': 10000000.0, 'height': 10000000.0}, 'merc': {'llcrnrlat': -80, 'urcrnrlat': 84, 'llcrnrlon': -180, 'urcrnrlon': 180}, 'omerc': {'lat_0': 0, 'lon_0': 0, 'lat_1': -10, 'lat_2': 10, 'lon_1': 0, 'lon_2': 0, 'width': 10000000.0, 'height': 10000000.0}}
if ccrs is None:
    PROJS = {}
else:
    PROJS = {'aitoff': pproj.Aitoff, 'hammer': pproj.Hammer, 'kav7': pproj.KavrayskiyVII, 'wintri': pproj.WinkelTripel, 'npgnom': pproj.NorthPolarGnomonic, 'spgnom': pproj.SouthPolarGnomonic, 'npaeqd': pproj.NorthPolarAzimuthalEquidistant, 'spaeqd': pproj.SouthPolarAzimuthalEquidistant, 'nplaea': pproj.NorthPolarLambertAzimuthalEqualArea, 'splaea': pproj.SouthPolarLambertAzimuthalEqualArea}
    PROJS_MISSING = {'aea': 'AlbersEqualArea', 'aeqd': 'AzimuthalEquidistant', 'cyl': 'PlateCarree', 'eck1': 'EckertI', 'eck2': 'EckertII', 'eck3': 'EckertIII', 'eck4': 'EckertIV', 'eck5': 'EckertV', 'eck6': 'EckertVI', 'eqc': 'PlateCarree', 'eqdc': 'EquidistantConic', 'eqearth': 'EqualEarth', 'euro': 'EuroPP', 'geos': 'Geostationary', 'gnom': 'Gnomonic', 'igh': 'InterruptedGoodeHomolosine', 'laea': 'LambertAzimuthalEqualArea', 'lcc': 'LambertConformal', 'lcyl': 'LambertCylindrical', 'merc': 'Mercator', 'mill': 'Miller', 'moll': 'Mollweide', 'npstere': 'NorthPolarStereo', 'nsper': 'NearsidePerspective', 'ortho': 'Orthographic', 'osgb': 'OSGB', 'osni': 'OSNI', 'pcarree': 'PlateCarree', 'robin': 'Robinson', 'rotpole': 'RotatedPole', 'sinu': 'Sinusoidal', 'spstere': 'SouthPolarStereo', 'stere': 'Stereographic', 'tmerc': 'TransverseMercator', 'utm': 'UTM'}
    PROJS_TABLE = ...
FEATURES_CARTOPY = {'land': ('physical', 'land'), 'ocean': ('physical', 'ocean'), 'lakes': ('physical', 'lakes'), 'coast': ('physical', 'coastline'), 'rivers': ('physical', 'rivers_lake_centerlines'), 'borders': ('cultural', 'admin_0_boundary_lines_land'), 'innerborders': ('cultural', 'admin_1_states_provinces_lakes')}
FEATURES_BASEMAP = {'land': 'fillcontinents', 'coast': 'drawcoastlines', 'rivers': 'drawrivers', 'borders': 'drawcountries', 'innerborders': 'drawstates'}
RESOS_CARTOPY = {'lo': '110m', 'med': '50m', 'hi': '10m', 'x-hi': '10m', 'xx-hi': '10m'}
RESOS_BASEMAP = {'lo': 'c', 'med': 'l', 'hi': 'i', 'x-hi': 'h', 'xx-hi': 'f'}

def _modify_colormap(cmap: Incomplete, *, cut: Incomplete, left: Incomplete, right: Incomplete, reverse: Incomplete, shift: Incomplete, alpha: Incomplete, samples: Incomplete) -> Incomplete:
    """Modify colormap using a variety of methods."""
    ...

def Colormap(*args: Incomplete, name: Incomplete=None, listmode: Incomplete='perceptual', filemode: Incomplete='continuous', discrete: Incomplete=False, cycle: Incomplete=None, save: Incomplete=False, save_kw: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
    """Generate, retrieve, modify, and/or merge instances of
:class:`~ultraplot.colors.PerceptualColormap`,
:class:`~ultraplot.colors.ContinuousColormap`, and
:class:`~ultraplot.colors.DiscreteColormap`.

Parameters
----------
*args : colormap-spec
    Positional arguments that individually generate colormaps. If more
    than one argument is passed, the resulting colormaps are *merged* with
    `~ultraplot.colors.ContinuousColormap.append`
    or `~ultraplot.colors.DiscreteColormap.append`.
    The arguments are interpreted as follows:

    * If a registered colormap name, that colormap instance is looked up.
      If colormap instance is a native matplotlib colormap class, it is
      converted to a ultraplot colormap class.
    * If a filename string with valid extension, the colormap data
      is loaded with `ultraplot.colors.ContinuousColormap.from_file` or
      `ultraplot.colors.DiscreteColormap.from_file` depending on the value of
      `filemode` (see below). Default behavior is to load a
      :class:`~ultraplot.colors.ContinuousColormap`.
    * If RGB tuple or color string, a :class:`~ultraplot.colors.PerceptualColormap`
      is generated with `~ultraplot.colors.PerceptualColormap.from_color`.
      If the string ends in ``'_r'``, the monochromatic map will be
      *reversed*, i.e. will go from dark to light instead of light to dark.
    * If sequence of RGB tuples or color strings, a
      :class:`~ultraplot.colors.DiscreteColormap`, :class:`~ultraplot.colors.PerceptualColormap`,
      or :class:`~ultraplot.colors.ContinuousColormap` is generated depending on
      the value of `listmode` (see below). Default behavior is to generate a
      :class:`~ultraplot.colors.PerceptualColormap`.
    * If dictionary, a :class:`~ultraplot.colors.PerceptualColormap` is
      generated with `~ultraplot.colors.PerceptualColormap.from_hsl`.
      The dictionary should contain the keys ``'hue'``, ``'saturation'``,
      ``'luminance'``, and optionally ``'alpha'``, or their aliases (see below).

name : str, optional
    Name under which the final colormap is registered. It can
    then be reused by passing ``cmap='name'`` to plotting
    functions. Names with leading underscores are ignored.
filemode : {'perceptual', 'continuous', 'discrete'}, optional
    Controls how colormaps are generated when you input list(s) of colors.
    The options are as follows:

    * If ``'perceptual'`` or ``'continuous'``, a colormap is generated using
      `~ultraplot.colors.ContinuousColormap.from_file`. The resulting
      colormap may be a :class:`~ultraplot.colors.ContinuousColormap` or
      :class:`~ultraplot.colors.PerceptualColormap` depending on the data file.
    * If ``'discrete'``, a :class:`~ultraplot.colors.DiscreteColormap` is generated
      using `~ultraplot.colors.ContinuousColormap.from_file`.

    Default is ``'continuous'`` when calling `Colormap` directly and
    ``'discrete'`` when `Colormap` is called by `Cycle`.
listmode : {'perceptual', 'continuous', 'discrete'}, optional
    Controls how colormaps are generated when you input sequence(s)
    of colors. The options are as follows:

    * If ``'perceptual'``, a :class:`~ultraplot.colors.PerceptualColormap`
      is generated with `~ultraplot.colors.PerceptualColormap.from_list`.
    * If ``'continuous'``, a :class:`~ultraplot.colors.ContinuousColormap` is
      generated with `~ultraplot.colors.ContinuousColormap.from_list`.
    * If ``'discrete'``, a :class:`~ultraplot.colors.DiscreteColormap` is generated
      by simply passing the colors to the class.

    Default is ``'perceptual'`` when calling `Colormap` directly and
    ``'discrete'`` when `Colormap` is called by `Cycle`.
samples : int or sequence of int, optional
    For :class:`~ultraplot.colors.ContinuousColormap`\\ s, this is used to
    generate :class:`~ultraplot.colors.DiscreteColormap`\\ s with
    `~ultraplot.colors.ContinuousColormap.to_discrete`. For
    :class:`~ultraplot.colors.DiscreteColormap`\\ s, this is used to updates the
    number of colors in the cycle. If `samples` is integer, it applies
    to the final *merged* colormap. If it is a sequence of integers,
    it applies to each input colormap individually.
discrete : bool, optional
    If ``True``, when the final colormap is a
    :class:`~ultraplot.colors.DiscreteColormap`, we leave it alone, but when it is a
    :class:`~ultraplot.colors.ContinuousColormap`, we always call
    `~ultraplot.colors.ContinuousColormap.to_discrete` with a
    default `samples` value of ``10``. This argument is not
    necessary if you provide the `samples` argument.
left, right : float or sequence of float, optional
    Truncate the left or right edges of the colormap.
    Passed to :method:`~ultraplot.colors.ContinuousColormap.truncate`.
    If float, these apply to the final *merged* colormap. If sequence
    of float, these apply to each input colormap individually.
cut : float or sequence of float, optional
    Cut out the center of the colormap. Passed to
    `~ultraplot.colors.ContinuousColormap.cut`. If float,
    this applies to the final *merged* colormap. If sequence of
    float, these apply to each input colormap individually.
reverse : bool or sequence of bool, optional
    Reverse the colormap. Passed to
    `~ultraplot.colors.ContinuousColormap.reversed`. If
    float, this applies to the final *merged* colormap. If
    sequence of float, these apply to each input colormap individually.
shift : float or sequence of float, optional
    Cyclically shift the colormap.
    Passed to :property:`~ultraplot.colors.ContinuousColormap.shifted`.
    If float, this applies to the final *merged* colormap. If sequence
    of float, these apply to each input colormap individually.
a
    Shorthand for `alpha`.
alpha : float or color-spec or sequence, optional
    The opacity of the colormap or the opacity gradation. Passed to
    `ultraplot.colors.ContinuousColormap.set_alpha`
    or `ultraplot.colors.DiscreteColormap.set_alpha`. If float, this applies
    to the final *merged* colormap. If sequence of float, these apply to
    each colormap individually.
h, s, l, c
    Shorthands for `hue`, `luminance`, `saturation`, and `chroma`.
hue, saturation, luminance : float or color-spec or sequence, optional
    The channel value(s) used to generate colormaps with
    `~ultraplot.colors.PerceptualColormap.from_hsl` and
    `~ultraplot.colors.PerceptualColormap.from_color`.

    * If you provided no positional arguments, these are used to create
      an arbitrary perceptually uniform colormap with
      `~ultraplot.colors.PerceptualColormap.from_hsl`. This
      is an alternative to passing a dictionary as a positional argument
      with `hue`, `saturation`, and `luminance` as dictionary keys (see `args`).
    * If you did provide positional arguments, and any of them are
      color specifications, these control the look of monochromatic colormaps
      generated with `~ultraplot.colors.PerceptualColormap.from_color`.
      To use different values for each colormap, pass a sequence of floats
      instead of a single float. Note the default `luminance` is ``90`` if
      `discrete` is ``True`` and ``100`` otherwise.

chroma
    Alias for `saturation`.
cycle : str, optional
    The registered cycle name used to interpret color strings like ``'C0'``
    and ``'C2'``. Default is from the active property :rcraw:`cycle`. This lets
    you make monochromatic colormaps using colors selected from arbitrary cycles.
save : bool, optional
    Whether to call the colormap/color cycle save method, i.e.
    `ultraplot.colors.ContinuousColormap.save` or
    `ultraplot.colors.DiscreteColormap.save`.
save_kw : dict-like, optional
    Ignored if `save` is ``False``. Passed to the colormap/color cycle
    save method, i.e. `ultraplot.colors.ContinuousColormap.save` or
    `ultraplot.colors.DiscreteColormap.save`.

Other parameters
----------------
**kwargs
    Passed to `ultraplot.colors.ContinuousColormap.copy`,
    `ultraplot.colors.PerceptualColormap.copy`, or
    `ultraplot.colors.DiscreteColormap.copy`.

Returns
-------
matplotlib.colors.Colormap
    A :class:`~ultraplot.colors.ContinuousColormap` or
    :class:`~ultraplot.colors.DiscreteColormap` instance.

See also
--------
matplotlib.colors.Colormap
matplotlib.colors.LinearSegmentedColormap
matplotlib.colors.ListedColormap
ultraplot.constructor.Norm
ultraplot.constructor.Cycle
ultraplot.utils.get_colors"""
    ...

class Cycle(cycler.Cycler):
    """
    Generate and merge `~cycler.Cycler` instances in a variety of ways. The new generated class can be used to internally map keywords to the properties of the `~cycler.Cycler` instance. It is used by various plot functions to cycle through colors, linestyles, markers, etc.

    Parameters
    ----------
    *args : colormap-spec or cycle-spec, optional
        Positional arguments control the *colors* in the `~cycler.Cycler`
        object. If zero arguments are passed, the single color ``'black'``
        is used. If more than one argument is passed, the resulting cycles
        are merged. Arguments are interpreted as follows:

        * If a `~cycler.Cycler`, nothing more is done.
        * If a sequence of RGB tuples or color strings, these colors are used.
        * If a :class:`~ultraplot.colors.DiscreteColormap`, colors from the ``colors``
        attribute are used.
        * If a string cycle name, that :class:`~ultraplot.colors.DiscreteColormap`
        is looked up and its ``colors`` are used.
        * In all other cases, the argument is passed to `Colormap`, and
        colors from the resulting :class:`~ultraplot.colors.ContinuousColormap`
        are used. See the `samples` argument.

        If the last positional argument is numeric, it is used for the
        `samples` keyword argument.
    N
        Shorthand for `samples`.
    samples : float or sequence of float, optional
        For :class:`~ultraplot.colors.DiscreteColormap`\\ s, this is the number of
        colors to select. For example, ``Cycle('538', 4)`` returns the first 4
        colors of the ``'538'`` color cycle.
        For :class:`~ultraplot.colors.ContinuousColormap`\\ s, this is either a
        sequence of sample coordinates used to draw colors from the colormap, or
        an integer number of colors to draw. If the latter, the sample coordinates
        are ``np.linspace(0, 1, samples)``. For example, ``Cycle('Reds', 5)``
        divides the ``'Reds'`` colormap into five evenly spaced colors.

    Other parameters
    ----------------
    c, color, colors : sequence of color-spec, optional
        A sequence of colors passed as keyword arguments. This is equivalent
        to passing a sequence of colors as the first positional argument and is
        included for consistency with `~matplotlib.axes.Axes.set_prop_cycle`.
        If positional arguments were passed, the colors in this list are
        appended to the colors resulting from the positional arguments.
    lw, ls, d, a, m, ms, mew, mec, mfc
        Shorthands for the below keywords.
    linewidth, linestyle, dashes, alpha, marker, markersize, markeredgewidth, markeredgecolor, markerfacecolor : object or sequence of object, optional
        Lists of `~matplotlib.lines.Line2D` properties that can be added to the
        `~cycler.Cycler` instance. If the input was already a `~cycler.Cycler`,
        these are added or appended to the existing cycle keys. If the lists have
        unequal length, they are repeated to their least common multiple (unlike
        `~cycler.cycler`, which throws an error in this case). For more info
        on cyclers see `~matplotlib.axes.Axes.set_prop_cycle`. Also see
        the `line style reference <https://matplotlib.org/2.2.5/gallery/lines_bars_and_markers/line_styles_reference.html>`__,
        the `marker reference <https://matplotlib.org/stable/gallery/lines_bars_and_markers/marker_reference.html>`__,
        and the `custom dashes reference <https://matplotlib.org/stable/gallery/lines_bars_and_markers/line_demo_dash_control.html>`__.
    linewidths, linestyles, dashes, alphas, markers, markersizes, markeredgewidths, markeredgecolors, markerfacecolors
        Aliases for the above keywords.
    **kwargs
        If the input is not already a `~cycler.Cycler` instance, these are passed
        to `Colormap` and used to build the :class:`~ultraplot.colors.DiscreteColormap`
        from which the cycler will draw its colors.

    See also
    --------
    cycler.cycler
    cycler.Cycler
    matplotlib.axes.Axes.set_prop_cycle
    ultraplot.constructor.Colormap
    ultraplot.constructor.Norm
    ultraplot.utils.get_colors
    """

    def __init__(self, *args: Incomplete, N: Incomplete=None, samples: Incomplete=None, name: Incomplete=None, **kwargs: Incomplete) -> None:
        ...

    def _parse_basic_properties(self, kwargs: Incomplete) -> Incomplete:
        """Parse and validate basic properties from kwargs."""
        ...

    def _handle_empty_args(self, props: Incomplete, kwargs: Incomplete) -> None:
        """Handle case when no positional arguments are provided."""
        ...

    def _handle_cycler_args(self, args: Incomplete, props: Incomplete, kwargs: Incomplete) -> None:
        """Handle case when arguments are cycler objects."""
        ...

    def _handle_colormap_args(self, args: Incomplete, props: Incomplete, kwargs: Incomplete, samples: Incomplete, name: Incomplete) -> None:
        """Handle case when arguments are for creating a colormap."""
        ...

    def _create_colormap(self, args: Incomplete, name: Incomplete, samples: Incomplete, kwargs: Incomplete) -> Incomplete:
        """Create a colormap from the given arguments."""
        ...

    def _is_all_cyclers(self, args: Incomplete) -> bool:
        """Check if all arguments are Cycler objects."""
        ...

    def _build_cycler(self, dicts: Incomplete) -> None:
        """Build the final cycler from the given dictionaries."""
        ...

    def __eq__(self, other: Incomplete) -> bool:
        ...

    def get_next(self) -> Incomplete:
        ...

def Norm(norm: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
    """Return an arbitrary `~matplotlib.colors.Normalize` instance. See this
`tutorial <https://matplotlib.org/stable/tutorials/colors/colormapnorms.html>`__
for an introduction to matplotlib normalizers.

Parameters
----------
norm : str or `~matplotlib.colors.Normalize`
    The normalizer specification. If a `~matplotlib.colors.Normalize`
    instance already, a `copy.copy` of the instance is returned.
    Otherwise, `norm` should be a string corresponding to one of
    the "registered" colormap normalizers (see below table).

    If `norm` is a list or tuple and the first element is a "registered"
    normalizer name, subsequent elements are passed to the normalizer class
    as positional arguments.

    .. _norm_table:

    ===============================  =====================================
    Key(s)                           Class
    ===============================  =====================================
    ``'null'``, ``'none'``           `~matplotlib.colors.NoNorm`
    ``'diverging'``, ``'div'``       `~ultraplot.colors.DivergingNorm`
    ``'segmented'``, ``'segments'``  `~ultraplot.colors.SegmentedNorm`
    ``'linear'``                     `~matplotlib.colors.Normalize`
    ``'log'``                        `~matplotlib.colors.LogNorm`
    ``'power'``                      `~matplotlib.colors.PowerNorm`
    ``'symlog'``                     `~matplotlib.colors.SymLogNorm`
    ===============================  =====================================

Other parameters
----------------
*args, **kwargs
    Passed to the `~matplotlib.colors.Normalize` initializer.

Returns
-------
matplotlib.colors.Normalize
    A `~matplotlib.colors.Normalize` instance.

See also
--------
matplotlib.colors.Normalize
ultraplot.colors.DiscreteNorm
ultraplot.constructor.Colormap"""
    ...

def Locator(locator: Incomplete, *args: Incomplete, discrete: Incomplete=False, **kwargs: Incomplete) -> Incomplete:
    """Return a `~matplotlib.ticker.Locator` instance.

Parameters
----------
locator : `~matplotlib.ticker.Locator`, str, bool, float, or sequence
    The locator specification, interpreted as follows:

    * If a `~matplotlib.ticker.Locator` instance already,
      a `copy.copy` of the instance is returned.
    * If ``False``, a `~matplotlib.ticker.NullLocator` is used, and if
      ``True``, the default `~matplotlib.ticker.AutoLocator` is used.
    * If a number, this specifies the *step size* between tick locations.
      Returns a `~matplotlib.ticker.MultipleLocator`.
    * If a sequence of numbers, these points are ticked. Returns
      a `~matplotlib.ticker.FixedLocator` by default or a
      `~ultraplot.ticker.DiscreteLocator` if `discrete` is ``True``.

    Otherwise, `locator` should be a string corresponding to one
    of the "registered" locators (see below table). If `locator` is a
    list or tuple and the first element is a "registered" locator name,
    subsequent elements are passed to the locator class as positional
    arguments. For example, ``uplt.Locator(('multiple', 5))`` is
    equivalent to ``uplt.Locator('multiple', 5)``.

    .. _locator_table:

    =======================  ============================================  =====================================================================================
    Key                      Class                                         Description
    =======================  ============================================  =====================================================================================
    ``'null'``, ``'none'``   `~matplotlib.ticker.NullLocator`              No ticks
    ``'auto'``               `~matplotlib.ticker.AutoLocator`              Major ticks at sensible locations
    ``'minor'``              `~matplotlib.ticker.AutoMinorLocator`         Minor ticks at sensible locations
    ``'date'``               `~matplotlib.dates.AutoDateLocator`           Default tick locations for datetime axes
    ``'fixed'``              `~matplotlib.ticker.FixedLocator`             Ticks at these exact locations
    ``'discrete'``           `~ultraplot.ticker.DiscreteLocator`             Major ticks restricted to these locations but subsampled depending on the axis length
    ``'discreteminor'``      `~ultraplot.ticker.DiscreteLocator`             Minor ticks restricted to these locations but subsampled depending on the axis length
    ``'index'``              :class:`~ultraplot.ticker.IndexLocator`                Ticks on the non-negative integers
    ``'linear'``             `~matplotlib.ticker.LinearLocator`            Exactly ``N`` ticks encompassing axis limits, spaced as ``numpy.linspace(lo, hi, N)``
    ``'log'``                `~matplotlib.ticker.LogLocator`               For log-scale axes
    ``'logminor'``           `~matplotlib.ticker.LogLocator`               For log-scale axes on the 1st through 9th multiples of each power of the base
    ``'logit'``              `~matplotlib.ticker.LogitLocator`             For logit-scale axes
    ``'logitminor'``         `~matplotlib.ticker.LogitLocator`             For logit-scale axes with ``minor=True`` passed to `~matplotlib.ticker.LogitLocator`
    ``'maxn'``               `~matplotlib.ticker.MaxNLocator`              No more than ``N`` ticks at sensible locations
    ``'multiple'``           `~matplotlib.ticker.MultipleLocator`          Ticks every ``N`` step away from zero
    ``'symlog'``             `~matplotlib.ticker.SymmetricalLogLocator`    For symlog-scale axes
    ``'symlogminor'``        `~matplotlib.ticker.SymmetricalLogLocator`    For symlog-scale axes on the 1st through 9th multiples of each power of the base
    ``'theta'``              `~matplotlib.projections.polar.ThetaLocator`  Like the base locator but default locations are every `numpy.pi` / 8 radians
    ``'year'``               `~matplotlib.dates.YearLocator`               Ticks every ``N`` years
    ``'month'``              `~matplotlib.dates.MonthLocator`              Ticks every ``N`` months
    ``'weekday'``            `~matplotlib.dates.WeekdayLocator`            Ticks every ``N`` weekdays
    ``'day'``                `~matplotlib.dates.DayLocator`                Ticks every ``N`` days
    ``'hour'``               `~matplotlib.dates.HourLocator`               Ticks every ``N`` hours
    ``'minute'``             `~matplotlib.dates.MinuteLocator`             Ticks every ``N`` minutes
    ``'second'``             `~matplotlib.dates.SecondLocator`             Ticks every ``N`` seconds
    ``'microsecond'``        `~matplotlib.dates.MicrosecondLocator`        Ticks every ``N`` microseconds
    ``'lon'``, ``'deglon'``  `~ultraplot.ticker.LongitudeLocator`            Longitude gridlines at sensible decimal locations
    ``'lat'``, ``'deglat'``  `~ultraplot.ticker.LatitudeLocator`             Latitude gridlines at sensible decimal locations
    ``'dms'``                `~ultraplot.ticker.DegreeLocator`               Gridlines on nice minute and second intervals
    ``'dmslon'``             `~ultraplot.ticker.LongitudeLocator`            Longitude gridlines on nice minute and second intervals
    ``'dmslat'``             `~ultraplot.ticker.LatitudeLocator`             Latitude gridlines on nice minute and second intervals
    =======================  ============================================  =====================================================================================

Other parameters
----------------
*args, **kwargs
    Passed to the `~matplotlib.ticker.Locator` class.

Returns
-------
matplotlib.ticker.Locator
    A `~matplotlib.ticker.Locator` instance.

See also
--------
matplotlib.ticker.Locator
ultraplot.axes.CartesianAxes.format
ultraplot.axes.PolarAxes.format
ultraplot.axes.GeoAxes.format
ultraplot.axes.Axes.colorbar
ultraplot.constructor.Formatter"""
    ...

def Formatter(formatter: Incomplete, *args: Incomplete, date: Incomplete=False, index: Incomplete=False, **kwargs: Incomplete) -> Incomplete:
    """Return a `~matplotlib.ticker.Formatter` instance.

Parameters
----------
formatter : `~matplotlib.ticker.Formatter`, str, bool, callable, or sequence
    The formatter specification, interpreted as follows:

    * If a `~matplotlib.ticker.Formatter` instance already,
      a `copy.copy` of the instance is returned.
    * If ``False``, a `~matplotlib.ticker.NullFormatter` is used, and if
      ``True``, the default `~ultraplot.ticker.AutoFormatter` is used.
    * If a function, the labels will be generated using this function.
      Returns a `~matplotlib.ticker.FuncFormatter`.
    * If sequence of strings, the ticks are labeled with these strings.
      Returns a `~matplotlib.ticker.FixedFormatter` by default or
      an :class:`~ultraplot.ticker.IndexFormatter` if `index` is ``True``.
    * If a string containing ``{x}`` or ``{x:...}``, ticks will be
      formatted by calling ``string.format(x=number)``. Returns
      a `~matplotlib.ticker.StrMethodFormatter`.
    * If a string containing ``'%%'`` and `date` is ``False``, ticks
      will be formatted using the C-style ``string %% number`` method. See
      `this page <https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting>`__
      for a review. Returns a `~matplotlib.ticker.FormatStrFormatter`.
    * If a string containing ``'%%'`` and `date` is ``True``, ticks
      will be formatted using `~datetime.datetime.strfrtime`. See
      `this page <https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes>`__
      for a review. Returns a `~matplotlib.dates.DateFormatter`.

    Otherwise, `formatter` should be a string corresponding to one of the
    "registered" formatters or formatter presets (see below table). If
    `formatter` is a list or tuple and the first element is a "registered"
    formatter name, subsequent elements are passed to the formatter class
    as positional arguments. For example, ``uplt.Formatter(('sigfig', 3))`` is
    equivalent to ``Formatter('sigfig', 3)``.


    .. _tau: https://tauday.com/tau-manifesto

    .. _formatter_table:

    ======================  ==============================================  =================================================================
    Key                     Class                                           Description
    ======================  ==============================================  =================================================================
    ``'null'``, ``'none'``  `~matplotlib.ticker.NullFormatter`              No tick labels
    ``'auto'``              `~ultraplot.ticker.AutoFormatter`                 New default tick labels for axes
    ``'sci'``               `~ultraplot.ticker.SciFormatter`                  Format ticks with scientific notation
    ``'simple'``            `~ultraplot.ticker.SimpleFormatter`               New default tick labels for e.g. contour labels
    ``'sigfig'``            `~ultraplot.ticker.SigFigFormatter`               Format labels using the first ``N`` significant digits
    ``'frac'``              `~ultraplot.ticker.FracFormatter`                 Rational fractions
    ``'date'``              `~matplotlib.dates.AutoDateFormatter`           Default tick labels for datetime axes
    ``'concise'``           `~matplotlib.dates.ConciseDateFormatter`        More concise date labels introduced in matplotlib 3.1
    ``'datestr'``           `~matplotlib.dates.DateFormatter`               Date formatting with C-style ``string %% format`` notation
    ``'eng'``               `~matplotlib.ticker.EngFormatter`               Engineering notation
    ``'fixed'``             `~matplotlib.ticker.FixedFormatter`             List of strings
    ``'formatstr'``         `~matplotlib.ticker.FormatStrFormatter`         From C-style ``string %% format`` notation
    ``'func'``              `~matplotlib.ticker.FuncFormatter`              Use an arbitrary function
    ``'index'``             :class:`~ultraplot.ticker.IndexFormatter`                List of strings corresponding to non-negative integer positions
    ``'log'``               `~matplotlib.ticker.LogFormatterSciNotation`    For log-scale axes with scientific notation
    ``'logit'``             `~matplotlib.ticker.LogitFormatter`             For logistic-scale axes
    ``'percent'``           `~matplotlib.ticker.PercentFormatter`           Trailing percent sign
    ``'scalar'``            `~matplotlib.ticker.ScalarFormatter`            The default matplotlib formatter
    ``'strmethod'``         `~matplotlib.ticker.StrMethodFormatter`         From the ``string.format`` method
    ``'theta'``             `~matplotlib.projections.polar.ThetaFormatter`  Formats radians as degrees, with a degree symbol
    ``'e'``                 `~ultraplot.ticker.FracFormatter` preset          Fractions of *e*
    ``'pi'``                `~ultraplot.ticker.FracFormatter` preset          Fractions of :math:`\\pi`
    ``'tau'``               `~ultraplot.ticker.FracFormatter` preset          Fractions of the `one true circle constant <tau_>`_ :math:`\\tau`
    ``'lat'``               `~ultraplot.ticker.AutoFormatter` preset          Cardinal "SN" indicator
    ``'lon'``               `~ultraplot.ticker.AutoFormatter` preset          Cardinal "WE" indicator
    ``'deg'``               `~ultraplot.ticker.AutoFormatter` preset          Trailing degree symbol
    ``'deglat'``            `~ultraplot.ticker.AutoFormatter` preset          Trailing degree symbol and cardinal "SN" indicator
    ``'deglon'``            `~ultraplot.ticker.AutoFormatter` preset          Trailing degree symbol and cardinal "WE" indicator
    ``'dms'``               `~ultraplot.ticker.DegreeFormatter`               Labels with degree/minute/second support
    ``'dmslon'``            `~ultraplot.ticker.LongitudeFormatter`            Longitude labels with degree/minute/second support
    ``'dmslat'``            `~ultraplot.ticker.LatitudeFormatter`             Latitude labels with degree/minute/second support
    ======================  ==============================================  =================================================================

date : bool, optional
    Toggles the behavior when `formatter` contains a ``'%%'`` sign
    (see above).
index : bool, optional
    Controls the behavior when `formatter` is a sequence of strings
    (see above).

Other parameters
----------------
*args, **kwargs
    Passed to the `~matplotlib.ticker.Formatter` class.

Returns
-------
matplotlib.ticker.Formatter
    A `~matplotlib.ticker.Formatter` instance.

See also
--------
matplotlib.ticker.Formatter
ultraplot.axes.CartesianAxes.format
ultraplot.axes.PolarAxes.format
ultraplot.axes.GeoAxes.format
ultraplot.axes.Axes.colorbar
ultraplot.constructor.Locator"""
    ...

def Scale(scale: Incomplete, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
    """Return a `~matplotlib.scale.ScaleBase` instance.

Parameters
----------
scale : `~matplotlib.scale.ScaleBase`, str, or tuple
    The axis scale specification. If a `~matplotlib.scale.ScaleBase` instance
    already, a `copy.copy` of the instance is returned. Otherwise, `scale`
    should be a string corresponding to one of the "registered" axis scales
    or axis scale presets (see below table).

    If `scale` is a list or tuple and the first element is a
    "registered" scale name, subsequent elements are passed to the
    scale class as positional arguments.

    .. _scale_table:

    =================  ======================================  ===============================================
    Key                Class                                   Description
    =================  ======================================  ===============================================
    ``'linear'``       `~ultraplot.scale.LinearScale`            Linear
    ``'log'``          `~ultraplot.scale.LogScale`               Logarithmic
    ``'symlog'``       `~ultraplot.scale.SymmetricalLogScale`    Logarithmic beyond finite space around zero
    ``'logit'``        `~ultraplot.scale.LogitScale`             Logistic
    ``'inverse'``      `~ultraplot.scale.InverseScale`           Inverse
    ``'function'``     `~ultraplot.scale.FuncScale`              Arbitrary forward and backwards transformations
    ``'sine'``         `~ultraplot.scale.SineLatitudeScale`      Sine function (in degrees)
    ``'mercator'``     `~ultraplot.scale.MercatorLatitudeScale`  Mercator latitude function (in degrees)
    ``'exp'``          `~ultraplot.scale.ExpScale`               Arbitrary exponential function
    ``'power'``        `~ultraplot.scale.PowerScale`             Arbitrary power function
    ``'cutoff'``       `~ultraplot.scale.CutoffScale`            Arbitrary piecewise linear transformations
    ``'quadratic'``    `~ultraplot.scale.PowerScale` (preset)    Quadratic function
    ``'cubic'``        `~ultraplot.scale.PowerScale` (preset)    Cubic function
    ``'quartic'``      `~ultraplot.scale.PowerScale` (preset)    Quartic function
    ``'db'``           `~ultraplot.scale.ExpScale` (preset)      Ratio expressed as `decibels <db_>`_
    ``'np'``           `~ultraplot.scale.ExpScale` (preset)      Ratio expressed as `nepers <np_>`_
    ``'idb'``          `~ultraplot.scale.ExpScale` (preset)      `Decibels <db_>`_ expressed as ratio
    ``'inp'``          `~ultraplot.scale.ExpScale` (preset)      `Nepers <np_>`_ expressed as ratio
    ``'pressure'``     `~ultraplot.scale.ExpScale` (preset)      Height (in km) expressed linear in pressure
    ``'height'``       `~ultraplot.scale.ExpScale` (preset)      Pressure (in hPa) expressed linear in height
    =================  ======================================  ===============================================

    .. _db: https://en.wikipedia.org/wiki/Decibel
    .. _np: https://en.wikipedia.org/wiki/Neper

Other parameters
----------------
*args, **kwargs
    Passed to the `~matplotlib.scale.ScaleBase` class.

Returns
-------
matplotlib.scale.ScaleBase
    A `~matplotlib.scale.ScaleBase` instance.

See also
--------
matplotlib.scale.ScaleBase
ultraplot.scale.LinearScale
ultraplot.axes.CartesianAxes.format
ultraplot.axes.CartesianAxes.dualx
ultraplot.axes.CartesianAxes.dualy"""
    ...

def _warn_basemap_deprecated() -> Incomplete:
    """Warn that the basemap backend is deprecated."""
    ...

def Proj(name: Incomplete, backend: Incomplete=None, lon0: Incomplete=None, lon_0: Incomplete=None, lat0: Incomplete=None, lat_0: Incomplete=None, lonlim: Incomplete=None, latlim: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
    """Return a `cartopy.crs.Projection` or `~mpl_toolkits.basemap.Basemap` instance.

Parameters
----------
name : str, `cartopy.crs.Projection`, or `~mpl_toolkits.basemap.Basemap`
    The projection name or projection class instance. If the latter, it
    is simply returned. If the former, it must correspond to one of the
    `PROJ <https://proj.org>`__ projection name shorthands, like in
    basemap.

    The following table lists the valid projection name shorthands,
    their full names (with links to the relevant `PROJ documentation
    <https://proj.org/operations/projections>`__),
    and whether they are available in the cartopy and basemap packages.
    (added) indicates a projection class that ultraplot has "added" to
    cartopy using the cartopy API.

    .. _proj_table:

    =============  ===============================================  =========  =======
    Key            Name                                             Cartopy    Basemap
    =============  ===============================================  =========  =======
    ``'aea'``      `Albers Equal Area <aea_>`_                      ✓          ✓
    ``'aeqd'``     `Azimuthal Equidistant <aeqd_>`_                 ✓          ✓
    ``'aitoff'``   `Aitoff <aitoff_>`_                              ✓ (added)  ✗
    ``'cass'``     `Cassini-Soldner <cass_>`_                       ✗          ✓
    ``'cea'``      `Cylindrical Equal Area <cea_>`_                 ✗          ✓
    ``'cyl'``      `Cylindrical Equidistant <eqc_>`_                ✓          ✓
    ``'eck1'``     `Eckert I <eck1_>`_                              ✓          ✗
    ``'eck2'``     `Eckert II <eck2_>`_                             ✓          ✗
    ``'eck3'``     `Eckert III <eck3_>`_                            ✓          ✗
    ``'eck4'``     `Eckert IV <eck4_>`_                             ✓          ✓
    ``'eck5'``     `Eckert V <eck5_>`_                              ✓          ✗
    ``'eck6'``     `Eckert VI <eck6_>`_                             ✓          ✗
    ``'eqdc'``     `Equidistant Conic <eqdc_>`_                     ✓          ✓
    ``'eqc'``      `Cylindrical Equidistant <eqc_>`_                ✓          ✓
    ``'eqearth'``  `Equal Earth <eqearth_>`_                        ✓          ✗
    ``'europp'``   Euro PP (Europe)                                 ✓          ✗
    ``'gall'``     `Gall Stereographic Cylindrical <gall_>`_        ✗          ✓
    ``'geos'``     `Geostationary <geos_>`_                         ✓          ✓
    ``'gnom'``     `Gnomonic <gnom_>`_                              ✓          ✓
    ``'hammer'``   `Hammer <hammer_>`_                              ✓ (added)  ✓
    ``'igh'``      `Interrupted Goode Homolosine <igh_>`_           ✓          ✗
    ``'kav7'``     `Kavrayskiy VII <kav7_>`_                        ✓ (added)  ✓
    ``'laea'``     `Lambert Azimuthal Equal Area <laea_>`_          ✓          ✓
    ``'lcc'``      `Lambert Conformal <lcc_>`_                      ✓          ✓
    ``'lcyl'``     Lambert Cylindrical                              ✓          ✗
    ``'mbtfpq'``   `McBryde-Thomas Flat-Polar Quartic <mbtfpq_>`_   ✗          ✓
    ``'merc'``     `Mercator <merc_>`_                              ✓          ✓
    ``'mill'``     `Miller Cylindrical <mill_>`_                    ✓          ✓
    ``'moll'``     `Mollweide <moll_>`_                             ✓          ✓
    ``'npaeqd'``   North-Polar Azimuthal Equidistant                ✓ (added)  ✓
    ``'npgnom'``   North-Polar Gnomonic                             ✓ (added)  ✗
    ``'nplaea'``   North-Polar Lambert Azimuthal                    ✓ (added)  ✓
    ``'npstere'``  North-Polar Stereographic                        ✓          ✓
    ``'nsper'``    `Near-Sided Perspective <nsper_>`_               ✓          ✓
    ``'osni'``     OSNI (Ireland)                                   ✓          ✗
    ``'osgb'``     OSGB (UK)                                        ✓          ✗
    ``'omerc'``    `Oblique Mercator <omerc_>`_                     ✗          ✓
    ``'ortho'``    `Orthographic <ortho_>`_                         ✓          ✓
    ``'pcarree'``  `Cylindrical Equidistant <eqc_>`_                ✓          ✓
    ``'poly'``     `Polyconic <poly_>`_                             ✗          ✓
    ``'rotpole'``  Rotated Pole                                     ✓          ✓
    ``'sinu'``     `Sinusoidal <sinu_>`_                            ✓          ✓
    ``'spaeqd'``   South-Polar Azimuthal Equidistant                ✓ (added)  ✓
    ``'spgnom'``   South-Polar Gnomonic                             ✓ (added)  ✗
    ``'splaea'``   South-Polar Lambert Azimuthal                    ✓ (added)  ✓
    ``'spstere'``  South-Polar Stereographic                        ✓          ✓
    ``'stere'``    `Stereographic <stere_>`_                        ✓          ✓
    ``'tmerc'``    `Transverse Mercator <tmerc_>`_                  ✓          ✓
    ``'utm'``      `Universal Transverse Mercator <utm_>`_          ✓          ✗
    ``'vandg'``    `van der Grinten <vandg_>`_                      ✗          ✓
    ``'wintri'``   `Winkel tripel <wintri_>`_                       ✓ (added)  ✗
    =============  ===============================================  =========  =======

backend : {'cartopy', 'basemap'}, default: :rc:`geo.backend`
    Whether to return a cartopy `~cartopy.crs.Projection` instance
    or a basemap `~mpl_toolkits.basemap.Basemap` instance.

    .. deprecated:: 3.0.0
        The ``'basemap'`` backend is deprecated and may be removed in a
        future release. Please use the ``'cartopy'`` backend instead.
lon0, lat0 : float, optional
    The central projection longitude and latitude. These are translated to
    `central_longitude`, `central_latitude` for cartopy projections.
lon_0, lat_0 : float, optional
    Aliases for `lon0`, `lat0`.
lonlim : 2-tuple of float, optional
    The longitude limits. Translated to `min_longitude` and `max_longitude` for
    cartopy projections and `llcrnrlon` and `urcrnrlon` for basemap projections.
latlim : 2-tuple of float, optional
    The latitude limits. Translated to `min_latitude` and `max_latitude` for
    cartopy projections and `llcrnrlon` and `urcrnrlon` for basemap projections.

Other parameters
----------------
**kwargs
    Passed to the cartopy `~cartopy.crs.Projection` or
    basemap `~mpl_toolkits.basemap.Basemap` class.

Returns
-------
proj : mpl_toolkits.basemap.Basemap or cartopy.crs.Projection
    A cartopy or basemap projection instance.

See also
--------
mpl_toolkits.basemap.Basemap
cartopy.crs.Projection
ultraplot.ui.subplots
ultraplot.axes.GeoAxes

References
----------
For more information on map projections, see the
`wikipedia page <https://en.wikipedia.org/wiki/Map_projection>`__ and the
`PROJ <https://proj.org>`__ documentation.

.. _aea: https://proj.org/operations/projections/aea.html
.. _aeqd: https://proj.org/operations/projections/aeqd.html
.. _aitoff: https://proj.org/operations/projections/aitoff.html
.. _cass: https://proj.org/operations/projections/cass.html
.. _cea: https://proj.org/operations/projections/cea.html
.. _eqc: https://proj.org/operations/projections/eqc.html
.. _eck1: https://proj.org/operations/projections/eck1.html
.. _eck2: https://proj.org/operations/projections/eck2.html
.. _eck3: https://proj.org/operations/projections/eck3.html
.. _eck4: https://proj.org/operations/projections/eck4.html
.. _eck5: https://proj.org/operations/projections/eck5.html
.. _eck6: https://proj.org/operations/projections/eck6.html
.. _eqdc: https://proj.org/operations/projections/eqdc.html
.. _eqc: https://proj.org/operations/projections/eqc.html
.. _eqearth: https://proj.org/operations/projections/eqearth.html
.. _gall: https://proj.org/operations/projections/gall.html
.. _geos: https://proj.org/operations/projections/geos.html
.. _gnom: https://proj.org/operations/projections/gnom.html
.. _hammer: https://proj.org/operations/projections/hammer.html
.. _igh: https://proj.org/operations/projections/igh.html
.. _kav7: https://proj.org/operations/projections/kav7.html
.. _laea: https://proj.org/operations/projections/laea.html
.. _lcc: https://proj.org/operations/projections/lcc.html
.. _mbtfpq: https://proj.org/operations/projections/mbtfpq.html
.. _merc: https://proj.org/operations/projections/merc.html
.. _mill: https://proj.org/operations/projections/mill.html
.. _moll: https://proj.org/operations/projections/moll.html
.. _nsper: https://proj.org/operations/projections/nsper.html
.. _omerc: https://proj.org/operations/projections/omerc.html
.. _ortho: https://proj.org/operations/projections/ortho.html
.. _eqc: https://proj.org/operations/projections/eqc.html
.. _poly: https://proj.org/operations/projections/poly.html
.. _sinu: https://proj.org/operations/projections/sinu.html
.. _stere: https://proj.org/operations/projections/stere.html
.. _tmerc: https://proj.org/operations/projections/tmerc.html
.. _utm: https://proj.org/operations/projections/utm.html
.. _vandg: https://proj.org/operations/projections/vandg.html
.. _wintri: https://proj.org/operations/projections/wintri.html"""
    ...
