# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
The figure class used for all ultraplot figures.
"""
from _typeshed import Incomplete
import functools
import inspect
import os
from contextlib import ExitStack
from typing import Callable, TypeVar, cast
try:
    from typing import Any, Iterable, List, Optional, Tuple, Union
except ImportError:
    from typing_extensions import Any, Iterable, List, Optional, Tuple, Union
import matplotlib.axes as maxes
import matplotlib.figure as mfigure
import matplotlib.text as mtext
import matplotlib.transforms as mtransforms
import numpy as np
try:
    from typing import override
except:
    from typing_extensions import override
from . import axes as paxes
from .axes._formatting import axis_format_requires_layout, pop_axis_format_kwargs
from . import constructor
from . import gridspec as pgridspec
from . import legend as plegend
from .config import rc, rc_matplotlib
from .internals import _alias_kwargs, _not_none, _pop_params, _pop_rc, _translate_loc, context, docstring, ic, labels, warnings
from ._layout import _LayoutTransaction
from ._subplots import SubplotManager
from .utils import _Crawler, units
__all__ = ['Figure']
_F = TypeVar('_F', bound=Callable[..., Any])

def _any_not_none(*values: Incomplete) -> Incomplete:
    """Return whether at least one value is not ``None``."""
    ...
JOURNAL_SIZES = {'aaas1': '5.5cm', 'aaas2': '12cm', 'agu1': ('95mm', '115mm'), 'agu2': ('190mm', '115mm'), 'agu3': ('95mm', '230mm'), 'agu4': ('190mm', '230mm'), 'ams1': 3.2, 'ams2': 4.5, 'ams3': 5.5, 'ams4': 6.5, 'cop1': '8.3cm', 'cop2': '12cm', 'nat1': '89mm', 'nat2': '183mm', 'pnas1': '8.7cm', 'pnas2': '11.4cm', 'pnas3': '17.8cm'}
_figure_docstring = ...
_subplots_params_docstring = ...
_axes_params_docstring = ...
_subplots_docstring = ...
_subplot_docstring = ...
_axes_docstring = ...
_space_docstring = ...
_figure_semantic_legend_common_docstring = ...
_figure_entrylegend_docstring = ...
_figure_catlegend_docstring = ...
_figure_sizelegend_docstring = ...
_figure_numlegend_docstring = ...
_figure_geolegend_docstring = ...
_save_docstring = ...

def _get_journal_size(preset: Incomplete) -> Incomplete:
    """Return the width and height corresponding to the given preset."""
    ...

def _add_canvas_preprocessor(canvas: Incomplete, method: Incomplete, cache: Incomplete=False) -> Incomplete:
    """Return a pre-processer that can be used to override instance-level
canvas draw() and print_figure() methods. This applies tight layout
and aspect ratio-conserving adjustments and aligns labels. Required
so canvas methods instantiate renderers with the correct dimensions."""
    ...

def _clear_border_cache(func: _F) -> _F:
    """Decorator that clears the border cache after function execution."""
    ...

class Figure(mfigure.Figure):
    """The [Figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.html) subclass used by ultraplot."""
    _share_message = "Axis sharing level can be 0 or False (share nothing), 1 or 'labels' or 'labs' (share axis labels), 2 or 'limits' or 'lims' (share axis limits and axis labels), 3 or True (share axis limits, axis labels, and tick labels), 4 or 'all' (share axis labels and tick labels in the same gridspec rows and columns and share axis limits across all subplots), or 'auto' (start unshared and share only compatible axes)."
    _space_message = 'To set the left, right, bottom, top, wspace, or hspace gridspec values, pass them as keyword arguments to uplt.figure() or uplt.subplots(). Please note they are now specified in physical units, with strings interpreted by uplt.units() and floats interpreted as font size-widths.'
    _tight_message = "ultraplot uses its own tight layout algorithm that is activated by default. To disable it, set uplt.rc['subplots.tight'] to False or pass tight=False to uplt.subplots(). For details, see fig.auto_layout()."
    _warn_interactive = True

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...

    def __init__(self, *, refnum: Incomplete=None, refaspect: Incomplete=None, refwidth: Incomplete=None, refheight: Incomplete=None, figwidth: Incomplete=None, figheight: Incomplete=None, journal: Incomplete=None, sharex: Incomplete=None, sharey: Incomplete=None, share: Incomplete=None, spanx: Incomplete=None, spany: Incomplete=None, span: Incomplete=None, alignx: Incomplete=None, aligny: Incomplete=None, align: Incomplete=None, left: Incomplete=None, right: Incomplete=None, top: Incomplete=None, bottom: Incomplete=None, wspace: Incomplete=None, hspace: Incomplete=None, space: Incomplete=None, tight: Incomplete=None, outerpad: Incomplete=None, innerpad: Incomplete=None, panelpad: Incomplete=None, wpad: Incomplete=None, hpad: Incomplete=None, pad: Incomplete=None, wequal: Incomplete=None, hequal: Incomplete=None, equal: Incomplete=None, wgroup: Incomplete=None, hgroup: Incomplete=None, group: Incomplete=None, **kwargs: Incomplete) -> None:
        """Parameters
----------
- `refnum`: The reference subplot number.
- `refaspect`: The reference subplot aspect ratio.
- `refwidth, refheight`: The width, height of the reference subplot.
- `figwidth, figheight`: The figure width and height.
- `figsize`: Tuple specifying the figure ``(width, height)``.
- `sharex, sharey, share`: The axis sharing "level" for the *x* axis, *y* axis, or both axes.
- `spanx, spany, span`: Whether to use "spanning" axis labels for the *x* axis, *y* axis, or both axes.
- `alignx, aligny, align`: Whether to ["align" axis labels](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/align_labels_demo.html) for the *x* axis, *y* axis, or both axes.
- `left, right, top, bottom`: The fixed space between the subplots and the figure edge.
- `wspace, hspace, space`: The fixed space between grid columns, rows, or both.
- `tight`: Whether automatic calls to `~Figure.auto_layout` should include [tight layout adjustments](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight).
- `wequal, hequal, equal`: Whether to make the tight layout algorithm apply equal spacing between columns, rows, or both.
- `wgroup, hgroup, group`: Whether to make the tight layout algorithm just consider spaces between adjacent subplots instead of entire columns and rows of subplots.
- `outerpad`: The scalar tight layout padding around the left, right, top, bottom figure edges.
- `innerpad`: The scalar tight layout padding between columns and rows.
- `panelpad`: The scalar tight layout padding between subplots and their panels, colorbars, and legends and between "stacks" of these objects.
- `journal`: String corresponding to an academic journal standard used to control the figure width `figwidth` and, if specified, the figure height `figheight`.
- `leftlabels, toplabels, rightlabels, bottomlabels`: Labels for the subplots lying along the left, top, right, and bottom edges of the figure.
- `leftlabelpad, toplabelpad, rightlabelpad, bottomlabelpad`: : [leftlabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=leftlabel.pad), [toplabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=toplabel.pad), [rightlabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=rightlabel.pad), [bottomlabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=bottomlabel.pad) The padding between the labels and the axes content.
- `leftlabelsharedpad, toplabelsharedpad, rightlabelsharedpad, bottomlabelsharedpad`: : [leftlabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=leftlabel.sharedpad), [toplabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=toplabel.sharedpad), [rightlabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=rightlabel.sharedpad), [bottomlabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=bottomlabel.sharedpad) The padding between side labels and a shared spanning axis label on…
- `leftlabels_kw, toplabels_kw, rightlabels_kw, bottomlabels_kw`: Additional settings used to update the labels with ``text.update()``.
- `figtitle`: Alias for `suptitle`.
- `suptitle`: The figure "super" title, centered between the left edge of the leftmost subplot and the right edge of the rightmost subplot.
- `suptitlepad`: The padding between the super title and the axes content.
- `suptitle_kw`: Additional settings used to update the super title with ``text.update()``.
- `includepanels`: Whether to include panels when aligning figure "super titles" along the top of the subplot grid and when aligning the `spanx` *x* axis labels and `spany` *y* axis labels along the…
- `**kwargs`: Passed to [matplotlib.figure.Figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.html).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html)"""
        ...

    def _init_figure_size(self, refnum: Incomplete, refaspect: Incomplete, refwidth: Incomplete, refheight: Incomplete, figwidth: Incomplete, figheight: Incomplete, journal: Incomplete) -> Incomplete:
        """Resolve figure sizing from reference dimensions, journal presets,
and explicit figure dimensions. Sets sizing attributes on self and
returns the resolved (figwidth, figheight)."""
        ...

    def _init_gridspec_params(self, **params: Incomplete) -> None:
        """Validate and store gridspec spacing parameters."""
        ...

    def _init_tight_layout(self, tight: Incomplete, kwargs: Incomplete) -> None:
        """Configure tight layout, suppressing native matplotlib layout engines."""
        ...

    @staticmethod
    def _normalize_share(value: Incomplete) -> Incomplete:
        """Normalize a share setting to an integer level and auto flag."""
        ...

    def _init_sharing(self, *, sharex: Incomplete, sharey: Incomplete, share: Incomplete, spanx: Incomplete, spany: Incomplete, span: Incomplete, alignx: Incomplete, aligny: Incomplete, align: Incomplete) -> None:
        """Resolve share, span, and align settings."""
        ...

    def _init_figure_state(self, figwidth: Incomplete, figheight: Incomplete, kwargs: Incomplete) -> None:
        """Initialize internal state, call matplotlib's Figure.__init__,
set up super labels, and apply initial formatting."""
        ...

    def _init_super_labels(self) -> None:
        """Create the figure-level label artists and their style state.

NOTE: Also called by `clear`, which discards every artist on the figure and
sets ``_suptitle`` to None. The labels must be rebuilt there or the next
``format(suptitle=...)`` raises on the missing artist."""
        ...

    def _invalidate_layout(self, *, reset: Incomplete=False) -> None:
        """Mark automatic layout stale, optionally discarding persistent state."""
        ...

    def clear(self, keep_observers: Incomplete=False) -> None:
        """Clear the figure, discarding all subplots, panels, and figure-level labels.

Parameters
----------
keep_observers : bool, default: False
    Whether to retain the figure's observers, e.g. a GUI widget tracking
    the axes.

See also
--------
matplotlib.figure.Figure.clear"""
        ...

    @override
    def draw(self, renderer: Incomplete) -> Incomplete:
        """Draw the Artist (and its children) using the given renderer.

This has no effect if the artist is not visible (`.Artist.get_visible`
returns False).

Parameters
----------
renderer : [RendererBase](https://matplotlib.org/stable/api/_as_gen/matplotlib.backend_bases.RendererBase.html) subclass.

Notes
-----
This method is overridden in the Artist subclasses."""
        ...

    @override
    def draw_without_rendering(self) -> Incomplete:
        """Draw without output while preserving figure dpi state."""
        ...

    def _blit_manager(self, *artists: Incomplete, bbox: Incomplete=None) -> Incomplete:
        """Return a manager for efficient updates of changing artists.

Parameters
----------
*artists : [Artist](https://matplotlib.org/stable/api/_as_gen/matplotlib.artist.Artist.html)
    Artists that will change between updates.
bbox : [Bbox](https://matplotlib.org/stable/api/_as_gen/matplotlib.transforms.Bbox.html) or object with a ``bbox`` attribute, optional
    Region to cache and blit. By default, the union of the artists'
    axes bounding boxes is used.

Returns
-------
[_BlitManager](https://ultraplot.readthedocs.io/en/stable/api/ultraplot._animation._BlitManager.html)
    Manager that restores the cached static background and redraws only
    the supplied artists."""
        ...

    def _is_auto_share_mode(self, which: str) -> bool:
        """Return whether a given axis uses auto-share mode."""
        ...

    def _axis_unit_signature(self, ax: Incomplete, which: str) -> tuple[str | None, bytes | str | None] | None:
        """Return a lightweight signature for axis unit/converter compatibility."""
        ...

    def _share_axes_compatible(self, ref: Incomplete, other: Incomplete, which: str) -> Incomplete:
        """Check whether two axes are compatible for sharing along one axis."""
        ...

    def _warn_incompatible_share(self, which: str, ref: Incomplete, other: Incomplete, reason: str) -> None:
        """Warn once per figure for explicit incompatible sharing."""
        ...

    def _partition_share_axes(self, axes: Incomplete, which: str) -> Incomplete:
        """Partition a candidate share list into compatible sub-groups."""
        ...

    def _iter_shared_groups(self, which: str, *, panels: bool=True) -> Incomplete:
        """Yield unique shared groups for one axis direction."""
        ...

    def _join_shared_group(self, which: str, ref: Incomplete, other: Incomplete) -> None:
        """Join an axis to a shared group and copy the shared axis state."""
        ...

    def _refresh_auto_share(self, which: Optional[str]=None) -> None:
        """Recompute auto-sharing groups after local axis-state changes."""
        ...

    def _autoscale_shared_limits(self, which: str) -> None:
        """Recompute shared data limits for each compatible shared-axis group."""
        ...

    def _snap_axes_to_pixel_grid(self, renderer: Incomplete) -> None:
        """Snap visible axes bounds to the renderer pixel grid."""
        ...

    def _find_misaligned_spans(self, axes: List[paxes.Axes], *, tol: float=1e-09) -> List[Tuple[str, int, int, mtransforms.Bbox, mtransforms.Bbox, paxes.Axes]]:
        """Identify spanning axes whose actual position differs from their
gridspec slot (e.g. because of an aspect constraint).

Returns a list of ``(axis, start, stop, slot, pos, ref_ax)`` tuples
where *axis* is ``'y'`` for row-spanning or ``'x'`` for column-spanning."""
        ...

    def _remap_axes_to_span(self, axes: List[paxes.Axes], spans: List[Tuple[str, int, int, mtransforms.Bbox, mtransforms.Bbox, paxes.Axes]], *, tol: float=1e-09) -> None:
        """Remap sibling axes so they align with the actual bounds of
spanning axes described by *spans*.  Siblings with their own
fixed aspect are skipped since they have independent constraints."""
        ...

    def _align_spanning_axes(self, *, tol: float=1e-09) -> None:
        """Align sibling subplots to spanning axes whose actual position
differs from their gridspec slot.

When a subplot spans multiple rows or columns and is shrunk inside
its slot (e.g. by a fixed aspect ratio), the adjacent subplots keep
their full extent and visibly stick out.  This method detects the
mismatch and remaps the sibling positions proportionally."""
        ...

    def _share_ticklabels(self, *, axis: str) -> None:
        """Tick label sharing is determined at the figure level. While
each subplot controls the limits, we are dealing with the ticklabels
here as the complexity is easier to deal with.
    axis: str 'x' or 'y', row or columns to update"""
        ...

    def _label_key_map(self) -> Incomplete:
        """Return a mapping for version-dependent label keys for Matplotlib tick params."""
        ...

    def _group_axes_by_axis(self, axes: Incomplete, axis: str) -> Incomplete:
        """Group axes by row (x) or column (y). Panels included; invalid subplotspec skipped."""
        ...

    def _compute_baseline_tick_state(self, group_axes: Incomplete, axis: str, label_keys: Incomplete) -> Incomplete:
        """Build a baseline ticklabel visibility dict from MAIN axes (panels excluded).
Returns (baseline_dict, skip_group: bool). Emits warnings when encountering
unsupported or mixed subplot types."""
        ...

    def _apply_border_mask(self, axi: Incomplete, baseline: dict, sides: tuple[str, str], outer_axes: Incomplete) -> Incomplete:
        """Apply figure-border constraints and panel opposite-side suppression.
Keeps label key mapping per-axis for cartesian."""
        ...

    def _effective_share_level(self, axi: Incomplete, axis: str, sides: tuple[str, str]) -> int:
        """Compute the effective share level for an axes, considering panel groups and
adjacent panels. Fixes the original variable leak by checking any relevant side."""
        ...

    def _set_ticklabel_state(self, axi: Incomplete, axis: str, state: dict) -> None:
        """Apply the computed ticklabel state to cartesian or geo axes."""
        ...

    def _context_adjusting(self, cache: Incomplete=True) -> Incomplete:
        """Prevent re-running auto layout steps due to draws triggered by figure
resizes. Otherwise can get infinite loops."""
        ...

    def _context_authorized(self) -> Incomplete:
        """Prevent warning message when internally calling no-op methods. Otherwise
emit warnings to help new users."""
        ...

    @staticmethod
    def _parse_backend(backend: Incomplete=None, basemap: Incomplete=None) -> Incomplete:
        """Delegate to SubplotManager."""
        ...

    def _parse_proj(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
        """Delegate to SubplotManager."""
        ...

    def _get_align_axes(self, side: Incomplete) -> Incomplete:
        """Return the main axes along the edge of the figure.

For 'left'/'right': select one extreme axis per row (leftmost/rightmost).
For 'top'/'bottom': select one extreme axis per column (topmost/bottommost)."""
        ...

    def _get_border_axes(self, *, same_type: Incomplete=False, force_recalculate: Incomplete=False) -> dict[str, list[paxes.Axes]]:
        """Identifies axes located on the outer boundaries of the GridSpec layout.

Returns a dictionary with keys 'top', 'bottom', 'left', 'right', each
containing a list of axes on that border."""
        ...

    def _get_align_coord(self, side: Incomplete, axs: Incomplete, align: Incomplete='center', includepanels: Incomplete=False) -> Incomplete:
        """Return the figure coordinate for positioning spanning axis labels or super titles.

Parameters
----------
side : str
    Side of the figure ('top', 'bottom', 'left', 'right').
axs : list
    List of axes to align across.
align : str, default 'center'
    Horizontal alignment for x-axis positioning: 'left', 'center', or 'right'.
    For y-axis positioning, always centers regardless of this parameter.
includepanels : bool, default False
    Whether to include panel axes in the alignment calculation."""
        ...

    def _get_offset_coord(self, side: Incomplete, axs: Incomplete, renderer: Incomplete, *, pad: Incomplete=None, extra: Incomplete=None, include_subset_titles: Incomplete=True, exclude_spanning_axis_labels: Incomplete=False) -> Incomplete:
        """Return the figure coordinate for offsetting super labels and super titles."""
        ...

    def _get_layout_axes_bbox(self, axes: Incomplete, renderer: Incomplete, *, include_subset_titles: Incomplete=True, use_cache: Incomplete=True) -> Incomplete:
        """Return an axes bbox using the active relative-outset store."""
        ...

    def _get_layout_tightbbox(self, renderer: Incomplete) -> Incomplete:
        """Return the figure tight bbox while reusing relative axes outsets.

This mirrors matplotlib's ``Figure.get_tightbbox`` but routes axes
measurements through the active relative-outset store."""
        ...

    def _get_renderer(self) -> Incomplete:
        """Get a renderer at all costs. See matplotlib's tight_layout.py."""
        ...

    def _add_axes_panel(self, ax: 'paxes.Axes', side: Optional[str]=None, span: Optional[Union[int, Tuple[int, int]]]=None, row: Optional[int]=None, col: Optional[int]=None, rows: Optional[Union[int, Tuple[int, int]]]=None, cols: Optional[Union[int, Tuple[int, int]]]=None, **kwargs: Incomplete) -> 'paxes.Axes':
        """Add an axes panel."""
        ...

    def _add_figure_panel(self, side: Optional[str]=None, span: Optional[Union[int, Tuple[int, int]]]=None, row: Optional[int]=None, col: Optional[int]=None, rows: Optional[Union[int, Tuple[int, int]]]=None, cols: Optional[Union[int, Tuple[int, int]]]=None, **kwargs: Incomplete) -> 'paxes.Axes':
        """Add a figure panel."""
        ...

    def _add_subplot(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
        """Delegate to SubplotManager."""
        ...

    def _unshare_axes(self) -> None:
        ...

    def _toggle_axis_sharing(self, *, which: Incomplete='y', share: Incomplete=True, panels: Incomplete=False, children: Incomplete=False, hidden: Incomplete=False) -> None:
        """Share or unshare axes in the figure along a given direction.

Parameters:
- which: 'x', 'y', 'z', or 'view'.
- share: int indicating the levels (see above)
- panels: Whether to include panel axes.
- children: Whether to include child axes.
- hidden: Whether to include hidden axes."""
        ...

    def _add_subplots(self, *args: Incomplete, **kwargs: Incomplete) -> Incomplete:
        """Delegate to SubplotManager."""
        ...

    def _align_axis_label(self, x: Incomplete) -> None:
        """Align *x* and *y* axis labels in the perpendicular and parallel directions."""
        ...

    def _register_share_label_group(self, axes: Incomplete, *, target: Incomplete, source: Incomplete=None) -> None:
        """Register an explicit label-sharing group for a subset of axes."""
        ...

    def _register_share_label_group_for_side(self, axes: Incomplete, *, target: Incomplete, side: Incomplete, source: Incomplete=None) -> None:
        """Register a single label-sharing group for a given label side."""
        ...

    def _is_share_label_group_member(self, ax: Incomplete, axis: Incomplete) -> bool:
        """Return True if the axes belongs to any explicit label-sharing group."""
        ...

    def _has_share_label_groups(self, axis: Incomplete) -> bool:
        """Return True if there are any explicit label-sharing groups for an axis."""
        ...

    def _clear_share_label_groups(self, axes: Incomplete=None, *, target: Incomplete=None) -> None:
        """Clear explicit label-sharing groups, optionally filtered by axes."""
        ...

    def _apply_share_label_groups(self, axis: Incomplete=None) -> None:
        """Apply explicit label-sharing groups, overriding default label sharing."""
        ...

    def _align_super_labels(self, side: Incomplete, renderer: Incomplete) -> None:
        """Adjust the position of super labels."""
        ...

    def _align_spanning_axis_labels(self, side: Incomplete, renderer: Incomplete, side_labels: Incomplete) -> None:
        """Place spanning axis labels outside figure-level labels on the same side.

Figure-level side labels describe individual rows or columns, while a
spanning axis label describes the whole group. The latter therefore has
lower visual priority and belongs farther from the axes."""
        ...

    def _align_super_title(self, renderer: Incomplete) -> None:
        """Adjust the position of the super title based on user alignment preferences.

Respects horizontal and vertical alignment settings from suptitle_kw parameters,
while applying sensible defaults when no custom alignment is provided."""
        ...

    @staticmethod
    def _deduplicate_axes(axes: Iterable[paxes.Axes]) -> List[paxes.Axes]:
        """Resolve panel parents and remove duplicates, preserving order."""
        ...

    @staticmethod
    def _normalize_title_alignment(loc: str) -> str:
        """Convert a *loc* string to a horizontal alignment for ``Text.set_ha``."""
        ...

    @staticmethod
    def _resolve_title_props(fontdict: dict[str, Any] | None, kwargs: dict[str, Any]) -> dict[str, Any]:
        """Build the property dict for a title from rc defaults, *fontdict*,
and extra *kwargs*."""
        ...

    def _update_subset_title(self, axes: Iterable[paxes.Axes], title: str | None, *, fontdict: dict[str, Any] | None=None, loc: str | None=None, pad: float | str | None=None, y: float | None=None, **kwargs: Any) -> mtext.Text:
        """Create or update a title spanning a subset of subplots."""
        ...

    def _visible_subset_group_axes(self, group: dict[str, Any]) -> List[paxes.Axes]:
        """Return visible axes from a subset-title group that belong to this figure."""
        ...

    def _get_subset_title_bbox(self, ax: paxes.Axes, renderer: Incomplete) -> mtransforms.Bbox | None:
        """Return the union bbox for shared titles covering the given axes.

Shared subset titles live above the subset's top edge, so they should
only contribute to the tight bounding boxes for axes that actually touch
that top boundary. Otherwise, multi-row subsets can incorrectly claim
the title as extra inter-row spacing."""
        ...

    def _align_subset_titles(self, renderer: Any) -> None:
        """Update the positions of titles spanning subplot subsets."""
        ...

    def _update_axis_label(self, side: Incomplete, axs: Incomplete) -> None:
        """Update the aligned axis label for the input axes."""
        ...

    def _update_super_labels(self, side: Incomplete, labels: Incomplete, **kwargs: Incomplete) -> None:
        """Assign the figure super labels and update settings."""
        ...

    def _update_super_title(self, title: Incomplete, **kwargs: Incomplete) -> None:
        """Assign the figure super title and update settings."""
        ...

    @staticmethod
    def _iter_semantic_legend_axes(candidate: Incomplete) -> Incomplete:
        """Yield axes objects from nested axis containers."""
        ...

    def _semantic_legend_axes(self, ax: Incomplete=None, ref: Incomplete=None) -> Incomplete:
        """Pick an axes instance for semantic legend handle generation."""
        ...

    def entrylegend(self, entries: Incomplete, *, line: Incomplete=None, marker: Incomplete=None, color: Incomplete=None, linestyle: Incomplete=None, linewidth: Incomplete=None, markersize: Incomplete=None, alpha: Incomplete=None, markeredgecolor: Incomplete=None, markeredgewidth: Incomplete=None, markerfacecolor: Incomplete=None, handle_kw: Incomplete=None, add: Incomplete=True, **legend_kwargs: Incomplete) -> Incomplete:
        """Build generic semantic legend entries and optionally add a figure legend.

Parameters
----------
entries
    Entry specifications as handles, style dictionaries, or ``(label, spec)``
    pairs.

Other parameters
----------------
**legend_kwargs
    Placement and legend styling keywords forwarded to
    [legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend) when ``add=True``. This includes figure legend
    placement keywords like ``loc=``, ``ref=``, ``ax=``, ``rows=``, ``cols=``, and
    ``span=``. Pass ``add=False`` to return ``(handles, labels)`` without drawing.

Notes
-----
Handle generation currently reuses the semantic legend builder used by
[entrylegend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.entrylegend), then routes the final draw step through
[legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend)."""
        ...

    def catlegend(self, categories: Incomplete, *, colors: Incomplete=None, markers: Incomplete=None, line: Incomplete=None, linestyle: Incomplete=None, linewidth: Incomplete=None, markersize: Incomplete=None, alpha: Incomplete=None, markeredgecolor: Incomplete=None, markeredgewidth: Incomplete=None, markerfacecolor: Incomplete=None, handle_kw: Incomplete=None, add: Incomplete=True, **legend_kwargs: Incomplete) -> Incomplete:
        """Build categorical legend entries and optionally add a figure legend.

Parameters
----------
categories
    Category labels used to generate legend handles.

Other parameters
----------------
**legend_kwargs
    Placement and legend styling keywords forwarded to
    [legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend) when ``add=True``. This includes figure legend
    placement keywords like ``loc=``, ``ref=``, ``ax=``, ``rows=``, ``cols=``, and
    ``span=``. Pass ``add=False`` to return ``(handles, labels)`` without drawing.

Notes
-----
Handle generation currently reuses the semantic legend builder used by
[catlegend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.catlegend), then routes the final draw step through
[legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend)."""
        ...

    def sizelegend(self, levels: Incomplete, *, labels: Incomplete=None, color: Incomplete=None, marker: Incomplete=None, area: Incomplete=None, values: Incomplete=None, vmin: Incomplete=None, vmax: Incomplete=None, smin: Incomplete=None, smax: Incomplete=None, area_size: Incomplete=None, absolute_size: Incomplete=None, scale: Incomplete=None, minsize: Incomplete=None, fmt: Incomplete=None, alpha: Incomplete=None, markeredgecolor: Incomplete=None, markeredgewidth: Incomplete=None, markerfacecolor: Incomplete=None, handle_kw: Incomplete=None, add: Incomplete=True, **legend_kwargs: Incomplete) -> Incomplete:
        """Build size legend entries and optionally add a figure legend.

Parameters
----------
levels
    Numeric levels used to generate marker-size entries.
values, vmin, vmax, smin, smax, area_size, absolute_size
    Optional scatter-style size scaling controls forwarded to
    [sizelegend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.sizelegend). When omitted, a compatible UltraPlot
    scatter artist can be used to infer the size scale automatically.

Other parameters
----------------
**legend_kwargs
    Placement and legend styling keywords forwarded to
    [legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend) when ``add=True``. This includes figure legend
    placement keywords like ``loc=``, ``ref=``, ``ax=``, ``rows=``, ``cols=``, and
    ``span=``. Pass ``add=False`` to return ``(handles, labels)`` without drawing.

Notes
-----
Handle generation currently reuses the semantic legend builder used by
[sizelegend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.sizelegend), then routes the final draw step through
[legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend).

Pass ``labels=[...]`` or ``labels={level: label}`` to override the generated labels."""
        ...

    def numlegend(self, levels: Incomplete=None, *, vmin: Incomplete=None, vmax: Incomplete=None, n: Incomplete=None, cmap: Incomplete=None, norm: Incomplete=None, fmt: Incomplete=None, facecolor: Incomplete=None, edgecolor: Incomplete=None, linewidth: Incomplete=None, linestyle: Incomplete=None, alpha: Incomplete=None, handle_kw: Incomplete=None, add: Incomplete=True, **legend_kwargs: Incomplete) -> Incomplete:
        """Build numeric-color legend entries and optionally add a figure legend.

Parameters
----------
levels
    Numeric levels or number of levels.

Other parameters
----------------
**legend_kwargs
    Placement and legend styling keywords forwarded to
    [legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend) when ``add=True``. This includes figure legend
    placement keywords like ``loc=``, ``ref=``, ``ax=``, ``rows=``, ``cols=``, and
    ``span=``. Pass ``add=False`` to return ``(handles, labels)`` without drawing.

Notes
-----
Handle generation currently reuses the semantic legend builder used by
[numlegend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.numlegend), then routes the final draw step through
[legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend)."""
        ...

    def geolegend(self, entries: Incomplete, labels: Incomplete=None, *, country_reso: Incomplete=None, country_territories: Incomplete=None, country_proj: Incomplete=None, handlesize: Incomplete=None, facecolor: Incomplete=None, edgecolor: Incomplete=None, linewidth: Incomplete=None, alpha: Incomplete=None, fill: Incomplete=None, add: Incomplete=True, **legend_kwargs: Incomplete) -> Incomplete:
        """Build geometry legend entries and optionally add a figure legend.

Parameters
----------
entries
    Geometry entries (mapping, ``(label, geometry)`` pairs, or geometries).
labels
    Optional labels for geometry sequences.

Other parameters
----------------
**legend_kwargs
    Placement and legend styling keywords forwarded to
    [legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend) when ``add=True``. This includes figure legend
    placement keywords like ``loc=``, ``ref=``, ``ax=``, ``rows=``, ``cols=``, and
    ``span=``. Pass ``add=False`` to return ``(handles, labels)`` without drawing.

Notes
-----
Handle generation currently reuses the semantic legend builder used by
[geolegend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.geolegend), then routes the final draw step through
[legend](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend)."""
        ...

    def add_axes(self, rect: Incomplete, **kwargs: Incomplete) -> Incomplete:
        """Add a non-subplot axes to the figure.

Parameters
----------
- `rect`: The (left, bottom, width, height) dimensions of the axes in figure-relative coordinates.
- `proj, projection`: The map projection specification(s).
- `proj_kw, projection_kw`: Keyword arguments passed to `Basemap` or `Projection` classes on instantiation.
- `backend`: Whether to use `Basemap` or `Projection` for map projections.
- `**kwargs`: Passed to the ultraplot class [ultraplot.axes.CartesianAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.CartesianAxes.html), [ultraplot.axes.PolarAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.PolarAxes.html), [ultraplot.axes.GeoAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html), or [ultraplot.axes.ThreeAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.ThreeAxes.html).
- `projection`: The projection type of the `~.axes.Axes`.
- `polar`: If True, equivalent to projection='polar'.
- `axes_class`: The `.axes.Axes` subclass that is instantiated.
- `sharex, sharey`: Share the x or y [axis](https://matplotlib.org/stable/api/_as_gen/matplotlib.axis.html) with sharex and/or sharey.
- `label`: A label for the returned Axes.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.add_axes)"""
        ...

    def add_subplot(self, *args: Incomplete, **kwargs: Incomplete) -> paxes.Axes:
        """Add a subplot axes to the figure.

Parameters
----------
- `*args`: The subplot location specifier.
- `number`: The axes number used for a-b-c labeling.
- `autoshare`: Whether to automatically share the *x* and *y* axes with subplots spanning the same rows and columns based on the figure-wide `sharex` and `sharey` settings.
- `proj, projection`: The map projection specification(s).
- `proj_kw, projection_kw`: Keyword arguments passed to `Basemap` or `Projection` classes on instantiation.
- `backend`: Whether to use `Basemap` or `Projection` for map projections.
- `**kwargs`: Passed to the ultraplot class [ultraplot.axes.CartesianAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.CartesianAxes.html), [ultraplot.axes.PolarAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.PolarAxes.html), [ultraplot.axes.GeoAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html), or [ultraplot.axes.ThreeAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.ThreeAxes.html).
- `projection`: The projection type of the subplot (`~.axes.Axes`).
- `polar`: If True, equivalent to projection='polar'.
- `axes_class`: The `.axes.Axes` subclass that is instantiated.
- `sharex, sharey`: Share the x or y [axis](https://matplotlib.org/stable/api/_as_gen/matplotlib.axis.html) with sharex and/or sharey.
- `label`: A label for the returned Axes.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.add_subplot)"""
        ...

    def subplot(self, *args: Incomplete, **kwargs: Incomplete) -> paxes.Axes:
        """Add a subplot axes to the figure.

Parameters
----------
- `*args`: The subplot location specifier.
- `number`: The axes number used for a-b-c labeling.
- `autoshare`: Whether to automatically share the *x* and *y* axes with subplots spanning the same rows and columns based on the figure-wide `sharex` and `sharey` settings.
- `proj, projection`: The map projection specification(s).
- `proj_kw, projection_kw`: Keyword arguments passed to `Basemap` or `Projection` classes on instantiation.
- `backend`: Whether to use `Basemap` or `Projection` for map projections.
- `**kwargs`: Passed to the ultraplot class [ultraplot.axes.CartesianAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.CartesianAxes.html), [ultraplot.axes.PolarAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.PolarAxes.html), [ultraplot.axes.GeoAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html), or [ultraplot.axes.ThreeAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.ThreeAxes.html).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.subplot)"""
        ...

    def add_subplots(self, *args: Incomplete, **kwargs: Incomplete) -> pgridspec.SubplotGrid:
        """Add an arbitrary grid of subplots to the figure.

Parameters
----------
- `array`: The subplot grid specifier.
- `nrows, ncols`: The number of rows and columns in the subplot grid.
- `order`: Whether subplots are numbered in column-major (``'C'``) or row-major (``'F'``) order.
- `proj, projection`: The map projection specification(s).
- `proj_kw, projection_kw`: Keyword arguments passed to `Basemap` or `Projection` classes on instantiation.
- `backend`: Whether to use `Basemap` or `Projection` for map projections.
- `left, right, top, bottom`: The fixed space between the subplots and the figure edge.
- `wspace, hspace, space`: The fixed space between grid columns, rows, and both, respectively.
- `wratios, hratios`: Passed to [GridSpec](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.gridspec.GridSpec.html), denotes the width and height ratios for the subplot grid.
- `wpad, hpad, pad`: The tight layout padding between columns, rows, and both, respectively.
- `wequal, hequal, equal`: Whether to make the tight layout algorithm apply equal spacing between columns, rows, or both.
- `wgroup, hgroup, group`: Whether to make the tight layout algorithm just consider spaces between adjacent subplots instead of entire columns and rows of subplots.
- `outerpad`: The scalar tight layout padding around the left, right, top, bottom figure edges.
- `innerpad`: The scalar tight layout padding between columns and rows.
- `panelpad`: The scalar tight layout padding between subplots and their panels, colorbars, and legends and between "stacks" of these objects.
- `refnum`: The reference subplot number.
- `refaspect`: The reference subplot aspect ratio.
- `refwidth, refheight`: The width, height of the reference subplot.
- `figwidth, figheight`: The figure width and height.
- `figsize`: Tuple specifying the figure ``(width, height)``.
- `sharex, sharey, share`: The axis sharing "level" for the *x* axis, *y* axis, or both axes.
- `spanx, spany, span`: Whether to use "spanning" axis labels for the *x* axis, *y* axis, or both axes.
- `alignx, aligny, align`: Whether to ["align" axis labels](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/align_labels_demo.html) for the *x* axis, *y* axis, or both axes.
- `tight`: Whether automatic calls to `~Figure.auto_layout` should include [tight layout adjustments](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight).
- `journal`: String corresponding to an academic journal standard used to control the figure width `figwidth` and, if specified, the figure height `figheight`.
- `**kwargs`: Passed to the ultraplot class [ultraplot.axes.CartesianAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.CartesianAxes.html), [ultraplot.axes.PolarAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.PolarAxes.html), [ultraplot.axes.GeoAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html), or [ultraplot.axes.ThreeAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.ThreeAxes.html).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.add_subplots)"""
        ...

    def subplots(self, *args: Incomplete, **kwargs: Incomplete) -> pgridspec.SubplotGrid:
        """Add an arbitrary grid of subplots to the figure.

Parameters
----------
- `array`: The subplot grid specifier.
- `nrows, ncols`: The number of rows and columns in the subplot grid.
- `order`: Whether subplots are numbered in column-major (``'C'``) or row-major (``'F'``) order.
- `proj, projection`: The map projection specification(s).
- `proj_kw, projection_kw`: Keyword arguments passed to `Basemap` or `Projection` classes on instantiation.
- `backend`: Whether to use `Basemap` or `Projection` for map projections.
- `left, right, top, bottom`: The fixed space between the subplots and the figure edge.
- `wspace, hspace, space`: The fixed space between grid columns, rows, and both, respectively.
- `wratios, hratios`: Passed to [GridSpec](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.gridspec.GridSpec.html), denotes the width and height ratios for the subplot grid.
- `wpad, hpad, pad`: The tight layout padding between columns, rows, and both, respectively.
- `wequal, hequal, equal`: Whether to make the tight layout algorithm apply equal spacing between columns, rows, or both.
- `wgroup, hgroup, group`: Whether to make the tight layout algorithm just consider spaces between adjacent subplots instead of entire columns and rows of subplots.
- `outerpad`: The scalar tight layout padding around the left, right, top, bottom figure edges.
- `innerpad`: The scalar tight layout padding between columns and rows.
- `panelpad`: The scalar tight layout padding between subplots and their panels, colorbars, and legends and between "stacks" of these objects.
- `refnum`: The reference subplot number.
- `refaspect`: The reference subplot aspect ratio.
- `refwidth, refheight`: The width, height of the reference subplot.
- `figwidth, figheight`: The figure width and height.
- `figsize`: Tuple specifying the figure ``(width, height)``.
- `sharex, sharey, share`: The axis sharing "level" for the *x* axis, *y* axis, or both axes.
- `spanx, spany, span`: Whether to use "spanning" axis labels for the *x* axis, *y* axis, or both axes.
- `alignx, aligny, align`: Whether to ["align" axis labels](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/align_labels_demo.html) for the *x* axis, *y* axis, or both axes.
- `tight`: Whether automatic calls to `~Figure.auto_layout` should include [tight layout adjustments](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight).
- `journal`: String corresponding to an academic journal standard used to control the figure width `figwidth` and, if specified, the figure height `figheight`.
- `**kwargs`: Passed to the ultraplot class [ultraplot.axes.CartesianAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.CartesianAxes.html), [ultraplot.axes.PolarAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.PolarAxes.html), [ultraplot.axes.GeoAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.GeoAxes.html), or [ultraplot.axes.ThreeAxes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.ThreeAxes.html).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.subplots)"""
        ...

    def auto_layout(self, renderer: Incomplete=None, aspect: Incomplete=None, tight: Incomplete=None, resize: Incomplete=None) -> None:
        """Automatically adjust the figure size and subplot positions. This is
triggered automatically whenever the figure is drawn.

Parameters
----------
renderer : [RendererBase](https://matplotlib.org/stable/api/_as_gen/matplotlib.backend_bases.RendererBase.html), optional
    The renderer. If ``None`` a default renderer will be produced.
aspect : bool, optional
    Whether to update the figure size based on the reference subplot aspect
    ratio. By default, this is ``True``. This only has an effect if the
    aspect ratio is fixed (e.g., due to an image plot or geographic projection).
tight : bool, optional
    Whether to update the figuer size and subplot positions according to
    a "tight layout". By default, this takes on the value of `tight` passed
    to `Figure`. If nothing was passed, it is [subplots.tight](https://ultraplot.readthedocs.io/en/stable/search.html?q=subplots.tight).
resize : bool, optional
    If ``False``, the current figure dimensions are fixed and automatic
    figure resizing is disabled. By default, the figure size may change
    unless both `figwidth` and `figheight` or `figsize` were passed
    to `~Figure.subplots`, `~Figure.set_size_inches` was called manually,
    or the figure was resized manually with an interactive backend."""
        ...

    def format(self, axs: Incomplete=None, *, figtitle: Incomplete=None, suptitle: Incomplete=None, suptitle_kw: Incomplete=None, llabels: Incomplete=None, leftlabels: Incomplete=None, leftlabels_kw: Incomplete=None, rlabels: Incomplete=None, rightlabels: Incomplete=None, rightlabels_kw: Incomplete=None, blabels: Incomplete=None, bottomlabels: Incomplete=None, bottomlabels_kw: Incomplete=None, tlabels: Incomplete=None, toplabels: Incomplete=None, toplabels_kw: Incomplete=None, rowlabels: Incomplete=None, collabels: Incomplete=None, includepanels: Incomplete=None, **kwargs: Incomplete) -> None:
        """Modify figure-wide labels and call ``format`` for the input axes.

Parameters
----------
- `axs`: The axes to format.
- `leftlabels, toplabels, rightlabels, bottomlabels`: Labels for the subplots lying along the left, top, right, and bottom edges of the figure.
- `leftlabelpad, toplabelpad, rightlabelpad, bottomlabelpad`: : [leftlabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=leftlabel.pad), [toplabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=toplabel.pad), [rightlabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=rightlabel.pad), [bottomlabel.pad](https://ultraplot.readthedocs.io/en/stable/search.html?q=bottomlabel.pad) The padding between the labels and the axes content.
- `leftlabelsharedpad, toplabelsharedpad, rightlabelsharedpad, bottomlabelsharedpad`: : [leftlabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=leftlabel.sharedpad), [toplabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=toplabel.sharedpad), [rightlabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=rightlabel.sharedpad), [bottomlabel.sharedpad](https://ultraplot.readthedocs.io/en/stable/search.html?q=bottomlabel.sharedpad) The padding between side labels and a shared spanning axis label on…
- `leftlabels_kw, toplabels_kw, rightlabels_kw, bottomlabels_kw`: Additional settings used to update the labels with ``text.update()``.
- `figtitle`: Alias for `suptitle`.
- `suptitle`: The figure "super" title, centered between the left edge of the leftmost subplot and the right edge of the rightmost subplot.
- `suptitlepad`: The padding between the super title and the axes content.
- `suptitle_kw`: Additional settings used to update the super title with ``text.update()``.
- `includepanels`: Whether to include panels when aligning figure "super titles" along the top of the subplot grid and when aligning the `spanx` *x* axis labels and `spany` *y* axis labels along the…
- `title`: The axes title.
- `abc`: The "a-b-c" subplot label style.
- `abcloc, titleloc`: Strings indicating the location for the a-b-c label and main title.
- `abcborder, titleborder`: Whether to draw a white border around titles and a-b-c labels positioned inside the axes.
- `abcbbox, titlebbox`: Whether to draw a white bbox around titles and a-b-c labels positioned inside the axes.
- `abcpad`: Horizontal offset to shift the a-b-c label position.
- `abc_kw, title_kw`: Additional settings used to update the a-b-c label and title with ``text.update()``.
- `titlepad`: The padding for the inner and outer titles and a-b-c labels.
- `titleabove`: Whether to try to put outer titles and a-b-c labels above panels, colorbars, or legends that are above the axes.
- `abctitlepad`: The horizontal padding between a-b-c labels and titles in the same location.
- `ltitle, ctitle, rtitle, ultitle, uctitle, urtitle, lltitle, lctitle, lrtitle`: Shorthands for the below keywords.
- `lowerlefttitle, lowercentertitle, lowerrighttitle`: Additional titles in specific positions (see `title` for details).
- `a, alpha, fc, facecolor, ec, edgecolor, lw, linewidth, ls, linestyle`: [axes.alpha](https://ultraplot.readthedocs.io/en/stable/search.html?q=axes.alpha) (default: 1.0), [axes.facecolor](https://ultraplot.readthedocs.io/en/stable/search.html?q=axes.facecolor) (default: white), [axes.edgecolor](https://ultraplot.readthedocs.io/en/stable/search.html?q=axes.edgecolor) (default: black), [axes.linewidth](https://ultraplot.readthedocs.io/en/stable/search.html?q=axes.linewidth) (default: 0.6), - Additional settings applied to…
- `aspect`: The data aspect ratio.
- `xlabel, ylabel`: The x and y axis labels.
- `xlabel_kw, ylabel_kw`: Additional axis label settings applied with [set_xlabel](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_xlabel.html) and [set_ylabel](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_ylabel.html).
- `xlim, ylim`: The x and y axis data limits.
- `xmin, ymin`: The x and y minimum data limits.
- `xmax, ymax`: The x and y maximum data limits.
- `xreverse, yreverse`: Whether to "reverse" the x and y axis direction.
- `xscale, yscale`: The x and y axis scales.
- `xscale_kw, yscale_kw`: The x and y axis scale settings.
- `xmargin, ymargin, margin`: The default margin between plotted content and the x and y axis spines in axes-relative coordinates.
- `xbounds, ybounds`: The x and y axis data bounds within which to draw the spines.
- `xtickrange, ytickrange`: The x and y axis data ranges within which major tick marks are labelled.
- `xwraprange, ywraprange`: The x and y axis data ranges with which major tick mark values are wrapped.
- _97 additional parameter groups are documented online._

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.format)"""
        ...

    def colorbar(self, mappable: Incomplete, values: Incomplete=None, loc: Optional[str]=None, location: Optional[str]=None, row: Optional[int]=None, col: Optional[int]=None, rows: Optional[Union[int, Tuple[int, int]]]=None, cols: Optional[Union[int, Tuple[int, int]]]=None, span: Optional[Union[int, Tuple[int, int]]]=None, space: Optional[Union[float, str]]=None, pad: Optional[Union[float, str]]=None, width: Optional[Union[float, str]]=None, **kwargs: Incomplete) -> Incomplete:
        """Add a colorbar along the side of the figure.

Parameters
----------
- `length`: The colorbar length.
- `shrink`: Alias for `length`.
- `width`: The colorbar width.
- `loc`: The colorbar location.
- `space`: The fixed space between the colorbar and the subplot grid edge.
- `pad`: The [tight layout padding](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight) between the colorbar and the subplot grid.
- `span`: Integer(s) indicating the span of the colorbar across rows and columns of subplots.
- `align`: For outer colorbars only.
- `orientation`: The colorbar orientation.
- `norm`: Ignored if `mappable` is a [ScalarMappable](https://matplotlib.org/stable/api/_as_gen/matplotlib.cm.ScalarMappable.html).
- `norm_kw`: Ignored if `mappable` is a [ScalarMappable](https://matplotlib.org/stable/api/_as_gen/matplotlib.cm.ScalarMappable.html).
- `vmin, vmax`: Ignored if `mappable` is a [ScalarMappable](https://matplotlib.org/stable/api/_as_gen/matplotlib.cm.ScalarMappable.html).
- `label, title`: The colorbar label.
- `reverse`: Whether to reverse the direction of the colorbar.
- `rotation`: The tick label rotation.
- `grid, edges, drawedges`: Whether to draw "grid" dividers between each distinct color.
- `extend`: Direction for drawing colorbar "extensions" (i.e.
- `extendfrac`: The length of the colorbar "extensions" relative to the length of the colorbar.
- `extendsize`: The length of the colorbar "extensions" in physical units.
- `extendrect`: Whether to draw colorbar "extensions" as rectangles.
- `locator, ticks`: Used to determine the colorbar tick positions.
- `locator_kw`: Keyword arguments passed to [matplotlib.ticker.Locator](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Locator.html) class.
- `minorlocator_kw`: As with `locator_kw`, but for the minor ticks.
- `format, formatter, ticklabels`: The tick label format.
- `formatter_kw`: Keyword arguments passed to [matplotlib.ticker.Formatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.ticker.Formatter.html) class.
- `frame, frameon`: For inset colorbars, indicates whether to draw a background "frame", just like [legend](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html).
- `tickminor`: Whether to add minor ticks using [minorticks_on](https://matplotlib.org/stable/api/_as_gen/matplotlib.colorbar.ColorbarBase.minorticks_on.html).
- `tickloc, ticklocation`: Where to draw tick marks on the colorbar.
- `tickdir, tickdirection`: Direction of major and minor colorbar ticks.
- `ticklen`: Major tick lengths for the colorbar ticks.
- `ticklenratio`: Relative scaling of `ticklen` used to determine minor tick lengths.
- `tickwidth`: Major tick widths for the colorbar ticks.
- `tickwidthratio`: Relative scaling of `tickwidth` used to determine minor tick widths.
- `ticklabelcolor, ticklabelsize, ticklabelweight`: The font color, size, and weight for colorbar tick labels
- `labelloc, labellocation`: The colorbar label location.
- `labelcolor, labelsize, labelweight`: The font color, size, and weight for the colorbar label.
- _22 additional parameter groups are documented online._

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.colorbar)"""
        ...

    def legend(self, handles: Incomplete=None, labels: Incomplete=None, loc: Incomplete=None, location: Incomplete=None, row: Incomplete=None, col: Incomplete=None, rows: Incomplete=None, cols: Incomplete=None, span: Incomplete=None, space: Incomplete=None, pad: Incomplete=None, width: Incomplete=None, **kwargs: Incomplete) -> Incomplete:
        """Add a legend along the side of the figure.

Parameters
----------
- `handles`: List of matplotlib artists, or a list of lists of artist instances (see the `center` keyword).
- `labels`: A matching list of string labels or ``None`` placeholders, or a matching list of lists (see the `center` keyword).
- `loc`: The legend location.
- `space`: The fixed space between the legend and the subplot grid edge.
- `pad`: The [tight layout padding](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight) between the legend and the subplot grid.
- `span`: Integer(s) indicating the span of the legend across rows and columns of subplots.
- `align`: For outer legends only.
- `width`: The space allocated for the legend box.
- `frame, frameon`: Toggles the legend frame.
- `ncol, ncols`: The number of columns.
- `order`: Whether legend handles are drawn in row-major (``'C'``) or column-major (``'F'``) order.
- `center`: Whether to center each legend row individually.
- `alphabetize`: Whether to alphabetize the legend entries according to the legend labels.
- `title, label`: The legend title.
- `fontsize, fontweight, fontcolor`: The font size, weight, and color for the legend text.
- `titlefontsize, titlefontweight, titlefontcolor`: The font size, weight, and color for the legend title.
- `borderpad, borderaxespad, handlelength, handleheight, handletextpad, labelspacing, columnspacing`: Various matplotlib [legend](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html) spacing arguments.
- `a, alpha, framealpha, fc, facecolor, framecolor, ec, edgecolor, ew, edgewidth`: See the full API documentation.
- `c, color, lw, linewidth, m, marker, ls, linestyle, dashes, ms, markersize`: Properties used to override the legend handles.
- `handle_kw`: Additional properties used to override legend handles, e.g.
- `handler_map`: A dictionary mapping instances or types to a legend handler.
- `**kwargs`: Passed to [legend](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html).
- `bbox_to_anchor`: Box that is used to position the legend in conjunction with *loc*.
- `ncols`: The number of columns that the legend has.
- `prop`: The font properties of the legend.
- `fontsize`: The font size of the legend.
- `labelcolor`: The color of the text in the legend.
- `numpoints`: The number of marker points in the legend when creating a legend entry for a `.Line2D` (line).
- `scatterpoints`: The number of marker points in the legend when creating a legend entry for a `.PathCollection` (scatter plot).
- `scatteryoffsets`: The vertical offset (relative to the font size) for the markers created for a scatter plot legend entry.
- `markerscale`: The relative size of legend markers compared to the originally drawn ones.
- `markerfirst`: If *True*, legend marker is placed to the left of the legend label.
- `reverse`: If *True*, the legend labels are displayed in reverse order from the input.
- `frameon`: Whether the legend should be drawn on a patch (frame).
- `fancybox`: Whether round edges should be enabled around the `.FancyBboxPatch` which makes up the legend's background.
- `shadow`: Whether to draw a shadow behind the legend.
- _17 additional parameter groups are documented online._

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.legend)"""
        ...

    def save(self, filename: Incomplete, **kwargs: Incomplete) -> None:
        """Save the figure.

Parameters
----------
path : path-like, optional
    The file path. User paths are expanded with `os.path.expanduser`.
**kwargs
    Passed to [savefig](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.savefig.html)

See also
--------
Figure.save
Figure.savefig
matplotlib.figure.Figure.savefig"""
        ...

    def savefig(self, filename: Incomplete, **kwargs: Incomplete) -> None:
        """Save the figure.

Parameters
----------
- `path`: The file path.
- `**kwargs`: Passed to [savefig](https://matplotlib.org/stable/api/_as_gen/matplotlib.figure.Figure.savefig.html)
- `fname`: A path, or a Python file-like object, or possibly some backend-dependent object such as [matplotlib.backends.backend_pdf.PdfPages](https://matplotlib.org/stable/api/_as_gen/matplotlib.backends.backend_pdf.PdfPages.html).
- `transparent`: If *True*, the Axes patches will all be transparent; the Figure patch will also be transparent unless *facecolor* and/or *edgecolor* are specified via kwargs.
- `dpi`: The resolution in dots per inch.
- `format`: The file format, e.g.
- `metadata`: Key/value pairs to store in the image metadata.
- `bbox_inches`: Bounding box in inches: only the given portion of the figure is saved.
- `pad_inches`: Amount of padding in inches around the figure when bbox_inches is 'tight'.
- `facecolor`: The facecolor of the figure.
- `edgecolor`: The edgecolor of the figure.
- `backend`: Use a non-default backend to render the file, e.g.
- `orientation`: Currently only supported by the postscript backend.
- `papertype`: One of 'letter', 'legal', 'executive', 'ledger', 'a0' through 'a10', 'b0' through 'b10'.
- `bbox_extra_artists`: A list of extra artists that will be considered when the tight bbox is calculated.
- `pil_kwargs`: Additional keyword arguments that are passed to `PIL.Image.Image.save` when saving the figure.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.savefig)"""
        ...

    def set_canvas(self, canvas: Incomplete) -> None:
        """Set the figure canvas. Add monkey patches for the instance-level
[draw](https://matplotlib.org/stable/api/_as_gen/matplotlib.backend_bases.FigureCanvasBase.draw.html) and
[print_figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.backend_bases.FigureCanvasBase.print_figure.html) methods.

Parameters
----------
canvas : [FigureCanvasBase](https://matplotlib.org/stable/api/_as_gen/matplotlib.backend_bases.FigureCanvasBase.html)
    The figure canvas.

See also
--------
matplotlib.figure.Figure.set_canvas

Matplotlib documentation


Set the canvas that contains the figure

Parameters
----------
canvas : FigureCanvas"""
        ...

    def _is_same_size(self, figsize: Incomplete, eps: Incomplete=None) -> Incomplete:
        """Test if the figure size is unchanged up to some tolerance in inches."""
        ...

    def set_size_inches(self, w: Incomplete, h: Incomplete=None, *, forward: Incomplete=True, internal: Incomplete=False, eps: Incomplete=None) -> None:
        """Set the figure size. If this is being called manually or from an interactive
backend, update the default layout with this fixed size. If the figure size is
unchanged or this is an internal call, do not update the default layout.

Parameters
----------
*args : float
    The width and height passed as positional arguments or a 2-tuple.
forward : bool, optional
    Whether to update the canvas.
internal : bool, optional
    Whether this is an internal resize.
eps : float, optional
    The deviation from the current size in inches required to treat this
    as a user-triggered figure resize that fixes the layout.

See also
--------
matplotlib.figure.Figure.set_size_inches

Matplotlib documentation


Set the figure size in inches.

Call signatures::

     fig.set_size_inches(w, h)  # OR
     fig.set_size_inches((w, h))

Parameters
----------
w : (float, float) or float
    Width and height in inches (if height not specified as a separate
    argument) or width.
h : float
    Height in inches.
forward : bool, default: True
    If ``True``, the canvas size is automatically updated, e.g.,
    you can resize the figure window from the shell.

See Also
--------
matplotlib.figure.Figure.get_size_inches
matplotlib.figure.Figure.set_figwidth
matplotlib.figure.Figure.set_figheight

Notes
-----
To transform from pixels to inches divide by `Figure.dpi`."""
        ...

    def _iter_axes(self, hidden: Incomplete=False, children: Incomplete=False, panels: Incomplete=True) -> Incomplete:
        """Iterate over all axes and panels in the figure belonging to the
[Axes](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html) class. Exclude inset and twin axes.

Parameters
----------
hidden : bool, optional
    Whether to include "hidden" panels.
children : bool, optional
    Whether to include child axes. Note this now includes "twin" axes.
panels : bool or str or sequence of str, optional
    Whether to include panels or the panels to include."""
        ...

    @property
    def gridspec(self) -> Incomplete:
        """The single [GridSpec](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.gridspec.GridSpec.html) instance used for all
subplots in the figure.

See also
--------
ultraplot.figure.Figure.subplotgrid
ultraplot.gridspec.GridSpec.figure
ultraplot.gridspec.SubplotGrid.gridspec"""
        ...

    @gridspec.setter
    def gridspec(self, gs: Incomplete) -> None:
        """The single [GridSpec](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.gridspec.GridSpec.html) instance used for all
subplots in the figure.

See also
--------
ultraplot.figure.Figure.subplotgrid
ultraplot.gridspec.GridSpec.figure
ultraplot.gridspec.SubplotGrid.gridspec"""
        ...

    def _get_subplot(self, number: int) -> Incomplete:
        """Return the subplot with the given *number*, or ``None``."""
        ...

    def _iter_subplots(self) -> Incomplete:
        """Iterate over all numbered subplots."""
        ...

    @property
    def subplotgrid(self) -> Incomplete:
        """A [SubplotGrid](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.gridspec.SubplotGrid.html) containing the numbered subplots in the
figure. The subplots are ordered by increasing [number](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.axes.Axes.html#ultraplot.axes.Axes.number).

See also
--------
ultraplot.figure.Figure.gridspec
ultraplot.gridspec.SubplotGrid.figure"""
        ...

    @property
    def tight(self) -> Incomplete:
        """Whether the [tight layout algorithm](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight) is active for the
figure. This value is passed to [auto_layout](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.auto_layout)
every time the figure is drawn. Can be changed e.g. ``fig.tight = False``.

See also
--------
ultraplot.figure.Figure.auto_layout"""
        ...

    @tight.setter
    def tight(self, b: Incomplete) -> None:
        ...
    _format_signature = inspect.signature(format)
    format = docstring._obfuscate_kwargs(format)
