# @generated by tools/generate_stubs.py; do not edit
# fmt: off
"""
The starting point for creating ultraplot figures.
"""
from _typeshed import Incomplete
import matplotlib.pyplot as plt
from . import axes as paxes
from . import figure as pfigure
from . import gridspec as pgridspec
from ._subplots import SubplotManager
from .figure import Figure
from .internals import _not_none, _pop_params, _pop_props, _pop_rc, docstring, ic
__all__ = ['figure', 'subplot', 'subplots', 'show', 'close', 'switch_backend', 'ion', 'ioff', 'isinteractive']
_pyplot_docstring = ...

def _parse_figsize(kwargs: Incomplete) -> Incomplete:
    """Translate `figsize` into ultraplot-specific `figwidth` and `figheight` keys."""
    ...

def show(*args: Incomplete, **kwargs: Incomplete) -> None:
    """Call [matplotlib.pyplot.show](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html).
This is included so you don't have to import [pyplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html).

Parameters
----------
*args, **kwargs
    Passed to [matplotlib.pyplot.show](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html)."""
    ...

def close(*args: Incomplete, **kwargs: Incomplete) -> None:
    """Call [matplotlib.pyplot.close](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.close.html).
This is included so you don't have to import [pyplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html).

Parameters
----------
*args, **kwargs
    Passed to [matplotlib.pyplot.close](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.close.html)."""
    ...

def switch_backend(*args: Incomplete, **kwargs: Incomplete) -> None:
    """Call [matplotlib.pyplot.switch_backend](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.switch_backend.html).
This is included so you don't have to import [pyplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html).

Parameters
----------
*args, **kwargs
    Passed to [matplotlib.pyplot.switch_backend](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.switch_backend.html)."""
    ...

def ion() -> Incomplete:
    """Call [matplotlib.pyplot.ion](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ion.html).
This is included so you don't have to import [pyplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html)."""
    ...

def ioff() -> Incomplete:
    """Call [matplotlib.pyplot.ioff](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ioff.html).
This is included so you don't have to import [pyplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html)."""
    ...

def isinteractive() -> bool:
    """Call [matplotlib.pyplot.isinteractive](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.isinteractive.html).
This is included so you don't have to import [pyplot](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html)."""
    ...

def figure(**kwargs: Incomplete) -> Figure:
    """Create an empty figure.

Parameters
----------
- `refnum`: The reference subplot number.
- `refaspect`: The reference subplot aspect ratio.
- `refwidth, refheight`: The width, height of the reference subplot.
- `figwidth, figheight`: The figure width and height.
- `figsize`: Tuple specifying the figure ``(width, height)``.
- `sharex, sharey, share`: The axis sharing "level" for the *x* axis, *y* axis, or both axes.
- `spanx, spany, span`: Whether to use "spanning" axis labels for the *x* axis, *y* axis, or both axes.
- `alignx, aligny, align`: Whether to ["align" axis labels](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/align_labels_demo.html) for the *x* axis, *y* axis, or both axes.
- `left, right, top, bottom`: The fixed space between the subplots and the figure edge.
- `wspace, hspace, space`: The fixed space between grid columns, rows, or both.
- `tight`: Whether automatic calls to `~Figure.auto_layout` should include [tight layout adjustments](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight).
- `wequal, hequal, equal`: Whether to make the tight layout algorithm apply equal spacing between columns, rows, or both.
- `wgroup, hgroup, group`: Whether to make the tight layout algorithm just consider spaces between adjacent subplots instead of entire columns and rows of subplots.
- `outerpad`: The scalar tight layout padding around the left, right, top, bottom figure edges.
- `innerpad`: The scalar tight layout padding between columns and rows.
- `panelpad`: The scalar tight layout padding between subplots and their panels, colorbars, and legends and between "stacks" of these objects.
- `journal`: String corresponding to an academic journal standard used to control the figure width `figwidth` and, if specified, the figure height `figheight`.
- `**kwargs`: Passed to [ultraplot.figure.Figure.format](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.format).

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.ui.figure.html)"""
    ...

def subplot(**kwargs: Incomplete) -> tuple[Figure, paxes.Axes]:
    """Return a figure and a single subplot.

Parameters
----------
- `refnum`: The reference subplot number.
- `refaspect`: The reference subplot aspect ratio.
- `refwidth, refheight`: The width, height of the reference subplot.
- `figwidth, figheight`: The figure width and height.
- `figsize`: Tuple specifying the figure ``(width, height)``.
- `sharex, sharey, share`: The axis sharing "level" for the *x* axis, *y* axis, or both axes.
- `spanx, spany, span`: Whether to use "spanning" axis labels for the *x* axis, *y* axis, or both axes.
- `alignx, aligny, align`: Whether to ["align" axis labels](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/align_labels_demo.html) for the *x* axis, *y* axis, or both axes.
- `left, right, top, bottom`: The fixed space between the subplots and the figure edge.
- `wspace, hspace, space`: The fixed space between grid columns, rows, or both.
- `tight`: Whether automatic calls to `~Figure.auto_layout` should include [tight layout adjustments](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight).
- `wequal, hequal, equal`: Whether to make the tight layout algorithm apply equal spacing between columns, rows, or both.
- `wgroup, hgroup, group`: Whether to make the tight layout algorithm just consider spaces between adjacent subplots instead of entire columns and rows of subplots.
- `outerpad`: The scalar tight layout padding around the left, right, top, bottom figure edges.
- `innerpad`: The scalar tight layout padding between columns and rows.
- `panelpad`: The scalar tight layout padding between subplots and their panels, colorbars, and legends and between "stacks" of these objects.
- `journal`: String corresponding to an academic journal standard used to control the figure width `figwidth` and, if specified, the figure height `figheight`.
- `**kwargs`: Passed to [ultraplot.figure.Figure.format](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.format) or the projection-specific ``format`` command for the axes.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.ui.subplot.html)"""
    ...

def subplots(*args: Incomplete, **kwargs: Incomplete) -> tuple[Figure, pgridspec.SubplotGrid]:
    """Return a figure and an arbitrary grid of subplots.

Parameters
----------
- `array`: The subplot grid specifier.
- `nrows, ncols`: The number of rows and columns in the subplot grid.
- `order`: Whether subplots are numbered in column-major (``'C'``) or row-major (``'F'``) order.
- `proj, projection`: The map projection specification(s).
- `proj_kw, projection_kw`: Keyword arguments passed to `Basemap` or `Projection` classes on instantiation.
- `backend`: Whether to use `Basemap` or `Projection` for map projections.
- `left, right, top, bottom`: The fixed space between the subplots and the figure edge.
- `wspace, hspace, space`: The fixed space between grid columns, rows, and both, respectively.
- `wratios, hratios`: Passed to [GridSpec](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.gridspec.GridSpec.html), denotes the width and height ratios for the subplot grid.
- `wpad, hpad, pad`: The tight layout padding between columns, rows, and both, respectively.
- `wequal, hequal, equal`: Whether to make the tight layout algorithm apply equal spacing between columns, rows, or both.
- `wgroup, hgroup, group`: Whether to make the tight layout algorithm just consider spaces between adjacent subplots instead of entire columns and rows of subplots.
- `outerpad`: The scalar tight layout padding around the left, right, top, bottom figure edges.
- `innerpad`: The scalar tight layout padding between columns and rows.
- `panelpad`: The scalar tight layout padding between subplots and their panels, colorbars, and legends and between "stacks" of these objects.
- `refnum`: The reference subplot number.
- `refaspect`: The reference subplot aspect ratio.
- `refwidth, refheight`: The width, height of the reference subplot.
- `figwidth, figheight`: The figure width and height.
- `figsize`: Tuple specifying the figure ``(width, height)``.
- `sharex, sharey, share`: The axis sharing "level" for the *x* axis, *y* axis, or both axes.
- `spanx, spany, span`: Whether to use "spanning" axis labels for the *x* axis, *y* axis, or both axes.
- `alignx, aligny, align`: Whether to ["align" axis labels](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/align_labels_demo.html) for the *x* axis, *y* axis, or both axes.
- `tight`: Whether automatic calls to `~Figure.auto_layout` should include [tight layout adjustments](https://ultraplot.readthedocs.io/en/stable/search.html?q=ug_tight).
- `journal`: String corresponding to an academic journal standard used to control the figure width `figwidth` and, if specified, the figure height `figheight`.
- `**kwargs`: Passed to [ultraplot.figure.Figure.format](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.figure.Figure.html#ultraplot.figure.Figure.format) or the projection-specific ``format`` command for each axes.

[Full API documentation](https://ultraplot.readthedocs.io/en/stable/api/ultraplot.ui.subplots.html)"""
    ...
