name: Archive Plot Comparison Results

on:
  workflow_run:
    workflows: ["Matrix Test"]
    types:
      - completed

jobs:
  archive-test-results:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Download all artifacts from the triggered workflow
      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: any # We want results even if tests fail
          path: temp_artifacts

      # Create a timestamped archive directory
      - name: Prepare archive directory
        id: prepare
        run: |
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          SHA_SHORT=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)
          PR_NUMBER=$(echo "${{ github.event.workflow_run.head_branch }}" | grep -oP 'pull/\K\d+' || echo "main")

          if [[ "$PR_NUMBER" == "main" ]]; then
            BRANCH_INFO="main"
          else
            BRANCH_INFO="pr-${PR_NUMBER}"
          fi

          ARCHIVE_DIR="mpl-results/${TIMESTAMP}_${SHA_SHORT}_${BRANCH_INFO}"
          echo "archive_dir=${ARCHIVE_DIR}" >> $GITHUB_OUTPUT

          mkdir -p "docs/_static/${ARCHIVE_DIR}"

          # Copy HTML results from each configuration into the archive
          find temp_artifacts -name "*.html" -o -name "*.png" | while read file; do
            # Extract config from artifact folder name
            artifact_folder=$(dirname "$file")
            config=$(basename "$artifact_folder" | sed -E 's/failed-comparisons-([^-]+)-([^-]+).*/\1-\2/')

            # Create config subdirectory
            mkdir -p "docs/_static/${ARCHIVE_DIR}/${config}"

            # Copy the file
            cp "$file" "docs/_static/${ARCHIVE_DIR}/${config}/"
          done

          # Record this run in the archives list
          if [ ! -f "docs/_static/mpl-results/archives.txt" ]; then
            mkdir -p "docs/_static/mpl-results"
            touch "docs/_static/mpl-results/archives.txt"
          fi

          # Add new archive at the beginning of the file (keeping only last 20 runs)
          echo "${ARCHIVE_DIR}|${{ github.event.workflow_run.display_title }}|${TIMESTAMP}|${SHA_SHORT}|${BRANCH_INFO}" > temp_archives.txt
          cat "docs/_static/mpl-results/archives.txt" | head -n 19 >> temp_archives.txt
          mv temp_archives.txt "docs/_static/mpl-results/archives.txt"

      - name: Generate archive index page
        run: |
          cat > docs/plot_comparison_results.rst << 'EOF'
          Plot Comparison Results
          =======================

          This page provides links to the results of UltraPlot test comparisons from CI runs.

          .. list-table::
             :widths: 15 15 45 25
             :header-rows: 1

             * - Date/Time
               - Commit
               - Workflow
               - Test Results
          EOF

          # Add entry for each archive from the archives.txt file
          while IFS="|" read -r dir title timestamp sha branch; do
            if [ -n "$dir" ]; then
              date_formatted=$(echo $timestamp | sed -E 's/([0-9]{4})([0-9]{2})([0-9]{2})_([0-9]{2})([0-9]{2})([0-9]{2})/\1-\2-\3 \4:\5:\6/')

              # Find all configuration directories
              configs=$(find "docs/_static/$dir" -type d -mindepth 1 -maxdepth 1 | sort)

              # Create list of links for each configuration
              config_links=""
              for config_path in $configs; do
                config=$(basename "$config_path")
                config_links="${config_links} | \`${config} <_static/${dir}/${config}/fig_comparison.html>\`__"
              done

              echo "   * - ${date_formatted}" >> docs/plot_comparison_results.rst
              echo "     - ${sha}" >> docs/plot_comparison_results.rst
              echo "     - ${title} (${branch})" >> docs/plot_comparison_results.rst
              echo "     - ${config_links}" >> docs/plot_comparison_results.rst
            fi
          done < "docs/_static/mpl-results/archives.txt"

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git add docs/_static/mpl-results/
          git add docs/plot_comparison_results.rst

          git commit -m "Update plot comparison archives [skip ci]" || echo "No changes to commit"
          git push
