name: Build docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-fonts-extra
          sudo fc-cache -fv
        # need tex-gyre-hero fonts to show text in geo plots
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2.0.4
        with:
          environment-file: ./environment.yml
      - name: Check dependencies
        run: |
          micromamba activate ultraplot-dev
          micromamba list
      - name: "Build docs"
        shell: bash -el {0}
        run: |
          micromamba activate ultraplot-dev
          pip install .
          cd docs
          make html
