name: Coverage and Badge
on:
  push:
    branches:
      - main

jobs:
  run-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2.0.4
        with:
          python-version: "3.10"
          environment-file: ./environment.yml

      - name: Install packages
        run: pip install pytest-cov genbadge

      - name: Run coverage
        run: pytest --cov=ultraplot --cover-report=term --cov-report=xml ultraplot/tests

      - name: Generate badge
        run: genbadge coverage -i coverage.xml

      - name: Upload report XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage-badge.svg
