name: Publish to PyPI
on:
  release:
    types: [published]
  push:
    tags: ["v*"]

jobs:
  publish-pypi-test:
    name: Publish to TestPyPI
    environment:
      name: test
      url: https://test.pypi.org/project/ultraplot/
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build package
        run: |
          python -m pip install build
          python -m build
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-prod:
    name: Publish to PyPI
    needs: publish-pypi-test
    environment:
      name: prod
      url: https://pypi.org/project/ultraplot/
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || (github.event_name == 'push' && needs.publish-pypi-test.result == 'success')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build package
        run: |
          python -m pip install build
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
